### ISSUE TITLE
launch_ironpython_server 

### ISSUE THREAD

**Issue by sdesharnais** [ansys/pyaedt#1116]
Hi,

A customer is trying to remotely launch Maxwell using the launch_ironpython_server command :

from pyaedt.common_rpc import launch_ironpython_server
client = launch_ironpython_server(aedt_path="/home/mengju/ansys/AnsysEM21.1/Linux64",  non_graphical=False, port=18000)
m2d = client.root.Maxwell2D(projectname = "ProjectName", designname = "DesignName", solution_type = "Transient", non_graphical = False)

She gets the following error message: AttributeError: 'PyaedtServiceWindows' object has no attribute 'Maxwell2d'

On the other hand, this code works well with HFSS, as shown in the example provided in the documentation.

This looks to me like this procedure isn’t (yet) designed to work with Maxwell: is that correct or did I miss something?

Thank you for your help,

**Comment by maxcapodi78** [comment]
Hello @sdesharnais the method is implemented. The customer should use the following syntax:

m2d = client.root.maxwell2d(projectname = "ProjectName", designname = "DesignName", solution_type = "Transient")

I've tested and works fine for me.

**Comment by sdesharnais** [comment]
Thank you Massimo.

Dr. Sébastien DESHARNAIS
Lead Application Engineer
***@***.******@***.***>

***@***.***

De : Massimo Capodiferro ***@***.***>
Envoyé : Monday, May 2, 2022 13:05
À : pyansys/pyaedt ***@***.***>
Cc : Sebastien Desharnais ***@***.***>; Mention ***@***.***>
Objet : Re: [pyansys/pyaedt] launch_ironpython_server (Issue #1116)


[External Sender]

Hello @sdesharnais<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsdesharnais&data=05%7C01%7Csebastien.desharnais%40ansys.com%7C8968b0276bb24055b0a608da2c2b974e%7C34c6ce6715b84eff80e952da8be89706%7C0%7C0%7C637870863007634141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q%2Bi5n4BnP7QvN6OKmiaZ9hK%2FYBPwdlzTc5XMeXAaHFI%3D&reserved=0> the method is implemented. The customer should use the following syntax:

m2d = client.root.maxwell2d(projectname = "ProjectName", designname = "DesignName", solution_type = "Transient")

I've tested and works fine for me.

-
