### ISSUE TITLE
Legacy client server connection always close the session.

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/pyaedt#1498]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The option `close_on_exit` is not available when we use the **legacy** client/server connection.

### Steps To Reproduce

On server side:
```
from pyaedt.common_rpc import launch_server
launch_server(port=5000)
```

On client side:
```
from pyaedt.common_rpc import client
my_client = client("MACHINE_NAME", server_port=5000)
m2d = my_client.root.maxwell2d(specified_version="2022.1", non_graphical=False, close_on_exit=False)
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

N/A

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey Is this issue fixed? Could we close the issue?

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys Let me try it again and I will confirm that to you.
