### ISSUE TITLE
Remove dependencies on libraries in $ANSYSEM_ROOT_PATH/Delcross or remove warning about this folder

### ISSUE THREAD

**Issue by isaacansys** [ansys/pyaedt#1704]
### Description of the feature

If $ANSYSEM_ROOT_PATH/Delcross is not in $LD_LIBRARY_PATH on Linux, PyAEDT will issue a warning.  This folder contains, among other libraries, Qt 5 libraries that may prevent the use of later Qt 5 versions by downstream apps that depend on PyAEDT.  In testing with such an app I found that at least EDB-only usage of PyAEDT seems to work without the Delcross folder in $LD_LIBRARY_PATH.

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey What do you think about this issue?

**Comment by maxcapodi78** [comment]
this may be probably removed in 23R2. I need to run some checks in linux
