### ISSUE TITLE
Add setter method to EDBPadstackInstance.pin_number

### ISSUE THREAD

**Issue by Marcel0000** [ansys/pyaedt#2436]
### Description of the feature

It would be great to have a setter method for pin numbers to EDBPadstackInstance.pin_number.

This should enable the possibility to rename pins easily without trigger pin removal from the component, as it is currently the case, when editing the pin name.

### Useful links and references

https://aedt.docs.pyansys.com/release/0.6/EDBAPI/_autosummary/pyaedt.edb_core.edb_data.padstacks_data.EDBPadstackInstance.pin_number.html#pyaedt.edb_core.edb_data.padstacks_data.EDBPadstackInstance.pin_number

**Comment by ring630** [comment]
@Marcel0000 I have done many experiments. It is a technical limitation.

**Comment by Marcel0000** [comment]
@ring630 alright, thanks for checking this out!

**Comment by Samuelopez-ansys** [comment]
@ring630 If it is a technical limitation of EDB, could we close this issue?

**Comment by ring630** [comment]
@Samuelopez-ansys Yes. I am closing it now.
