### ISSUE TITLE
Primitives3DLayout.place_3d_component() does not allow z-displacement

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyaedt#2508]
### Description of the feature

We need to implement z-displacement when placing 3D components to place components without intersecting existing geometry.

### Steps for implementing the feature

Native API Syntax to set z-position. Needs to be added to the method.
```
oProject = oDesktop.GetActiveProject()
oDesign = oProject.GetActiveDesign()
oEditor = oDesign.SetActiveEditor("Layout")
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:BaseElementTab",
			[
				"NAME:PropServers", 
				"92"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Location",
					"X:="			, "-0.8mm",
					"Y:="			, "0mm",
					"Z:="			, "0.6285mm"
				]
			]
		]
	])
```

**Comment by svandenb-dev** [comment]
@dcrawforAtAnsys 

You can move the 3D component assuming this code, placing a component then moving and rotating.
Is it something you are looking ?

  cmp_instance = hfss.modeler.insert_3d_component(cmp_file, name=cmp_refdes)
  if cmp_instance:
        hfss.modeler.move(cmp_refdes, [1, 1, 1])
        hfss.modeler.rotate(90)

**Comment by maxcapodi78** [comment]
@dcrawforAtAnsys  I've fixed it. you can change location of a placed component also with setter location:
com.location = [1,2,3]
