### ISSUE TITLE
pyaedt.launch_desktop seems to ignore new_desktop_session bool

### ISSUE THREAD

**Issue by camuher** [ansys/pyaedt#2623]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

pyaedt.launch_desktop(specified_version='2023.2',new_desktop_session=False) accepts the new_desktop_session bool but even when its set to false it opens a new desktop session

### Steps To Reproduce

#Have AEDT of the propper version open (or run the code snippet twice)
#AEDT build 2023-03-06
#pyaedt 0.6.55
import pyaedt
d = pyaedt.launch_desktop(specified_version='2023.2',new_desktop_session=False)
#at this point it should open a new aedt window (which is not the intended behavior)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

agi.stk12 @ file:///C:/Program%20Files/AGI/STK%2012/bin/AgPythonAPI/agi.stk12-12.4.0-py3-none-any.whl
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
black==21.12b0
bleach==4.1.0
certifi==2022.12.7
cffi==1.15.0
charset-normalizer==3.0.1
click==8.0.3
clr-loader==0.2.5
colorama==0.4.4
contourpy==1.0.7
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.3
executing==0.8.2
fonttools==4.28.5
idna==3.4
imageio==2.25.1
ipykernel==6.7.0
ipython==8.0.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.1.2
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
MarkupSafe==2.0.1
matplotlib==3.7.1
matplotlib-inline==0.1.3
mistune==0.8.4
mpmath==1.2.1
mypy-extensions==0.4.3
nbclient==0.5.10
nbconvert==6.4.0
nbformat==5.1.3
nest-asyncio==1.5.4
nose==1.3.7
notebook==6.4.7
numpy==1.24.2
packaging==21.3
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pickleshare==0.7.5
Pillow==9.0.0
platformdirs==2.4.1
plumbum==1.8.1
pooch==1.6.0
prometheus-client==0.12.0
prompt-toolkit==3.0.24
psutil==5.9.4
pure-eval==0.2.1
pyaedt==0.6.55
pycparser==2.21
Pygments==2.11.2
pyparsing==3.0.7
pypiwin32==223
pyrsistent==0.18.1
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2021.3
pyvista==0.38.2
pywin32==305
pywinpty==1.1.6
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.0
requests==2.28.2
rpyc==5.3.0
scikit-rf==0.25.0
scipy==1.10.1
scooby==0.7.1
Send2Trash==1.8.0
six==1.16.0
stack-data==0.1.4
sympy==1.9
terminado==0.12.1
testpath==0.5.0
tomli==1.2.3
tornado==6.1
traitlets==5.1.1
typing_extensions==4.0.1
urllib3==1.26.14
vtk==9.2.6
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.2

**Comment by maxcapodi78** [comment]
@camuher starting from 2023.1 we put GRPC Api as default one. that's why, your opened session of AEDT was not visible to the pyaedt session. 
You would need to open ansysedt.exe -grpcsrv portnumber to make it visible

Anyway. I've added a fall back criteria in latest pyaedt version so if it doesn't find GRPC Sessions opened but it finds a COM Session opened then it connects to it.
Please give it a try
