### ISSUE TITLE
Adding object priorities for Icepak components fails

### ISSUE THREAD

**Issue by StiftMC** [ansys/pyaedt#2667]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug
IcepakMesh.add_priority(entity_type, obj_list, comp_name=None, priority=3)

Function returns "Script macro error: Entity '2' is already in priority list '%2'"

![image](https://user-images.githubusercontent.com/100361281/226641058-51aebd56-3f84-45d1-8c9d-18bc2eb1d7d9.png)

If you have a PCB component in the design, there are already two entries in the priority list. 

![image](https://user-images.githubusercontent.com/100361281/226640053-263323f6-c2ba-4cc8-999c-c814235954ed.png)

### Steps To Reproduce

Import PCB with components. Call the function with list of components as obj_list and entity_type = 1 results in the mentioned error. Using the GUI with same inputs works. 

![image](https://user-images.githubusercontent.com/100361281/226640786-f187d1d6-c56c-4950-a214-03feb4223289.png)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

AEDTLib==1.5.36
aiohttp==3.8.1
aiosignal==1.2.0
altgraph==0.17
anyio==3.0.1
appdirs==1.4.4
argon2-cffi==20.1.0
async-generator==1.10
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.10.0
bleach==3.3.0
cachetools==5.0.0
certifi==2020.12.5
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.1.1
click==8.1.3
clr-loader==0.2.4
colorama==0.4.4
cycler==0.11.0
dataframe-image==0.1.5
decorator==5.0.7
defusedxml==0.7.1
entrypoints==0.3
et-xmlfile==1.1.0
fonttools==4.28.2
frozenlist==1.3.1
future==0.18.2
fuzzywuzzy==0.18.0
idna==2.10
imageio==2.21.3
importlib-metadata==4.0.1
ipykernel==5.5.4
ipython==7.23.1
ipython-genutils==0.2.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.1.0
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.2.0
jupyter-core==4.7.1
jupyter-server==1.7.0
jupyterlab==3.0.15
jupyterlab-pygments==0.1.2
jupyterlab-server==2.5.1
kiwisolver==1.3.2
MarkupSafe==1.1.1
matplotlib==3.5.0
matplotlib-inline==0.1.2
meshio==4.4.6
mistune==0.8.4
multidict==6.0.2
nbclassic==0.2.8
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
numpy==1.21.4
opencv-python==4.6.0.66
openpyxl==3.0.7
packaging==20.9
pandas==1.3.5
pandocfilters==1.4.3
parso==0.8.2
pefile==2021.5.24
pickleshare==0.7.5
Pillow==9.2.0
plumbum==1.7.2
prometheus-client==0.10.1
prompt-toolkit==3.0.18
psutil==5.9.2
py2exe==0.11.1.0
pyaedt==0.6.56
pycparser==2.20
Pygments==2.9.0
pyinstaller==4.10
pyinstaller-hooks-contrib==2021.1
pyodbc==4.0.31
pyparsing==2.4.7
pypiwin32==223
pyrsistent==0.17.3
python-certifi-win32==1.6
python-dateutil==2.8.2
python-Levenshtein==0.12.2
pythonnet==3.0.1
pytz==2021.3
pyvista==0.36.1
pywin32==304
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==6.0
pyzmq==22.0.3
regex==2022.6.2
requests==2.25.1
rpyc==5.3.0
SCLib==2.0.11804
scooby==0.6.0
Send2Trash==1.5.0
setuptools-scm==6.0.1
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.1
terminado==0.9.5
testpath==0.4.4
tornado==6.1
tqdm==4.64.0
traitlets==5.0.5
typing-extensions==3.10.0.0
urllib3==1.26.4
vtk==9.1.0
WBLib==2.0.4
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.59.0
wrapt==1.12.1
wslink==1.8.2
yarl==1.8.1
zipp==3.4.1

**Comment by Samuelopez-ansys** [comment]
@StiftMC I fixed the issue. You were passing all the object of the design, included the ones which belong to the 3DComponent, and it is now allowed. I have implemented a 'check' inside the method to discard the 3DComponent objects and the 'Sheets', because Priority does not take into account sheets
