### ISSUE TITLE
Bug located in sym-link creation of pyaedt\pyaedt\misc\aedtlib_personalib_install.py

### ISSUE THREAD

**Issue by kbhagat-ansys** [ansys/pyaedt#2675]
### Before submitting the issue

- [x] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The `aedtlib_personalib_install.py` is flawed when creating a sym-link to pyaedt on Linux. 
Currently, it checks if pyaedt symlink is present and it won't create it. Since the python virtual environments are version specific, it's best if we delete the sym-links and recreate it every time we run this script. Customers will end up running Install PyAEDT for every new version they install - thus we want this to reflect. 

### Steps To Reproduce

run aedtlib_personalib_install.py on Linux through the Install PyAEDT script from AEDT

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

N/A

**Comment by Samuelopez-ansys** [comment]
@kbhagat-ansys Could you help us and start a pull request with this modification? We will help you if you need further assistance.

**Comment by kbhagat-ansys** [comment]
> @kbhagat-ansys Could you help us and start a pull request with this modification? We will help you if you need further assistance.

@Samuelopez-ansys  Sounds good. Will look into it later this week or next.
