### ISSUE TITLE
License server configuration

### ISSUE THREAD

**Issue by akaszynski** [ansys/pyaedt#2743]
Please configure the CI/CD to use the `LICENSE_SERVER` secret within the PyAEDT workflows. This will allow us to smoothly change the configuration of the license server rather than relying on local configuration.

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey @SMoraisAnsys 

Maybe we could start checking this issue. We just need to add the License_server secret to the yaml right? And delete the license manager on each VM.

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys That is correct.
The only issue is that if you want to debug manually, you won't have any licenses available anymore.
I will give you more details in a meeting.
