### ISSUE TITLE
_make_winding does not use vertices from line.

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/pyaedt#2764]
https://github.com/pyansys/pyaedt/blob/dec3535c155e44363c3a5ec367914bdeb763625d/pyaedt/modeler/cad/Primitives3D.py#L2116-L2124

`list_positions2` list is extended but never used later.

**Comment by Samuelopez-ansys** [comment]
@maxcapodi78 I think we can remove these lines, right?

**Comment by MaxJPRey** [comment]
Yes we can. I should have done it instead of opening an issue 😄 .
