### ISSUE TITLE
Test _unittest/test_40_3dlayout_edb.py::TestClass::test_19_dcir fails intermittently on Linux

### ISSUE THREAD

**Issue by isaacansys** [ansys/pyaedt#2863]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The test _unittest/test_40_3dlayout_edb.py::TestClass::test_19_dcir is failing intermittently on Linux

### Steps To Reproduce

1. Install pyaedt.[tests] and set up environment to run with Ansys EM 2023 R1
2. Run the test:
   ```pytest -v _unittest/test_40_3dlayout_edb.py::TestClass::test_19_dcir```
3. Repeat step 2 several times and note that the test sometimes passes and sometimes fails

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.10

### Installed packages

asttokens==2.2.1
attrs==22.2.0
backcall==0.2.0
certifi==2022.12.7
cffi==1.15.0
charset-normalizer==3.1.0
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.5
codecov==2.1.12
contourpy==1.0.7
coverage==7.2.2
cycler==0.11.0
decorator==5.1.1
distro==1.8.0
dotnetcore2==3.1.23
et-xmlfile==1.1.0
exceptiongroup==1.1.1
execnet==1.9.0
executing==1.2.0
Fiona==1.9.2
fonttools==4.39.2
geopandas==0.12.2
idna==3.4
imageio==2.26.1
iniconfig==2.0.0
ipython==8.8.0
jedi==0.18.2
joblib==1.2.0
kiwisolver==1.4.4
matplotlib==3.7.1
matplotlib-inline==0.1.6
munch==2.5.0
networkx==3.0
numpy==1.24.1
openpyxl==3.0.10
osmnx==1.3.0
packaging==23.0
pandas==1.5.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.1.1
pluggy==1.0.0
plumbum==1.8.1
pooch==1.7.0
prompt-toolkit==3.0.38
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyaedt @ file:///home/staff/iwaldron/build/pyaedt
pycparser==2.21
Pygments==2.14.0
pyparsing==3.0.9
pyproj==3.4.1
pytest==7.2.2
pytest-cov==4.0.0
pytest-xdist==3.2.0
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2022.7.1
pyvista==0.37.0
requests==2.28.2
rpyc==5.3.0
scikit-learn==1.2.0
scikit-rf==0.25.0
scipy==1.10.1
scooby==0.7.1
shapely==2.0.1
six==1.16.0
SRTM.py==0.3.7
stack-data==0.6.2
threadpoolctl==3.1.0
tomli==2.0.1
traitlets==5.9.0
urllib3==1.26.15
utm==0.7.0
vtk==9.2.6
wcwidth==0.2.6

**Comment by Samuelopez-ansys** [comment]
@maxcapodi78 @svandenb-dev I think this unitttest is not failing anymore right?
