### ISSUE TITLE
Documentation for lumped_port

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/pyaedt#2904]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

![image](https://user-images.githubusercontent.com/87315832/233968555-ae20dfaa-9b63-4bcf-b9bb-bf5994d25212.png)

The syntax of the documentation for the parameters named `signal` and `reference` is not correct.

### Steps To Reproduce

N/A

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

N/A

**Comment by maxcapodi78** [comment]
@MaxJPRey  what is incorrect in this syntax?

**Comment by MaxJPRey** [comment]
@maxcapodi78 No major issue. I just fixed it.
