### ISSUE TITLE
HFSS3DLayout: PCB and EDB in 3D Layout Example Error

### ISSUE THREAD

**Issue by nico-zhu** [ansys/pyaedt#2915]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The HFSS3DLayout: PCB and EDB in 3D Layout example currently on the website seems to give an error using edb.nets.plot():
Show only two nets

Show only two specified nets.

h3d.modeler.change_net_visibility(["A0_GPIO", "A0_MUX"], visible=True)

edb = h3d.modeler.edb

edb.nets.plot(["A0_GPIO", "A0_MUX"])

pyaedt INFO: Logger is initialized in EDB.
pyaedt INFO: pyaedt v0.6.61
pyaedt INFO: Python version 3.7.13 (remotes/origin/bdighole/python/3713/clean_up-dirty:d4e1bece, Apr  6 2022, 00:24:) [MSC v.1920 64 bit (AMD64)]
pyaedt INFO: EDB Path C:/Users/AppData/Local/Temp/8/Example_CNGGK0/edb_demo.aedb
pyaedt INFO: EDB Version 2022.2
pyaedt INFO: EDB Standalone True
pyaedt INFO: Database Opened
pyaedt INFO: Cell Galileo_um Opened
pyaedt INFO: Refreshing the Components dictionary.
pyaedt INFO: Objects Initialized
pyaedt INFO: Builder was initialized.
pyaedt INFO: EDB was initialized.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\8\ipykernel_57580\601141570.py in <module>
      1 h3d.modeler.change_net_visibility(["A0_GPIO", "A0_MUX"], visible=True)
      2 edb = h3d.modeler.edb
----> 3 edb.nets.plot(["A0_GPIO", "A0_MUX"])

AttributeError: 'Edb' object has no attribute 'nets'

### Steps To Reproduce

Run the HFSS3DLayout example provided at: https://aedt.docs.pyansys.com/version/stable/examples/01-HFSS3DLayout/EDB_in_3DLayout.html#sphx-glr-examples-01-hfss3dlayout-edb-in-3dlayout-py. 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

aiofiles==22.1.0
aiosqlite==0.18.0
alabaster==0.7.12
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
atomicwrites==1.4.0
attrs==22.2.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.1
bleach==6.0.0
cached-property==1.5.2
certifi==2022.12.7
cffi==1.15.1
chardet==3.0.4
charset-normalizer==3.1.0
clr-loader==0.2.5
colorama==0.4.6
cycler==0.11.0
Cython==0.29.28
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
docutils==0.17.1
entrypoints==0.4
execnet==1.9.0
fastjsonschema==2.16.3
fonttools==4.38.0
fqdn==1.5.1
future==0.16.0
grpcio==1.26.0
hypothesis==6.41.0
idna==3.4
imageio==2.27.0
imagesize==1.3.0
importlib-metadata==6.1.0
importlib-resources==5.12.0
iniconfig==1.1.1
ipycanvas==0.13.1
ipyevents==2.0.1
ipykernel==6.16.2
ipython==7.34.0
ipython-genutils==0.2.0
ipyvtklink==0.2.3
ipywidgets==7.7.5
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter-server==1.23.6
jupyter-ydoc==0.2.3
jupyter_client==7.4.9
jupyter_core==4.12.0
jupyter_server_fileid==0.8.0
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.4
jupyterlab_server==2.22.0
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.5.3
matplotlib-inline==0.1.6
mistune==2.0.5
nbclassic==0.5.5
nbclient==0.7.3
nbconvert==7.3.0
nbformat==5.8.0
nest-asyncio==1.5.6
notebook==6.5.4
notebook_shim==0.2.2
numpy==1.21.6
packaging==23.0
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.5.0
pkgutil_resolve_name==1.3.10
platformdirs==3.2.0
pluggy==1.0.0
plumbum==1.8.1
pooch==1.7.0
prometheus-client==0.16.0
prompt-toolkit==3.0.38
protobuf==3.18.1
psutil==5.9.4
py==1.11.0
pyaedt==0.6.61
pybind11==2.9.2
pycparser==2.21
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.1.1
pytest-forked==1.4.0
pytest-xdist==2.5.0
python-certifi-win32==1.6
python-dateutil==2.8.2
python-json-logger==2.0.7
pythonnet==3.0.1
pytz==2023.3
pyvista==0.38.5
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.2
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpyc==5.3.0
scipy==1.7.0
SCons==4.0.1
scooby==0.7.1
Send2Trash==1.8.0
setuptools-scm==6.4.2
sip==6.5.1
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.4
Sphinx==4.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
terminado==0.17.1
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tornado==6.2
traitlets==5.9.0
typing_extensions==4.5.0
uri-template==1.2.0
urllib3==1.26.15
vtk==9.2.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.1
widgetsnbextension==3.6.4
wrapt==1.14.0
y-py==0.5.9
ypy-websocket==0.8.2
zipp==3.15.0

**Comment by svandenb-dev** [comment]
HI @nico-zhu ,
I am not sure to understand the issue. 
Hfss3D layout and Edb and 2 different api.
Ploting Edb is available in C python not ironpython. and Also has been design to plot nets when edb is loaded out of Aedt not inside like you are doing.
edb = Edb(edb_file)
edb.nets.plot() will show the entire board in a Matplotlib object.
