### ISSUE TITLE
Improve create_polygon_from_points() to allow ArcHeights

### ISSUE THREAD

**Issue by s-benter** [ansys/pyaedt#2916]
### Description of the current limitations

edb_core.modeler.get_polygon_points() returns a list of points.  Line endpoints are represented by two-value tuples for (x,y).  Arcs are represented by single-value tuples for ArcHeight.

edb.modeler.create_polygon_from_points() can only accept (x,y) pairs and throws an IndexError if ArcHeights are included included in the points list. 
 
for example:
```
 point_list = [[0 ,90], [0 ,10], [-2.9289321881345], [10 ,0], [90 ,0], [-2.9289321881345], [100 ,10], [100 ,90], [-2.9289321881345], [90 ,100], [10 ,100], [-2.9289321881345]]
 edb.modeler.create_polygon_from_points(point_list, "Layer") 
```

should return a polygon primitive of a 100mm square with rounded corners.

**Comment by maxcapodi78** [comment]
@s-benter I've added the support for the height now. You have to pass a tuple of 3 values [xend, yend, height]. The Arc height will be created between previous point and [xend,yend] and height will be the Arc Height.
