### ISSUE TITLE
Bug located in create_polygon()

### ISSUE THREAD

**Issue by housamomar** [ansys/pyaedt#2976]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Current create_polygon() method does not support the use global and local variable on the same time as input parameters to polygon create method. 

Error:
"ArcData does not support parameterization"

FYI: @hui

### Steps To Reproduce

    def create_signal_from_polygon(self, polygonStruct, gndLayerObjs):
        planes=[]

        for polygon in polygonStruct:

            points = polygon['points']
            layer = polygon['layer']
            netName = polygon['net_name']

            shape = self.edb.modeler.Shape("polygon", points=points)
            planes.append(shape)

            """
            self.edb.modeler.create_polygon_from_points(point_list = points, 
                                                        layer_name = layer, 
                                                        net_name = netName)
            """
            self.edb.modeler.create_polygon(main_shape = shape,
                                            layer_name = layer,
                                            net_name = netName)
            
            if not(polygon['void_points'] == []):
                vPoints = polygon['void_points']
                void_shape = self.edb.modeler.Shape("polygon", points=vPoints)
                vplane = self.edb.modeler.create_polygon(main_shape = void_shape,
                                                         layer_name = layer,
                                                         net_name = 'GND')
                gndLayerObjs[layer].add_void(vplane)

gnd_layers = myEDB.core_primitives.create_rectangle(
        layer_name = "TOP",
        net_name = "GND",
        center_point=["0", "0"],
        lower_left_point=['-xModelSize/2', '-yModelSizePt1'],
        upper_right_point=['xModelSize/2', 'yModelSizePt2'],
        representation_type="LowerLeftUpperRight",
    )

taperList=[]

taperList.append({
    'points': [[('$xRef - topTuneWidth/2'),    ('$yRef + topTuneLength')],
               [('$xRef - midTuneWidth_1/2'),  ('$yRef + topTuneLength + taper1Length')],
               [('$xRef + midTuneWidth_1/2'),  ('$yRef + topTuneLength + taper1Length')],
               [('$xRef + topTuneWidth/2'),    ('$yRef + topTuneLength')],
               ],
    'layer': "TOP",
    'net_name': 'sig',
    'void_points': [[('$xRef - topTuneWidth/2   - $lineSpace'),  ('$yRef + topTuneLength')],
                    [('$xRef - midTuneWidth_1/2 - $lineSpace'),  ('$yRef + topTuneLength + taper1Length')],
                    [('$xRef + midTuneWidth_1/2 + $lineSpace'),  ('$yRef + topTuneLength + taper1Length')],
                    [('$xRef + topTuneWidth/2   + $lineSpace'),  ('$yRef + topTuneLength')],
                    ],
})

edb_wrapper.create_signal_from_polygon(taperList,gnd_layers)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
clr-loader==0.2.5
contourpy==1.0.7
cycler==0.11.0
fonttools==4.39.3
idna==3.4
imageio==2.27.0
joblib==1.2.0
kiwisolver==1.4.4
matplotlib==3.7.1
numpy==1.24.2
packaging==23.1
pandas==1.5.3
Pillow==9.5.0
platformdirs==3.2.0
plumbum==1.8.1
pooch==1.7.0
psutil==5.9.4
pyaedt==0.6.71
pycparser==2.21
pyparsing==3.0.9
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2022.7.1
pyvista==0.38.5
pywin32==306
requests==2.28.2
rpyc==5.3.0
scikit-learn==1.2.2
scikit-rf==0.24.1
scipy==1.10.0
scooby==0.7.1
six==1.16.0
threadpoolctl==3.1.0
urllib3==1.26.15
vtk==9.2.6

**Comment by ring630** [comment]
@svandenb-dev @Samuelopez-ansys I am looking at this issue now

**Comment by ring630** [comment]
Workaround solution. 
1, create polygon with same number of points of the target polygon.
2, set variables to polygon points after polygon creation. 
`
import pyaedt


myEDB = pyaedt.Edb(edbversion="2023.1")
myEDB.stackup.create_symmetric_stackup(2)
myEDB["$xRef"] = 0
myEDB["$yRef"] = 0
myEDB["topTuneWidth"] = 1
myEDB["midTuneWidth_1"] = 1
myEDB["taper1Length"] = 0.1
myEDB["topTuneLength"] = 0.1


points = [[('$xRef - topTuneWidth/2'), ('$yRef + topTuneLength')],
           [('$xRef - midTuneWidth_1/2'), ('$yRef + topTuneLength + taper1Length')],
           [('$xRef + midTuneWidth_1/2'), ('$yRef + topTuneLength + taper1Length')],
           [('$xRef + topTuneWidth/2'), ('$yRef + topTuneLength')],
           ]



layer = "TOP"
net_name = "sig"

_points = [(0, 0) for i in points]
polygon = myEDB.modeler.create_polygon(main_shape=_points, layer_name=layer, net_name=net_name)
primitive_object = polygon.primitive_object
polygon_data = primitive_object.GetPolygonData()
for idx, i in enumerate(points):
    pdata_0 = myEDB.edb_value(i[0])
    pdata_1 = myEDB.edb_value(i[1])
    new_points = myEDB.edb.Geometry.PointData(pdata_0, pdata_1)
    polygon_data.SetPoint(idx, new_points)
    primitive_object.SetPolygonData(polygon_data)

myEDB.save_edb()
myEDB.close_edb()
`
![image](https://github.com/ansys/pyaedt/assets/27995305/27af3c7a-57a3-4e56-8ca1-acae2ba57f56)

**Comment by ring630** [comment]
@housamomar fixed. after merging you should be able to pass variables

```
import pyaedt


myEDB = pyaedt.Edb(edbversion="2023.1")
myEDB.stackup.create_symmetric_stackup(2)
myEDB["$xRef"] = 0
myEDB["$yRef"] = 0
myEDB["topTuneWidth"] = 1
myEDB["midTuneWidth_1"] = 1
myEDB["taper1Length"] = 0.1
myEDB["topTuneLength"] = 0.1


points = [[('$xRef - topTuneWidth/2'), ('$yRef + topTuneLength')],
           [('$xRef - midTuneWidth_1/2'), ('$yRef + topTuneLength + taper1Length')],
           [('$xRef + midTuneWidth_1/2'), ('$yRef + topTuneLength + taper1Length')],
           [('$xRef + topTuneWidth/2'), ('$yRef + topTuneLength')],
           ]

layer = "TOP"
net_name = "sig"

polygon = myEDB.modeler.create_polygon(main_shape=points, layer_name=layer, net_name=net_name)

myEDB.close_edb()
```
