### ISSUE TITLE
Bug located in get_messages

### ISSUE THREAD

**Issue by nnetake** [ansys/pyaedt#3007]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

this method does not write output for the 3D component design opened for editing

### Steps To Reproduce

Open the project -> Create Icepak design -> Add any 3D component in the model -> open 3d component in the edit mode and try the below code. It does not give the messages that are there in the design of 3D component. But the original iron python command reports the messages. 

import os
import pyaedt
from pyaedt import icepak, modeler, Desktop
pyaedt_icepak = pyaedt.Icepak()
pyaedt_icepak.logger.add_message(0,"3Dcomp This is information message")
pyaedt_icepak.logger.add_message(1,"3Dcomp This is warning message")
pyaedt_icepak.logger.add_message(2,"3Dcomp This is error message")

pyaedt_icepak.logger.get_messages(project_name=pyaedt_icepak.project_name, design_name=pyaedt_icepak.design_name, level=0, aedt_messages=False).design_level

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

-e git+https://github.com/pyansys/pyaedt-icepak-rest-api@7d04417e46bd919ef1f9acf82de18c201d76f156#egg=ansys_aedt_wrappers_restapi
attrs==23.1.0
bottle==0.12.25
build==0.10.0
certifi==2022.12.7
cffi==1.15.1
cfgv==3.3.1
charset-normalizer==3.1.0
clr-loader==0.2.5
colorama==0.4.6
contourpy==1.0.7
coverage==7.2.3
cycler==0.11.0
distlib==0.3.6
exceptiongroup==1.1.1
filelock==3.12.0
flake8==6.0.0
fonttools==4.39.3
identify==2.5.24
idna==3.4
imageio==2.28.0
importlib-metadata==6.6.0
importlib-resources==5.12.0
iniconfig==2.0.0
kiwisolver==1.4.4
matplotlib==3.7.1
mccabe==0.7.0
nodeenv==1.7.0
numpy==1.24.3
packaging==23.1
Pillow==9.5.0
platformdirs==3.4.0
pluggy==1.0.0
plumbum==1.8.1
pooch==1.7.0
pre-commit==3.3.1
psutil==5.9.5
py==1.11.0
pyaedt==0.6.61
pycodestyle==2.10.0
pycparser==2.21
pyflakes==3.0.1
pyparsing==3.0.9
pyproject_hooks==1.0.0
pytest==7.2.2
pytest-cov==4.0.0
pytest-html==3.2.0
pytest-metadata==2.0.4
pytest-timeout==2.1.0
pytest-xprocess==0.22.2
python-dateutil==2.8.2
pythonnet==3.0.1
pyvista==0.38.5
pywin32==306
PyYAML==6.0
requests==2.29.0
rpyc==5.3.0
scooby==0.7.1
six==1.16.0
tomli==2.0.1
urllib3==1.26.15
virtualenv==20.23.0
vtk==9.2.6
waitress==2.1.2
zipp==3.15.0

**Comment by lorenzovecchietti** [comment]
Fixed in PR 3016
