### ISSUE TITLE
Bug located when running PyAEDT with gRPC on WSL

### ISSUE THREAD

**Issue by ansGEsquembri** [ansys/pyaedt#3036]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When running `/opt/AnsysEM/v222/Linux64/ansysedt -grpcsrv PORT_NUMBER` on `Ubuntu 20.04` running on `WSL 2`, AEDT restarts and crashes after a few minutes without doing anything with it.

`gRPC` server status shown on AEDT messages list is ok.

If `AEDT` is run without `grpcsrv` flag it works fine.

### Steps To Reproduce

Run `/opt/AnsysEM/v222/Linux64/ansysedt -grpcsrv PORT_NUMBER` on `Ubuntu 20.04` on `WSL 2`.

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.8

### Installed packages

aiofiles==23.1.0
ansys-api-platform-instancemanagement==1.0.0b3
ansys-dash-treeview==0.0.1.dev0
ansys-platform-instancemanagement==1.1.1
-e git+https://github.com/Solution-Applications/glow.git@df3589a2d1128f7d0a45fccccd38fe3c5e0eca60#egg=ansys_saf_glow
ansys-saf-pim-light-server==0.1.9
ansys-saf-portal==0.1.6
-e git+https://github.com/Solution-Applications/saf-end-to-end-testing.git@c1409ffb773fa6c8f6460d558db3a31b4f088001#egg=ansys_solutions_saf_end_to_end_solution
ansys-templates==0.7.1
anyio==3.6.2
arrow==1.2.3
asgiref==3.6.0
async-generator==1.10
attrs==23.1.0
backoff==2.2.1
beautifulsoup4==4.12.2
binaryornot==0.4.4
boto3==1.26.52
botocore==1.29.115
bottle==0.12.25
Brotli==1.0.9
CacheControl==0.12.11
cachelib==0.10.2
cachetools==5.3.0
cef==0.5
certifi==2022.12.7
cffi==1.15.0
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.1.0
cleo==2.0.1
click==7.1.2
clr-loader==0.2.5
colorama==0.4.6
cookiecutter==2.1.1
coverage==6.5.0
crashtest==0.4.1
cryptography==39.0.2
dash==2.6.1
dash-bootstrap-components==1.4.1
dash-core-components==2.0.0
dash-extensions==0.1.3
dash-html-components==2.0.0
dash-iconify==0.1.2
dash-table==5.0.0
dash-uploader==0.6.0
debugpy==1.6.7
Deprecated==1.2.13
distlib==0.3.6
distro==1.8.0
dotnetcore2==3.1.23
dulwich==0.20.50
EditorConfig==0.12.3
exceptiongroup==1.1.1
execnet==1.9.0
fastapi==0.95.1
filelock==3.12.0
Flask==2.0.3
Flask-Caching==1.11.1
Flask-Compress==1.13
googleapis-common-protos==1.59.0
grpcio==1.47.0
grpcio-health-checking==1.24.0
h11==0.14.0
html5lib==1.1
httpcore==0.16.3
httpx==0.23.3
identify==2.5.22
idna==3.4
importlib-metadata==6.0.1
importlib-resources==5.12.0
iniconfig==2.0.0
isort==5.12.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
jeepney==0.8.0
Jinja2==3.1.2
jinja2-time==0.2.0
jmespath==1.0.1
jsbeautifier==1.14.7
jsonschema==4.17.3
keyring==23.13.1
lockfile==0.12.2
lxml==4.9.2
MarkupSafe==2.1.2
mock==4.0.3
more-itertools==8.14.0
msgpack==1.0.5
networkx==3.1
nodeenv==1.7.0
opentelemetry-api==1.17.0
opentelemetry-exporter-otlp==1.17.0
opentelemetry-exporter-otlp-proto-grpc==1.17.0
opentelemetry-exporter-otlp-proto-http==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-asgi==0.38b0
opentelemetry-instrumentation-fastapi==0.38b0
opentelemetry-instrumentation-flask==0.38b0
opentelemetry-instrumentation-httpx==0.38b0
opentelemetry-instrumentation-logging==0.38b0
opentelemetry-instrumentation-wsgi==0.38b0
opentelemetry-proto==1.17.0
opentelemetry-sdk==1.17.0
opentelemetry-semantic-conventions==0.38b0
opentelemetry-util-http==0.38b0
outcome==1.2.0
packaging==23.1
percy==2.0.2
pexpect==4.8.0
pkg_resources==0.0.0
pkginfo==1.9.6
pkgutil_resolve_name==1.3.10
platformdirs==3.2.0
plotly==5.14.1
pluggy==1.0.0
plumbum==1.8.1
poetry==1.3.2
poetry-core==1.4.0
poetry-plugin-export==1.3.1
pre-commit==3.2.2
protobuf==3.20.3
protoc-gen-swagger==0.1.0
proxy-tools==0.1.0
psutil==5.9.5
ptyprocess==0.7.0
py==1.11.0
pyaedt==0.6.71
pycairo==1.23.0
pycparser==2.21
pydantic==1.10.7
PyGObject==3.44.1
pyOpenSSL==23.1.1
pyproject_api==1.5.1
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.1
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
pyright==1.1.303
pyrsistent==0.19.3
pyshortcuts==1.8.3
PySide2==5.15.2.1
PySide6==6.5.0
PySide6-Addons==6.5.0
PySide6-Essentials==6.5.0
PySocks==1.7.1
pytest==7.3.1
pytest-cov==3.0.0
pytest-dependency==0.5.1
pytest-html==3.2.0
pytest-md==0.2.0
pytest-metadata==2.0.4
pytest-order==1.1.0
pytest-pythonpath==0.7.3
pytest-xdist==3.2.1
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
python-slugify==8.0.1
pythonnet==3.0.1
pywebview==4.0.2
PyYAML==6.0
QtPy==2.3.1
rapidfuzz==2.15.1
requests==2.28.2
requests-toolbelt==0.10.1
rfc3986==1.5.0
rpyc==5.3.0
s3transfer==0.6.0
SecretStorage==3.3.3
selenium==4.2.0
shellingham==1.5.0.post1
shiboken2==5.15.2.1
shiboken6==6.5.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
starlette==0.26.1
tenacity==8.2.2
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.8
tox==4.4.12
trio==0.22.0
trio-websocket==0.10.2
trove-classifiers==2023.5.2
typing_extensions==4.5.0
urllib3==1.26.15
urllib3-secure-extra==0.1.0
uvicorn==0.21.1
virtualenv==20.21.0
waitress==2.1.2
webencodings==0.5.1
Werkzeug==2.2.3
wrapt==1.15.0
wsproto==1.2.0
zipp==3.15.0

**Comment by Samuelopez-ansys** [comment]
This is an issue in AEDT product, it is not related to PyAEDT. Ansys development team is aware.
