### ISSUE TITLE
How to arbitrarily create a circuit port in Hfss3DLayout? Does the current pyaedt have this feature?

### ISSUE THREAD

**Issue by xym180** [ansys/pyaedt#3064]
### Description of the feature

CreateCircuitPort(PosLayer=,  X0=,Y0=,NegLayer=,X1=,Y1=)

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev Do you know if it is possible? I have only found between nets.

**Comment by svandenb-dev** [comment]
Hi @xym180,
you have everything available in EDB for port creation pin groups...
