### ISSUE TITLE
Question about dynamic ROM evaluation and build setting

### ISSUE THREAD

**Issue by PengkunLiu** [ansys/pyaedt#3082]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

（1）How to show the training precision during the dynamic ROM creation?
（2） How to evaluate the dynamic ROM on a defined dataset? It seems the API exists in the library, but I do not find the illustration on the GitHub page. I try to use the evaluate command, but the log shows unable to evaluate the ROM Component.
(3) Are there any references for command in the dynarom_build.conf, such as how to add the reduce method and order, evaluation trajectory ids?   I try to add some settings in the dynarom_build.conf, the following picture is I modified as per my understanding.
 
  

### Steps To Reproduce

![image](https://github.com/ansys/pyaedt/assets/64773425/7ad99ef3-ff95-4466-a4e1-01650a52ea0c)
![image](https://github.com/ansys/pyaedt/assets/64773425/c6770317-22fa-4800-8998-5db080cf307e)
![image](https://github.com/ansys/pyaedt/assets/64773425/05567dfc-afa7-42e4-94c9-e212cac81129)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

anyio==3.7.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==23.1.0
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
clr-loader==0.2.5
colorama==0.4.6
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.1.1
executing==1.2.0
fastjsonschema==2.17.1
fonttools==4.39.4
fqdn==1.5.1
idna==3.4
importlib-metadata==6.6.0
importlib-resources==5.12.0
ipykernel==6.23.1
ipython==8.13.2
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mistune==2.0.5
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.4.0
nbformat==5.8.0
nest-asyncio==1.5.6
notebook==6.5.4
notebook_shim==0.2.3
numpy==1.24.3
overrides==7.3.1
packaging==23.1
pandas==2.0.2
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.1
plumbum==1.8.2
pooch==1.7.0
prometheus-client==0.17.0
prompt-toolkit==3.0.38
psutil==5.9.5
pure-eval==0.2.2
pyaedt==0.6.78
pycparser==2.21
Pygments==2.15.1
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.7
pythonnet==3.0.1
pytz==2023.3
pyvista==0.39.1
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpyc==5.3.1
scooby==0.7.2
seaborn==0.12.2
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
terminado==0.17.1
tinycss2==1.2.1
tornado==6.3.2
traitlets==5.9.0
typing_extensions==4.6.2
tzdata==2023.3
uri-template==1.2.0
urllib3==2.0.2
vtk==9.2.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.2
widgetsnbextension==4.0.7
zipp==3.15.0

**Comment by Samuelopez-ansys** [comment]
@SushobhitGupt Could you help with this issue? 

Thanks
