### ISSUE TITLE
Add ability to get extents properties in HFSS 3d layout

### ISSUE THREAD

**Issue by skandak-ansys** [ansys/pyaedt#3094]
### Description of the feature

Currently there is API command to edit hfss 3d layout extents in the form of `Hfss3dLayout.edit_hfss_extents`. However, there are no API commands to **get** these values. It will be a useful feature.

**Comment by ring630** [comment]
@skandak-ansys , this is limited by AEDT scripting. 

if edb works for you, you can find all hfss extent parameters under edb.hfss.hfss_extent_info

![image](https://github.com/ansys/pyaedt/assets/27995305/6080cdfd-5d87-49c1-929c-d8f972f3a925)
