### ISSUE TITLE
Add ...Edit_Dataset in HFSS

### ISSUE THREAD

**Issue by arobinson905** [ansys/pyaedt#3100]
### Description of the feature

I need a function like oDesign.EditDataset in IronPython to edit a pre-existing dataset in HFSS.

**Comment by Samuelopez-ansys** [comment]
Hi @arobinson905 ,

Edit Dataset is already wrapped in pyaedt, but it is hidden in the dataset object. Every time to update the dataset object, the method EditDataset is called.


```
x = [1, 100]
y = [1000, 980]
ds1 = self.aedtapp.create_dataset1d_design("Test_DataSet", x, y)

ds1.add_point(10, 999)

# or

ds1.x = [1, 500]
ds1.update()

```

Both commands are using EditDataset. I will close this issue, please add a comment if you need anything else.
