### ISSUE TITLE
Please add oModule.EditRadiatedPowerCalculationMethod()

### ISSUE THREAD

**Issue by cmesibov** [ansys/pyaedt#3104]
### Description of the feature

Please add oModule.EditRadiatedPowerCalculationMethod().
The options would be "Auto", "Radiation Surface Integral" and "Far Field Integral"

### Steps for implementing the feature

oModule = oDesign.GetModule("RadField")
oModule.EditRadiatedPowerCalculationMethod("Far Field Integral") #or whatever

**Comment by maxcapodi78** [comment]
ADDED
