### ISSUE TITLE
Add Field Calculator feature

### ISSUE THREAD

**Issue by pvinod13** [ansys/pyaedt#3170]
### Description of the feature

Field calculator an important function in Electronic Desktop.

### Useful links and references

Section 19, in Ansys Scripting Guide.

**Comment by Samuelopez-ansys** [comment]
Hi @pvinod13 ,

You have access to all Fields Calculator API using:
app.ofieldsreporter

For instance:
m3d.post.ofieldsreporter.EnterScalarFunc("X")
