### ISSUE TITLE
In EDB: Cloning a polygons with holes or voids results in holes or voids being dropped

### ISSUE THREAD

**Issue by xelasch** [ansys/pyaedt#3171]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Suppose you have an EDB polygon X, which has a hole XH.
If you invoke "X.clone()" you would expect to obtain an EDB file containing two polygons X and Y (with Y being the clone of X), both of which have a hole.
However, it appears that polygon Y does not have holes.

### Steps To Reproduce

import pyaedt
from pyaedt import Edb, Hfss3dLayout

edb = Edb("_foo.edb")

edb.stackup.add_layer(layer_name="foo")

x = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0] ])
x_hole = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [1.0, 1.0], [9.0, 1.0], [9.0, 9.0], [1.0, 9.0] ])

y = x.subtract(x_hole)[0]

print("N_arcs = ", len(y.arcs))
print("N_voids = ", len(y.voids))

y.clone()

edb.save_edb()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

pyaedt==0.6.78

**Comment by svandenb-dev** [comment]
@xelasch bug was fixed
![image](https://github.com/ansys/pyaedt/assets/74993647/2390c781-00c8-4f9f-9cee-975c4cd85ef7)
