### ISSUE TITLE
EDB primitive intersect() gives wrong result if intersection results in two separate polygons

### ISSUE THREAD

**Issue by xelasch** [ansys/pyaedt#3172]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Suppose an EDB with a primitive X (with a convex outer shape) with a convex hole XH. Further, suppose a second polygon Y intersects X, such that the boolean intersection results in two separate objects.

Then apply X.intersect(Y). The operation only yields the first intersection polygon and discards the second.

See related problem: https://github.com/ansys/pyaedt/issues/3155

### Steps To Reproduce

import pyaedt
from pyaedt import Edb, Hfss3dLayout

edb = Edb("_foo.edb")

edb.stackup.add_layer(layer_name="foo")

x = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0] ])
x_hole = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [1.0, 1.0], [9.0, 1.0], [9.0, 9.0], [1.0, 9.0] ])
y = x.subtract(x_hole)[0]

x2 = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0] ])
x2_hole = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [1.0, 1.0], [9.0, 1.0], [9.0, 9.0], [1.0, 9.0] ])
y2 = x2.subtract(x2_hole)[0]

print("N_arcs = ", len(y.arcs))
print("N_voids = ", len(y.voids))

z = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [-15.0, 5.0], [15.0, 5.0], [15.0, 6.0], [-15.0, 6.0] ])
z2 = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [-15.0, 5.0], [15.0, 5.0], [15.0, 6.0], [-15.0, 6.0] ])

y.intersect(z)

edb.save_edb()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

pyaedt==0.6.78

**Comment by svandenb-dev** [comment]
@xelasch the bug has been fixed
