### ISSUE TITLE
Setter of property layer_name in edb_core/edb_data/primitives_data.py crashes

### ISSUE THREAD

**Issue by xelasch** [ansys/pyaedt#3174]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

If you change the attribute "layer_name" of an EDB primitive, then it crashes.

I recommend to unit-test all routines in pyaedt, so that 100% code coverage is achieved by unit-tests. My personal recommendation: Use suitable code coverage analysis tool.

### Steps To Reproduce

import pyaedt
from pyaedt import Edb, Hfss3dLayout

edb = Edb("_foo.edb")

edb.stackup.add_layer(layer_name="foo")
edb.stackup.add_layer(layer_name="bar")

x = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0] ])
print(x.layer_name)
x.layer_name = "bar"  # Here, it crashes
print(x.layer_name)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

pyaedt==0.6.78

**Comment by svandenb-dev** [comment]
Hi @xelasch I will check. We do codeverage and unit test as much as we can. All Pull request must at least have 85% of code coverage to be merged. That's the minimum criteria but we usually do more.
Thanks
