### ISSUE TITLE
padstack options are limited ...

### ISSUE THREAD

**Issue by louseph** [ansys/pyaedt#3192]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Pad and antipad shape create method has limited options.
Please update and add all the available shapes for pad and antipad.

### Steps To Reproduce

edb.core_padstack.create()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiofiles==22.1.0
aiosqlite==0.18.0
altgraph==0.17.3
# Editable install with no version control (ansys-api-edb-v1==0.0.0)
-e d:\2023\pyedb\pyedb\protos
ansys-api-meshing-prime==0.1.1
# Editable install with no version control (ansys-edb==0.1)
-e d:\2023\pyedb\pyedb
ansys-meshing-prime==0.2.0
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==22.2.0
auto-py-to-exe==2.34.0
Babel==2.12.1
backcall==0.2.0
bcrypt==4.0.1
beautifulsoup4==4.11.2
bleach==6.0.0
bottle==0.12.25
bottle-websocket==0.2.9
build==0.10.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.0.1
click==8.1.3
clr-loader==0.2.5
colorama==0.4.6
comm==0.1.2
contourpy==1.0.7
cryptography==39.0.0
cx-Freeze==6.14.6
cx-Logging==3.1.0
cycler==0.11.0
dash==2.8.1
dash-access-manager==0.1.3
dash-bootstrap-components==1.3.1
dash-core-components==2.0.0
dash-daq==0.5.0
dash-html-components==2.0.0
dash-table==5.0.0
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
dnspython==2.3.0
docutils==0.19
Eel==0.16.0
exceptiongroup==1.1.0
executing==1.2.0
fastjsonschema==2.16.3
filelock==3.10.7
flake8==6.0.0
Flask==2.2.2
Flask-Login==0.6.2
flit==3.8.0
flit_core==3.8.0
fonttools==4.38.0
fpdf==1.7.2
fqdn==1.5.1
future==0.18.3
gdspy==1.6.13
gdstk==0.9.41
gevent==22.10.2
gevent-websocket==0.10.1
greenlet==2.0.2
grpcio==1.47.5
grpcio-tools==1.47.5
# Editable install with no version control (ICSetupToolkit==0.1.7)
-e d:\2023\apac_ebu_solution_sessions\ic-setup-toolkit-develop\ic-setup-toolkit-develop
identify==2.5.18
idna==3.4
imageio==2.25.0
importlib-metadata==6.0.0
iniconfig==2.0.0
ipykernel==6.21.3
ipynbname==2023.1.0.0
ipython==8.11.0
ipython-genutils==0.2.0
isoduration==20.11.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter-ydoc==0.2.4
jupyter_client==8.0.3
jupyter_core==5.2.0
jupyter_server==2.4.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.3
jupyterlab-pygments==0.2.2
jupyterlab_server==2.22.0
keyring==23.13.1
kiwisolver==1.4.4
Levenshtein==0.21.0
lief==0.12.3
loger==1.0
logger==1.4
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mccabe==0.7.0
mdurl==0.1.2
mistune==2.0.5
mongoengine==0.26.0
more-itertools==9.1.0
nbclassic==0.5.3
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
nodeenv==1.7.0
notebook==6.5.3
notebook_shim==0.2.2
numpy==1.24.1
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
paramiko==3.0.0
parso==0.8.3
pefile==2023.2.7
pickleshare==0.7.5
Pillow==9.4.0
pkginfo==1.9.6
platformdirs==3.2.0
plotly==5.13.0
pluggy==1.0.0
plumbum==1.8.1
pooch==1.6.0
pre-commit==3.1.1
prometheus-client==0.16.0
prompt-toolkit==3.0.38
protobuf==3.20.3
psutil==5.9.4
pure-eval==0.2.2
pyaedt==0.6.80
pycodestyle==2.10.0
pycparser==2.21
pyDOE==0.3.8
pyflakes==3.0.1
Pygments==2.14.0
pyinstaller==5.10.1
pyinstaller-hooks-contrib==2023.2
pymongo==4.3.3
PyNaCl==1.5.0
pyparsing==3.0.9
pyproject_api==1.5.1
pyproject_hooks==1.0.0
PyQt5==5.15.8
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
pyrsistent==0.19.3
PySide2==5.15.2.1
PySide6==6.5.0
PySide6-Addons==6.5.0
PySide6-Essentials==6.5.0
pytest==7.2.2
pytest-qt==4.2.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pythonnet==3.0.1
pytz==2022.7.1
pyvista==0.37.0
pywin32==305
pywin32-ctypes==0.2.0
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.0
rapidfuzz==3.0.0
readme-renderer==37.3
requests==2.28.2
requests-toolbelt==0.10.1
rfc3339-validator==0.1.4
rfc3986==2.0.0
rfc3986-validator==0.1.1
rich==13.3.3
rpyc==5.3.1
scipy==1.10.1
scooby==0.7.1
Send2Trash==1.8.0
shiboken2==5.15.2.1
shiboken6==6.5.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.4
stack-data==0.6.2
tenacity==8.2.0
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tomli_w==1.0.0
tornado==6.2
tox==4.4.8
traitlets==5.9.0
twine==4.0.2
uri-template==1.2.0
urllib3==1.26.14
virtualenv==20.21.0
vtk==9.2.5
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.2
whichcraft==0.6.1
XlsxWriter==3.1.0
y-py==0.5.9
ypy-websocket==0.8.2
zipp==3.15.0
zope.event==4.6
zope.interface==6.0

**Comment by svandenb-dev** [comment]
@louseph added rectangle shape support for antipads
