### ISSUE TITLE
Provide api to hide region object when exporting field to jpg

### ISSUE THREAD

**Issue by QY7** [ansys/pyaedt#3211]
### Description of the feature

Hello,

I've encountered an issue with the function app.post.export_field_jpg. Currently, when the function is executed, it seems to enable all visible attributes of objects, including regions.

The issue I'm facing is that because region size significantly exceeds the size of the object itself, the resulting exported image ends up highlighting these regions, thus diminishing the field content that should ideally be the focal point of the image. The desired field portion appears smaller and less emphasized than it should be.

Would it be possible to modify this function so it doesn't universally enable visibility for all objects when exporting? It would be more beneficial for my use case to have more control over what's emphasized in the exported image.

Looking forward to your assistance in resolving this issue. Thank you in advance.

**Comment by maxcapodi78** [comment]
@QY7 I've added such options in the method. now you can:
show/hide region
show/hide ruler
show/hide grid
show/hide axis
show a selections of object only
Please not I've verified that those options works in graphical only. I've submitted an enhancement request to AEDT Team

**Comment by QY7** [comment]
Thank you
