### ISSUE TITLE
Add Start/Continue from previously solved setup

### ISSUE THREAD

**Issue by Wenliang-SE** [ansys/pyaedt#3225]
### Description of the feature

"Start/Continue from previously solved setup" is available in Maxwell transient analysis setup "Advanced" tab under Import Option. 
![image](https://github.com/ansys/pyaedt/assets/111131478/dc9baa4c-81fc-475a-9974-c8fd30e6f463)
It is a very important feature for speed up induction machine steady state performance calculation. 

### Steps for implementing the feature

import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.SetActiveProject("yz200-6")
oProject.CopyDesign("Maxwell2DDesign1")
oProject.Paste()
oDesign = oProject.SetActiveDesign("Maxwell2DDesign2")
oModule = oDesign.GetModule("AnalysisSetup")
oModule.DeleteSetups(["Setup1"])
oModule.InsertSetup("Transient", 
	["NAME:Setup1","Enabled:=", True,
		["NAME:MeshLink","ImportMesh:="		, False],
		"NonlinearSolverResidual:=", "0.0001",
		"TimeIntegrationMethod:=", "BackwardEuler",
		"SmoothBHCurve:="	, False,
		**["NAME:PrevSoln","Project:=", "This Project*","Product:=", "Maxwell","Design:=", "Maxwell2DDesign1","Soln:=", "Setup1 : Transient",
			["NAME:Params","fractions:=", "fractions"],"ForceSourceToSolve:="	, True,"PreservePartnerSoln:="	, False,"PathRelativeTo:="	, "TargetProject"],
		"StopTime:="		, "10000000ns",
		"TimeStep:="		, "2000000ns",
		"OutputError:="		, False,
		"OutputPerObjectCoreLoss:=", False,
		"OutputPerObjectSolidLoss:=", False,
		"UseControlProgram:="	, False,
		"ControlProgramName:="	, "",
		"ControlProgramArg:="	, " ",
		"CallCtrlProgAfterLastStep:=", False,
		"FastReachSteadyState:=", False,
		"AutoDetectSteadyState:=", False,
		"IsGeneralTransient:="	, False,
		"IsHalfPeriodicTransient:=", False,
		"SaveFieldsType:="	, "None",
		"UseNonLinearIterNum:="	, False,
		"CacheSaveKind:="	, "Count",
		"NumberSolveSteps:="	, 1,
		"RangeStart:="		, "0s",
		"RangeEnd:="		, "0.1s",
		"UseAdaptiveTimeStep:="	, False,
		"InitialTimeStep:="	, "0.002s",
		"MinTimeStep:="		, "0.001s",
		"MaxTimeStep:="		, "0.003s",
		"TimeStepErrTolerance:=", 0.0001
	])

**Comment by IreneWoyna** [comment]
Hi @Wenliang-SE, this feature has been implemented now, and merged to main, please go ahead, test, and provide feedback :)

Thanks
Irene
