### ISSUE TITLE
Bug located in set core losses

### ISSUE THREAD

**Issue by Wenliang-SE** [ansys/pyaedt#3226]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Maxwell2D.set_core_losses not only enables the core loss setting, but mistakenly enables 'Consider core loss effect on field' by default and user cannot disable this  'Consider core loss effect on field' 
![image](https://github.com/ansys/pyaedt/assets/111131478/f4ac7c20-8dda-4a87-9238-16ebf196da69)

### Steps To Reproduce

core_loss_list = ['Rotor', 'Stator']
M2D.set_core_losses(core_loss_list, value=True)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
clr-loader==0.2.5        
cycler==0.11.0
fonttools==4.38.0
idna==3.4
imageio==2.31.1
kiwisolver==1.4.4
pythonnet==3.0.1
pyvista==0.38.6
pywin32==306
requests==2.31.0
rpyc==5.3.1
scooby==0.7.2
six==1.16.0
typing-extensions==4.7.1
urllib3==2.0.3
vtk==9.2.6

**Comment by IreneWoyna** [comment]
Core loss is enabled without  'Consider core loss effect on field' when the following command is used: 
core_loss_list = ['Rotor', 'Stator']
M2D.set_core_losses(core_loss_list, value=**False**)

I will change the documentation accordingly.
FYI @Wenliang-SE
