### ISSUE TITLE
Rename port in HFSS is missing

### ISSUE THREAD

**Issue by louseph** [ansys/pyaedt#3246]
### Description of the feature

Need a method to rename port in hfss design.

**Comment by Samuelopez-ansys** [comment]
Hi @louseph ,

In the last PyAEDT version, we have added a very nice feature, which is object oriented programming for boundaries and excitations.

For example, you can get the excitation information:

`app.design_excitations`

This will give you a list of excitation objects. You can modify the name simply:

`app.design_excitations[1].name = "hola"`

Please test it and close the issue if it works.
