### ISSUE TITLE
Exporting unnormalized Touchstone files

### ISSUE THREAD

**Issue by terdol** [ansys/pyaedt#3299]
### Description of the feature

The functions which are used to export Touchstone files (export_results or export_touchstone) do not provide an option to export unnormalized Touchstone files which can be done through the HFSS GUI. Such an option should be added to these functions.

**Comment by fwlfHS** [comment]
In addition the naming convention of solution_name is misleading. 
` solution_name : str, optional Name of the solution that has been solved.`
meant is the analysis setup name.
` # array containing "SetupName:SolutionName" pairs (note that setup and solution are separated by a colon)
        SolutionSelectionArray = [solution_name + ":" + sweep_name]`

The naming, of setup, solution, sweep should be more clear.
