### ISSUE TITLE
AEDT crashes when trying to load a project that is already open

### ISSUE THREAD

**Issue by jsalant22** [ansys/pyaedt#3309]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

1. Open an instance of AEDT and load a project.
2. Now try and load that same project via pyaedt.
3. The load_project() method gives a warning about the project being locked (good, expected behavior), but if you try to continue with other actions in the script (e.g. load a different project), then the AEDT instance started by pyaedt crashes.

### Steps To Reproduce

1. Open an instance of AEDT and load a project.
2. Now try and load that same project via pyaedt.
3. The load_project() method gives a warning about the project being locked (good, expected behavior), but if you try to continue with other actions in the script (e.g. load a different project), then the AEDT instance started by pyaedt crashes.

Sample code below and the example project is just one of the HFSS examples saved locally.

`import pyaedt
non_graphical = False
NewThread = True
desktop_version = "2023.2"
d = pyaedt.launch_desktop(desktop_version, non_graphical, NewThread)
hfss = pyaedt.Hfss(pyaedt.generate_unique_project_name())
filepath = "D:\\ARMReports\\CISPR25_Radiated_Emissions_Example.aedt" 
hfss.load_project(filepath)
hfss = pyaedt.Hfss(pyaedt.generate_unique_project_name())`

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

agi.stk12 @ file:///C:/Program%20Files/AGI/STK%2012/bin/AgPythonAPI/agi.stk12-12.6.0-py3-none-any.whl
asttokens==2.2.1
attrs==22.2.0
backcall==0.2.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.5
colorama==0.4.6
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
docutils==0.16
et-xmlfile==1.1.0
exceptiongroup==1.1.1
executing==1.2.0
Fiona==1.9.3
fonttools==4.39.0
geopandas==0.12.2
idna==3.4
imageio==2.26.0
iniconfig==2.0.0
ipykernel==6.22.0
ipython==8.13.2
ipywidgets==8.0.6
jedi==0.18.2
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
matplotlib==3.7.1
matplotlib-inline==0.1.6
munch==2.5.0
mypy==1.4.0
mypy-extensions==1.0.0
nest-asyncio==1.5.6
networkx==3.1
numpy==1.24.1
openpyxl==3.0.10
osmnx==1.3.0
packaging==23.0
pandas==1.5.3
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.1.1
plotly==5.14.1
pluggy==1.0.0
plumbum==1.8.1
pooch==1.7.0
prompt-toolkit==3.0.38
psutil==5.9.4
pure-eval==0.2.2
pyaedt==0.6.81
pybind11-stubgen==0.16.2
pycparser==2.21
pygenstub==2.0.1
Pygments==2.15.1
pyparsing==3.0.9
pyproj==3.5.0
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.1
PySide2==5.15.2.1
PySide6==6.4.2
PySide6-Addons==6.4.2
PySide6-Essentials==6.4.2
pytest==7.2.2
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2022.7.1
pyvista==0.37.0
pywin32==305
pyzmq==25.0.2
requests==2.28.2
rpyc==5.3.1
scikit-rf==0.25.0
scipy==1.10.1
scooby==0.7.1
shapely==2.0.1
shiboken2==5.15.2.1
shiboken6==6.4.2
six==1.16.0
snakeviz==2.2.0
SRTM.py==0.3.7
stack-data==0.6.2
tenacity==8.2.2
tomli==2.0.1
tornado==6.3.1
tqdm==4.65.0
traitlets==5.9.0
typing==3.7.4.3
typing_extensions==4.6.3
urllib3==1.26.15
utm==0.7.0
vtk==9.2.6
wcwidth==0.2.6
widgetsnbextension==4.0.7

**Comment by gmalinve** [comment]
Hi @jsalant22,

Have you tried to update pyaedt to latest version? There has been a big refactoring lately.
Please do let us know in case this solve the issue so we can close it.

Giulia
