### ISSUE TITLE
AEDT Optimetrics Native Iron Python APIs gives pywintypes_com_error  if called from pyaedt

### ISSUE THREAD

**Issue by tizianrot** [ansys/pyaedt#3316]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Dear All,
not sure if it is the correct place but I would raise awareness and maybe you can suggest a workaround. 
The Native Iron Python API (Exporting results from an Optimetrics Setup in a Maxwell Design):
oModule.ExportDOEResponseSurface
works well if  called from within the AEDT GUI. If called from a python IDE through pyaedt, calling the oModule object from a Maxwell 2d instance, throws a pywintypes_com_error as attached.
Thank you for any help.
![PythonError](https://github.com/ansys/pyaedt/assets/88496115/4c9da675-0fb6-4a38-a5b9-604fc095bcbd)

 

### Steps To Reproduce

- set up a Maxwell 2d design
- set up an Optimetrics DOE 
- export responce surface results to a csv file

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

-

**Comment by Samuelopez-ansys** [comment]
@tizianrot  Please could you share an end to end script to reproduce the issue?

Thanks

**Comment by gmalinve** [comment]
Closing as agreed with @tizianrot. 
Issues fixed from v2023.2 by dev.
