### ISSUE TITLE
Add design settings prop

### ISSUE THREAD

**Issue by nnetake** [ansys/pyaedt#3319]
### Description of the feature

Add API to get design settings for each type of design. This method will return the dictionary of all design settings of the requested design. 

### Steps for implementing the feature
need to figure out.

**Comment by gmalinve** [comment]
Hi @nnetake !

Please provide a complete title when opening issues :)
I'm aware you have started working on that, correct? if this is the case, could you please assign to yourself?
For any issue we are here to help! :)

Thanks,

Giulia

**Comment by nnetake** [comment]
@gmalinve  I have assigned it to my self. Sure I will write title in more descriptive way.
