### ISSUE TITLE
Improve parameter naming convention for hfss.set_impedance_multiplier()

### ISSUE THREAD

**Issue by fwlfHS** [ansys/pyaedt#3326]
### Description of the current limitations

As mentioned in #2358, the parameter given to `hfss.set_impedance_multiplier()` is the multiplier value not the impedance.

### Code sample expected

change "impedance" to "multiplier"

### Useful links and references

https://github.com/ansys/pyaedt/issues/2358

**Comment by Samuelopez-ansys** [comment]
Hi @fwlfHS ,

As mentioned in #2358 , are you going to do the implementation?

Thanks

**Comment by fwlfHS** [comment]
Hi @Samuelopez-ansys, please see PR #3328

**Comment by Samuelopez-ansys** [comment]
That's great! Thank you for your contribution 🥇
