### ISSUE TITLE
Creating padstack bug - layers not right

### ISSUE THREAD

**Issue by marycx** [ansys/pyaedt#3334]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I am using EDB API create padstacks (edb.padstack.create()). I defined the padstack layers to be 0->4. But when I place the padstack, I notice that the padstack layers are incorrectly shown in Ansys, it is layer 3->4. I want to ask why that is the case, thank you.
![image](https://github.com/ansys/pyaedt/assets/68626983/0ffa5136-6ce4-47bc-ad7e-4156480a126e)
![image](https://github.com/ansys/pyaedt/assets/68626983/70e3da3e-fb1b-4c4b-ae4e-2937d0214c15)

### Steps To Reproduce

use edb.padstacks.create

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

-

**Comment by ring630** [comment]
@marycx, I cannot reproduce the problem you have. Below is my test code. Please let me know if you can reproduce it on your side.

> 
> edb = Edb(edbversion="2023.2")
> 
> edb.stackup.create_symmetric_stackup(6)
> edb.padstacks.create(padstackname="micro_via",
>                      holediam="0.09mm",
>                      antipaddiam="0.15mm",
>                      paddiam="0.1mm",
>                      start_layer="TOP",
>                      stop_layer="L4")
> 
> edb.padstacks.place(position=(0,0),
>                     definition_name="micro_via",
>                     fromlayer="TOP",
>                     tolayer="L4")
> 
> edb.save_edb_as("D:to_delete/test.aedb")
> edb.close()
>

**Comment by marycx** [comment]
Hi, thanks for your help. I have resolved this issue.
