### ISSUE TITLE
Issue with importing layout design (edb.import_layout_pcb) when folder name has spaces in naming

### ISSUE THREAD

**Issue by Garpurinn** [ansys/pyaedt#3368]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

In version 0.6.75 I started to get failure on the edb.import_layout_pcb function, when importing my IPC2581 layout file. 

I believe I have isolated the issue to the the lines 662-665 in the edb.py part: 
![image](https://github.com/ansys/pyaedt/assets/96915188/3c0481ac-9644-4e38-a45f-8f1013dc7991)

In the previous version (0.6.74) it just ran `p = subprocess.Popen(cmd_translator)` without an if statement, but now it (in my case) it performes `p = subprocess.Popen(" ".join(cmd_translator)`.

I have then managed to further connect the issue with the name I choose for the folder where I placed my IPC2581 file (.xml). If the folder name has spaces in it, my import will fail when using version 0.6.75 or newer. 

So currently I bypass this issue with ensuring that there is no space in my folder name but would be nice to be able to have the option again like was possible in version 0.6.74 or older. 

### Steps To Reproduce

1. Place your layout file (IPC2581 / .xml) in a folder that has space in its name. 
`targetfile_IPC2581 =  r"C:\LayoutFiles\- XML Export\MyLayoutDesign.xml"`
2. Setup an Edb project: 
`aedb_path = os.path.join(targetdirectory, Project_name)`
`edb = pyaedt.Edb(edbpath=aedb_path, edbversion="2022.2")`
3. Try to import the layout file 
`edb.import_layout_pcb(targetfile_IPC2581, aedb_path, init_dlls=False, anstranslator_full_path='', use_ppe=False, control_file=None)
`

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

adodbapi==2.6.1.3
affine==2.3.1
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
aiosqlite==0.17.0
alabaster==0.7.12
alembic==1.7.7
algopy==0.5.7
altair==4.2.0
altair-data-server==0.4.1
altair-transform==0.2.0
altair-widgets==0.2.2
altgraph==0.17.2
amply==0.1.5
aniso8601==9.0.1
ansiwrap==0.8.4
ansys-api-fluent==0.3.12
ansys-api-mapdl==0.5.1
ansys-api-mechanical==0.1.0
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-api-sherlock==0.1.14
ansys-api-systemcoupling==0.1.0
ansys-dpf-composites==0.2.0
ansys-dpf-core==0.8.1
ansys-dpf-gate==0.3.1
ansys-dpf-gatebin==0.3.0
ansys-dpf-post==0.4.0
ansys-dynamicreporting-core==0.4.0
ansys-fluent-core==0.14.0
ansys-grantami-bomanalytics==1.1.3
ansys-grantami-bomanalytics-openapi==1.0.0
ansys-grantami-recordlists==1.0.0
ansys-grantami-serverapi-openapi==1.0.0
ansys-grpc-dpf==0.7.0
ansys-mapdl-core==0.64.1
ansys-mapdl-reader==0.52.8
ansys-math-core==0.1.1
ansys-mechanical-core==0.8.0
ansys-meshing-prime==0.4.0
ansys-motorcad-core==0.1.3
ansys-openapi-common==1.2.1
ansys-optislang-core==0.2.1
ansys-platform-instancemanagement==1.1.1
ansys-pythonnet==3.1.0rc1
ansys-seascape==0.2.0
ansys-sherlock-core==0.2.0
ansys-systemcoupling-core==0.1.3
anyio==3.5.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.2
asciitree==0.3.3
asgi-csrf==0.9
asgiref==3.7.2
asn1crypto==1.4.0
asteval==0.9.26
astor==0.8.1
astroid==2.11.3
astroML==1.0.2.post1
astropy==5.0.4
async-generator==1.10
async-timeout==4.0.2
atomicwrites==1.4.0
attrs==21.4.0
autopep8==1.6.0
Babel==2.10.1
backcall==0.2.0
backports-abc==0.5
baresql==0.7.6
base58==2.1.1
bcrypt==3.2.0
beautifulsoup4==4.11.1
binaryornot==0.4.4
black==22.3.0
bleach==5.0.0
blinker==1.4
blis==0.7.7
blosc==1.10.6
bokeh==2.4.2
botorch==0.4.0
Bottleneck==1.3.4
bqplot==0.12.33
branca==0.5.0
brewer2mpl==1.4.1
Brotli==1.0.9
build==0.10.0
cachelib==0.6.0
cachetools==5.0.0
Cartopy==0.20.2
catalogue==2.0.7
certifi==2021.10.8
cffi==1.15.1
cftime==1.6.0
chardet==4.0.0
charset-normalizer==2.0.12
click==8.1.3
click-default-group==1.2.2
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==2.0.0
clr-loader==0.2.5
clrmagic==0.0.1a2
colorama==0.4.4
colorcet==3.0.0
commonmark==0.9.1
contourpy==1.0.7
cookiecutter==1.7.3
coverage==6.3.2
cramjam==2.5.0
cryptography==3.4.7
csvs-to-sqlite==1.3.1a0
cvxopt==1.3.0
cvxpy==1.2.0
cx-Freeze==6.10
cx-Logging==3.0
cycler==0.11.0
cymem==2.0.6
Cython==0.29.28
cytoolz==0.11.2
dash==2.3.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dask==2022.4.2
dask-glm==0.2.0
dask-image==2021.12.0
dask-labextension==5.2.0
dask-ml==2022.1.22
dask-searchcv==0.2.0
databases==0.5.5
datasette==0.61.1
datasette-graphql==2.0.1
datashader==0.14.0
datashape==0.5.2
dateparser==1.1.0
db.py==0.5.4b1
deap==1.3.1
debugpy==1.6.0
decorator==4.4.2
defusedxml==0.7.1
Deprecated==1.2.13
deprecation==2.1.0
diff-match-patch==20200713
dill==0.3.3
distlib==0.3.4
distributed==2022.4.2
Django==4.2.4
docopt==0.6.2
docrepr==0.1.1
docutils==0.17.1
ecos==2.0.10
emcee==3.1.1
entrypoints==0.4
et-xmlfile==1.1.0
fast-histogram==0.10
fastai==2.6.3
fastapi==0.75.2
fastcore==1.3.27
fastdownload==0.0.5
fasteners==0.17.3
fastjsonschema==2.15.3
fastparquet==0.8.0
fastprogress==1.0.0
feather-format==0.4.1
filelock==3.12.2
Fiona==1.8.21
flake8==4.0.1
Flask==2.1.2
flask-accepts==0.18.4
Flask-Compress==1.12
Flask-Mail==0.9.1
flask-restx==0.5.1
Flask-Session==0.4.0
Flask-SQLAlchemy==2.5.1
flaskerize==0.14.0
flit==3.7.1
flit_core==3.7.1
folium==0.12.1
fonttools==4.31.2
formlayout==1.2.1a1
frozenlist==1.3.0
fs==2.4.15
fsspec==2022.3.0
future==0.18.2
fuzzywuzzy==0.18.0
GDAL==3.4.2
geographiclib==1.52
geomdl==5.3.1
geopandas==0.12.2
geopy==2.2.0
geoviews==1.9.5
gitdb==4.0.9
GitPython==3.1.26
gmpy2==2.1.2
google-api-core==2.10.1
google-api-python-client==2.74.0
google-auth==2.16.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.4
gpytorch==1.5.1
graphene==3.0
graphql-core==3.1.7
graphql-relay==3.1.5
great-expectations==0.14.11
greenlet==1.1.2
grpcio==1.51.1
grpcio-status==1.48.2
guidata==2.1.1
guiqwt==4.1.0
h11==0.12.0
h2==4.1.0
h5py==3.8.0
HeapDict==1.0.1
holoviews==1.14.8
hpack==4.0.0
html5lib==1.1
httpcore==0.14.7
httpie==3.1.0
httplib2==0.21.0
httptools==0.4.0
httpx==0.22.0
hupper==1.10.3
husl==4.0.3
hvplot==0.7.3
hypercorn==0.13.2
hyperframe==6.0.1
hypothesis==6.45.1
idlex==1.22
idna==3.1
imageio==2.17.0
imageio-ffmpeg==0.4.2
imagesize==1.3.0
imbalanced-learn==0.9.0
importlib-metadata==6.7.0
inflection==0.5.1
iniconfig==1.1.1
intake==0.6.4
intervaltree==3.0.2
iperf3==0.1.11
ipycanvas==0.11.0
ipykernel==6.13.0
ipyleaflet==0.14.0
ipympl==0.9.1
ipython==7.32.0
ipython-genutils==0.2.0
ipython-sql==0.4.1b1
ipywidgets==7.7.0
isort==5.10.1
itsdangerous==2.1.2
janus==1.0.0
jedi==0.18.1
jellyfish==0.9.0
Jinja2==3.0.3
jinja2-time==0.2.0
joblib==1.1.0
json5==0.9.6
jsonpatch==1.32
jsonpointer==2.3
jsonschema==4.4.0
julia==0.5.7
jupyter==1.0.0
jupyter-bokeh==3.0.4
jupyter-client==7.3.0
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyter-lsp==1.5.1
jupyter-packaging==0.12.0
jupyter-server==1.17.0
jupyter-server-mathjax==0.2.5
jupyter-server-proxy==3.2.1
jupyter-sphinx==0.3.2
jupyterlab==3.3.4
jupyterlab-git==0.34.2
jupyterlab-launcher==0.13.1
jupyterlab-lsp==3.10.1
jupyterlab-pygments==0.2.2
jupyterlab-server==2.13.0
jupyterlab-widgets==1.1.0
keyring==23.5.0
kiwisolver==1.4.2
langcodes==3.3.0
lazy-object-proxy==1.7.1
llvmlite==0.38.0
lmfit==1.0.3
locket==1.0.0
loky==3.1.0
lxml==4.9.2
lz4==4.0.0
Mako==1.2.0
Markdown==3.3.6
MarkupSafe==2.1.1
marshmallow==3.12.1
matplotlib==3.7.1
matplotlib-inline==0.1.3
maturin==0.12.14
mccabe==0.6.1
mercantile==1.2.1
mergedeep==1.3.4
metakernel==0.28.2
mistune==0.8.4
mizani==0.7.4
mkl-service==2.4.0
mlxtend==0.18.0
moviepy==1.0.3
mpl-scatter-density==0.7
mpld3==0.5.7
mpldatacursor==0.7.1
mpmath==1.2.1
msgpack==1.0.3
msvc-runtime==14.29.30133
multidict==6.0.2
multipledispatch==0.6.0
munch==2.5.0
murmurhash==1.0.6
mypy==0.942
mypy-extensions==0.4.3
mysql-connector-python==8.0.21
nbclassic==0.3.7
nbclient==0.5.13
nbconvert==6.5.0
nbconvert_reportlab==0.2
nbdime==3.1.1
nbformat==5.3.0
nbval==0.9.6
nest-asyncio==1.5.5
netCDF4==1.5.8
networkx==2.8
NLopt==2.7.0
nltk==3.7
notebook==6.4.11
notebook-shim==0.1.0
npTDMS==1.5.0
ntlm-auth==1.5.0
numba==0.55.1
numcodecs==0.9.1
numdifftools==0.9.40
numexpr==2.8.1
numpy==1.24.1
numpydoc==1.2.1
oct2py==5.4.3
octave-kernel==0.34.1
openpyxl==3.0.10
orjson==3.6.7
osmnx==1.3.0
osqp==0.6.2.post4
outcome==1.1.0
packaging==21.3
palettable==3.3.0
pandas==1.4.2
pandas-datareader==0.10.0
pandocfilters==1.5.0
panel==0.13.0
papermill==2.3.4
param==1.12.1
parambokeh==0.2.3
paramiko==2.8.0
paramnb==2.0.4
parso==0.8.3
partd==1.2.0
pathspec==0.9.0
pathy==0.6.1
patsy==0.5.2
pdfrw==0.4.post2
pdvega==0.2.1.dev0
pefile==2021.9.3
pep8==1.7.1
pexpect==4.8.0
pg8000==1.23.0
pickleshare==0.7.5
Pillow==9.1.0
PIMS==0.5
Pint==0.19.2
pipdeptree==2.2.1
pkginfo==1.8.2
platformdirs==2.5.2
plotly==5.7.0
plotnine==0.8.1.dev0
pluggy==1.0.0
plumbum==1.8.2
ply==3.11
pooch==1.6.0
portpicker==1.5.0
poyo==0.5.0
ppci==0.5.8
preshed==3.0.6
prettytable==3.2.0
priority==2.0.0
proglog==0.1.9
prometheus-client==0.14.1
prompt-toolkit==3.0.29
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.5
ptpython==3.0.20
ptyprocess==0.7.0
PuLP==2.3
py==1.11.0
py-lru-cache==0.1.4
pyaedt==0.6.75
pyaml==20.4.0
pyansys==2023.2.8
pyansys-docker==5.0.4
pyansys-tools-versioning==0.4.0
pyarrow==7.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAudio==0.2.11
pybars3==0.9.7
pybind11==2.9.2
pycodestyle==2.8.0
pycosat==0.6.3
pycparser==2.21
pyct==0.4.8
pydantic==1.8.2
pydeck==0.7.1
pydocstyle==6.1.1
pyepsg==0.4.0
pyerfa==2.0.0.1
pyflakes==2.4.0
pyflux==0.4.17
pygad==2.16.3
pygame==2.1.2
pygbm==0.1.0
Pygments==2.11.2
pyhdf==0.10.3
pyiges==0.2.1
pyinstaller==5.0.1
pyinstaller-hooks-contrib==2022.4
pylint==2.13.7
pyls-spyder==0.4.0
pymc==2.3.8
PyMeta3==0.5.1
pymongo==4.1.1
Pympler==1.0.1
PyNaCl==1.5.0
pynndescent==0.5.6
pyodbc==4.0.32
PyOpenGL==3.1.6
pypandoc==1.5
pyparsing==3.0.9
pypiwin32==223
pypng==0.20220715.0
pyproj==3.5.0
pyproject_hooks==1.0.0
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pyqtgraph==0.12.4
PyQtWebEngine==5.15.5
PyQtWebEngine-Qt5==5.15.2
pyrsistent==0.18.1
pyserial==3.5
pyshp==2.2.0
PySimpleGUI==4.60.4
PySocks==1.7.1
pystache==0.5.4
pytest==7.1.1
python-baseconv==1.2.2
python-dateutil==2.8.2
python-dotenv==0.19.2
python-hdf4==0.10.0+dummy
python-Levenshtein==0.12.2
python-lsp-black==1.2.1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.4.1
python-multipart==0.0.5
python-picard==0.7
python-slugify==6.1.2
python-snappy==0.6.1
pythonnet==3.0.1
PythonQwt==0.10.1
pytwin==0.3.0
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
PyVISA==1.12.0
pyvista==0.37.0
pyviz-comms==2.2.0
PyWavelets==1.3.0
pywin32==306
pywin32-ctypes==0.2.0
pywinpty==2.0.5
pywinusb==0.4.2
PyYAML==6.0
pyzmq==22.3.0
pyzo==4.12.3
pyzstd==0.15.2
QDarkStyle==3.0.3
qdldl==0.1.5.post2
qpsolvers==1.8.0
qstylizer==0.2.1
QtAwesome==1.1.1
qtconsole==5.3.0
QtPy==2.1.0
quadprog==0.1.8
quantecon==0.5.3
quart==0.17.0
rasterio==1.2.10
readme-renderer==35.0
redis==4.2.2
regex==2022.3.15
reportlab==3.6.9
requests==2.28.2
requests-negotiate-sspi==0.5.2
requests-ntlm==1.1.0
requests-toolbelt==0.9.1
rfc3986==1.5.0
rich==12.3.0
rise==5.7.1
rope==1.0.0
rpyc==5.3.1
rsa==4.9
Rtree==1.0.0
ruamel.yaml==0.17.17
Rx==3.1.1
scikit-fuzzy==0.4.1
scikit-image==0.19.2
scikit-learn==1.0.2
scikit-optimize==0.9.0
scikit-rf==0.26.0
scilab2py==0.6.2
scipy==1.8.0
scooby==0.7.1
scramp==1.4.1
scs==3.2.0
seaborn==0.11.2
Send2Trash==1.8.0
shap==0.40.0
shapely==2.0.1
simpervisor==0.4
simplegeneric==0.8.1
simplejson==3.17.6
simpy==4.0.1
six==1.16.0
sklearn-contrib-lightning==0.6.2.post0
slicer==0.0.7
slicerator==1.1.0
smart-open==5.2.1
smmap==5.0.0
snakeviz==2.1.0
sniffio==1.2.0
snowballstemmer==2.2.0
snuggs==1.4.7
sortedcontainers==2.4.0
sounddevice==0.4.4
soupsieve==2.3.2.post1
spacy==3.2.4
spacy-legacy==3.0.9
spacy-loggers==1.0.2
Sphinx==4.5.0
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
spyder==5.3.0
spyder-kernels==2.3.0
SQLAlchemy==1.4.35
sqlite-bro==0.12.2
sqlite-fts4==1.0.1
sqlite-utils==3.26
sqlparse==0.4.2
srsly==2.4.2
SRTM.py==0.3.7
starlette==0.17.1
statsmodels==0.13.2
streamlit==1.4.0
streamz==0.6.3
style==1.1.0
supersmoother==0.4
swifter==1.0.9
sympy==1.10.1
tables==3.7.0
tabulate==0.8.9
tblib==1.7.0
tenacity==8.0.1
termcolor==1.1.0
terminado==0.13.3
text-unidecode==1.3
textdistance==4.2.2
textwrap3==0.9.2
thinc==8.0.15
threadpoolctl==3.1.0
three-merge==0.1.1
tifffile==2022.4.22
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tomli_w==1.0.0
tomlkit==0.10.2
toolz==0.11.2
torch==1.11.0
torchaudio==0.11.0
torchvision==0.12.0
tornado==6.1
tqdm==4.64.0
traitlets==5.1.1
traittypes==0.2.1
trio==0.20.0
trio-asyncio==0.12.0
twine==4.0.2
twitter==1.19.2
typer==0.4.1
typing_extensions==4.2.0
tzdata==2022.1
tzlocal==4.2
ujson==5.2.0
umap-learn==0.5.1
uncertainties==3.1.6
update==0.0.1
uritemplate==4.1.1
urllib3==1.26.9
utm==0.7.0
uvicorn==0.17.6
validators==0.18.2
vega==3.6.0
vega-datasets==0.9.0
virtualenv==20.14.1
ViTables==3.0.2
voila==0.3.5
vtk==9.2.5
wasabi==0.9.1
wasmer==1.1.0
wasmer_compiler_cranelift==1.1.0
wasmer_compiler_singlepass==1.1.0
watchdog==2.1.7
watchgod==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.2
websockets==10.3
Werkzeug==2.1.2
widgetsnbextension==3.6.0
winpython==4.6.20220501
wordcloud==1.8.1
wrapt==1.14.0
wsproto==1.1.0
xarray==2022.3.0
XlsxWriter==3.0.3
xlwings==0.24.7
yapf==0.32.0
yarl==1.7.2
zarr==2.11.3
zict==2.2.0
zipp==3.8.0
zstandard==0.17.0

**Comment by Samuelopez-ansys** [comment]
@maxcapodi78 Why is needed in Windows to join all in a string? 

I agree with @Garpurinn , if there are spaces in the path, it will fail.

**Comment by svandenb-dev** [comment]
@Samuelopez-ansys @ring630  I am reverting to previous behavior

**Comment by svandenb-dev** [comment]
@Garpurinn I made a new pull request for reverting to previous behavior. Thanks for your feedback
