### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by felipeescastro** [ansys/pyaedt#3383]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi, 

The function create_model_from_touchstone, located in PrimitivesCircuit.py, is blocking the python session and not running as expected. 

Please verify.

### Steps To Reproduce

To reproduce the issue, simply run the attached script (after modify the path of the s-param file). You'll notice that AEDT is blocked and nothing is imported once we force the script to stop.

[ExportSingleFreqRLGCFromSParam.zip](https://github.com/ansys/pyaedt/files/12280514/ExportSingleFreqRLGCFromSParam.zip)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiofiles==22.1.0
aiosqlite==0.19.0           
anyio==3.6.2                
argon2-cffi==21.3.0         
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
camelot-py==0.11.0
certifi==2022.12.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.5
colorama==0.4.6
comm==0.1.3
contourpy==1.0.7
cryptography==40.0.2
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
distro==1.8.0
et-xmlfile==1.1.0
executing==1.2.0
fastjsonschema==2.16.3
Fiona==1.9.3
fonttools==4.39.3
fqdn==1.5.1
geopandas==0.12.2
ghostscript==0.7
idna==3.4
imageio==2.27.0
ipycanvas==0.13.1
ipyevents==2.0.1
ipykernel==6.22.0
ipython==8.12.0
ipython-genutils==0.2.0
ipyvtklink==0.2.3
ipywidgets==7.7.5
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.6.3
jupyter-ydoc==0.2.4
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.5.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.4
jupyterlab_server==2.22.1
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.7.2
matplotlib-inline==0.1.6
mistune==2.0.5
munch==2.5.0
nbclassic==0.5.5
nbclient==0.7.3
nbconvert==7.3.1
nbformat==5.8.0
nest-asyncio==1.5.6
networkx==3.1
notebook==6.5.4
notebook_shim==0.2.2
numpy==1.25.1
opencv-python==4.7.0.72
openpyxl==3.1.2
osmnx==1.3.0
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.0
parso==0.8.3
pdfminer.six==20221105
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.2.0
plumbum==1.8.1
pooch==1.7.0
prometheus-client==0.16.0
prompt-toolkit==3.0.38
psutil==5.9.5
pure-eval==0.2.2
pyaedt==0.6.87
pycparser==2.21
Pygments==2.15.1
pyparsing==3.0.9
PyPDF2==3.0.1
pyproj==3.5.0
pyqtgraph==0.13.3
pyrsistent==0.19.3
PySide6==6.4.0
PySide6-Addons==6.4.0
PySide6-Essentials==6.4.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pythonnet==3.0.1
pytz==2023.3
pyvista==0.40.2
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.2
QDarkStyle==3.1
QtPy==2.3.1
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpyc==5.3.1
scikit-rf==0.28.0
scipy==1.10.1
scooby==0.7.1
Send2Trash==1.8.0
shapely==2.0.1
shiboken6==6.4.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
SRTM.py==0.3.7
stack-data==0.6.2
tabulate==0.9.0
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3
traitlets==5.9.0
tzdata==2023.3
uri-template==1.2.0
urllib3==1.26.15
utm==0.7.0
vtk==9.2.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.1
widgetsnbextension==3.6.4
y-py==0.5.9
ypy-websocket==0.8.2

**Comment by Samuelopez-ansys** [comment]
Hi @felipeescastro ,

Please next time put a more descriptive title :)

I have fixed the issue. The problem with this method is checking the file's header if the terminal name is defined. But in your file, the terminal name is not specified.

We need to refactor this method because every time we have a new touchstone format, we need to add an exception. I let you improve it if you have time. 

As I said, in the PR #3384 I have fixed it.

Thanks

**Comment by felipeescastro** [comment]
Hi @Samuelopez-ansys ,

Sorry for the title! It won't happen again ;)

Thank you for the quick fix! I'll try to improve the method but just after you show me how you debbuged it. I was really lost to identify why it was failing. 

Thanks!
