### ISSUE TITLE
Allow for export of SYZ results in EdbSIwave.create_exec_file

### ISSUE THREAD

**Issue by pyAnsysUser** [ansys/pyaedt#3408]
### Description of the feature

There should be an option to export the touchstone during the creating of the simulation with [EdbSIwave.create_exec_file()](https://aedt.docs.pyansys.com/version/stable/EDBAPI/_autosummary/pyaedt.siwave.Siwave.export_element_data.html). Alternatively, for consistency with [Hfss3dLayout.export_touchstone()](https://aedt.docs.pyansys.com/version/stable/API/_autosummary/pyaedt.hfss3dlayout.Hfss3dLayout.export_touchstone.html), an additional method may be used in [Siwave](https://aedt.docs.pyansys.com/version/stable/EDBAPI/_autosummary/pyaedt.siwave.Siwave.html).

### Steps for implementing the feature

At present, I am able to achieve this functionality with:
```
edb.core_siwave.create_exec_file(add_syz = True)
append_export_to_execfile()
    
    def append_export_to_execfile(self):
        project_name = self.siw_name
        exec_file = os.path.join(self.batch_sims_folder, project_name + '.exec')
        export_file = os.path.join(self.batch_data_folder, project_name)
        exec_string = f'ExportTouchstone "{export_file}"\n'
        with open(exec_file, 'a') as f:
            f.writelines(exec_string)
```

**Comment by svandenb-dev** [comment]
@pyAnsysUser 
I have added the option
create_exec_file(
        self, add_dc=False, add_ac=False, add_syz=False, export_touchstone=False, touchstone_file_path=""
    )
now you can activate the touchstone export with the boolean. If the file_path is not provided a default one will be created at the same project location. 

closing the issue
