### ISSUE TITLE
Improve consistency of keywords

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyaedt#3409]
### Description of the current limitations

The keywords `design_name` and `designname` are used inconsistently as named arguments.  For example, `design_name` is a keyword in `conftest.add_app()` while `designname` is used in `Hfss()` for the same thing.

### Code sample expected

See description

### Useful links and references

[PEP 8](https://peps.python.org/pep-0008/)

**Comment by Samuelopez-ansys** [comment]
@maxcapodi78 This modification is needed I think, but it could introduce regression issues. What do you think?

**Comment by Samuelopez-ansys** [comment]
This issue is duplicated: #4420
