### ISSUE TITLE
letters ä, ö, ü, ß do not work in Ansys (version 2023 R2) with PyAEDT

### ISSUE THREAD

**Issue by Jessi0396** [ansys/pyaedt#3426]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Ansys/PyAEDT cuts of the last letter of a word if the word contains one of the letters ä, ö, ü, ß.

### Steps To Reproduce

Create something **with PyAEDT** that has a name for example a material, a cylinder or something else und give it a name that contains ä, ö, ü, ß
You will see that PyAEDT (or Ansys) cuts of the last letter of the word (no matter where exactly the letter ä, ö, ü or ß is in the word)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

from tkinter import *
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
import os
import pyaedt
import math

**Comment by gmalinve** [comment]
@Samuelopez-ansys

If AEDT is run in grpc mode the issue does happen (for example add_material).
When we update the material in add_material and call the native API method AddMaterial, for names containing specific chars, the method returns None (where it should return the name of the material created).
If AEDT is run in COM mode, this doesn't happen. The native API method returns the material name.

For other methods using special chars (create_rectangle etc) if AEDT is run in COM mode the message manager displays an error saying that the name cannot contain non-ASCII chars.
