### ISSUE TITLE
[Maxwell2D] skew model

### ISSUE THREAD

**Issue by mehs1006** [ansys/pyaedt#3447]
### Discussed in https://github.com/ansys/pyaedt/discussions/3434

<div type='discussions-op-text'>

<sup>Originally posted by **mehs1006** August 18, 2023</sup>
Hi,

In the Maxwell2D module, there's a function called "skew model".
I wonder if there's a command in PyAEDT that can make a skew model.
Thanks.
</div>

**Comment by Samuelopez-ansys** [comment]
@gmalinve

**Comment by gmalinve** [comment]
Hi @mehs1006 ,

Thanks for your request.
We don't have it yet but it's on our timeline.
We'll let you know as soon as is available.

Giulia

**Comment by gmalinve** [comment]
@MaxJPRey

**Comment by gmalinve** [comment]
Hi @mehs1006 and @MaxJPRey ,

The skew model option in Maxwell2D has been implemented and will be available in the next release.
Hope this helps!

Giulia

**Comment by MaxJPRey** [comment]
Thanks @gmalinve .

**Comment by mehs1006** [comment]
Thanks @gmalinve
