### ISSUE TITLE
Saving project before releasing desktop invalidates optimetrics solution

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyaedt#3451]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When I solve the optimetrics via PyAEDT, I am able to "View Analysis Results" while and after the simulation runs. Even after I "release_desktop", the results are still accessible via "View Analysis Results". However, if I save the project via PyAEDT before I "release_desktop", SOMETIMES all the results get immediately lost.

### Steps To Reproduce

I created a simple test case that replicates the issue.  The attached "optimetrics_error.zip" contains a .aedt project with the related jupyter notebook that reads it, runs the optimetrics, and saves the project.
[optimetrics_error.zip](https://github.com/ansys/pyaedt/files/12405437/optimetrics_error.zip)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
clr-loader==0.2.5
colorama==0.4.6
contourpy==1.1.0
cycler==0.11.0
exceptiongroup==1.1.1
fonttools==4.40.0
grpcio==1.47.5
grpcio-tools==1.47.5
idna==3.4
iniconfig==2.0.0
kiwisolver==1.4.4
matplotlib==3.7.1
numpy==1.25.0
packaging==23.1
panda==0.3.1
Pillow==9.5.0
platformdirs==3.6.0
pluggy==1.2.0
pooch==1.7.0
protobuf==3.20.3
psutil==5.9.5
pycparser==2.21
pyparsing==3.1.0
pytest==7.4.0
python-dateutil==2.8.2
pythonnet==3.0.1
pyvista==0.39.1
requests==2.31.0
scooby==0.7.2
six==1.16.0
tomli==2.0.1
urllib3==2.0.3
vtk==9.2.6

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev I think this is an internal Icepak issue... I tried and it worked for me. I will close the issue, and we will see in the future if it is possible to reproduce the issue again. In your script, I saw you were using 2024R1, so maybe it was a bug in the build version.
