### ISSUE TITLE
Maxwell2D skew model

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/pyaedt#3462]
Hi,

In the Maxwell2D module, there's a function called "skew model".
I wonder if there's a command in PyAEDT that can make a skew model.
Thanks.

_Originally posted by @mehs1006 in https://github.com/ansys/pyaedt/discussions/3434_

**Comment by Samuelopez-ansys** [comment]
@gmalinve

**Comment by Samuelopez-ansys** [comment]
It is in progress, commented by @gmalinve in #3447

**Comment by gmalinve** [comment]
@Samuelopez-ansys @MaxJPRey I'll close this issue since it has already been mentioned in #3447 .
Thanks for the heads up ;)
