### ISSUE TITLE
Automatically refresh all IDs in Icepak.mesh.assign_mesh_region()

### ISSUE THREAD

**Issue by Rungenwagen** [ansys/pyaedt#3480]
### Description of the feature

The function Icepak.mesh.assign_mesh_region() creates an non-model object "Box1", which is the bounding box of the mesh region. However, the object can't be selected using Icepak.modeler["Box1"] directly. The current solution is calling Icepak.modeler.refresh_all_ids() before using Icepak.modeler["Box1"].
So, I suggest refreshing all IDs automatically when the function Icepak.mesh.assign_mesh_region() is called.
Alternatively, you can just add this issue in the document of [assign_mesh_region()](https://aedt.docs.pyansys.com/version/stable/API/_autosummary/pyaedt.modules.MeshIcepak.IcepakMesh.assign_mesh_region.html) and [refresh_all_ids()](https://aedt.docs.pyansys.com/version/stable/API/_autosummary/pyaedt.modeler.modeler3d.Modeler3D.refresh_all_ids.html#refresh-all-ids) to remind users.

**Comment by gmalinve** [comment]
Hi @Rungenwagen,

This issue should have been fixed in PR #3509.
If interested please take a look.
This fix should be available in next release of pyaedt.

Thanks for submitting it.

Giulia
