### ISSUE TITLE
need enhancement to create_ipk_3dcomponent_pcb

### ISSUE THREAD

**Issue by nnetake** [ansys/pyaedt#3537]
### Description of the feature

Currently, we need to provide this input - "outline_polygon" while creating polygonal shape PCB comp in Icepak. It is difficult to get this outline_polygon name. Internally we should set this polygon name and should not take it as input from the user because this is available in hfss-3d-layout. This is the native code to retrieve the polygon name:

```
oProject = oDesktop.GetActiveProject()
oDesign = oProject.GetActiveDesign()
oLayout = oDesign.SetActiveEditor("Layout")
outline = oLayout.FindObjects('layer', 'Outline')
polys = oLayout.FilterObjectList('type', 'poly', outline)
```
@lorenzovecchietti  as we discussed.

**Comment by nnetake** [comment]
@Rungenwagen that's correct. Thanks for mentioning this.

**Comment by maxcapodi78** [comment]
I've fixed. Please have a look
