### ISSUE TITLE
Add export RL Table or export path resistance matrix from siwave DCIR solution

### ISSUE THREAD

**Issue by pyAnsysUser** [ansys/pyaedt#3559]
### Description of the feature

Having the RL table in text form through the API would allow further data analysis

**Comment by ring630** [comment]
@Samuelopez-ansys  @svandenb-dev it looks like method to export RL tale is missing from lower level code (EDB API). If it is the case, we cannot implement this method in pyaedt.

**Comment by pyAnsysUser** [comment]
I think I would be willing to move to 3D Layout for this feature- this seems to be feasible, but not a huge priority for me right now. Thanks for checking this out in edb.

**Comment by ring630** [comment]
@pyAnsysUser hfss3dlayout cannot have this feature too, I think. I will implement it once I figure out a way.

**Comment by pyAnsysUser** [comment]
I was thinking the ExportMatrixData ironpython command could be used for (the RL table), but I have not tried

**Comment by Samuelopez-ansys** [comment]
ExportMatrixData is implement in Q3D:

[export_matrix_data](https://aedt.docs.pyansys.com/version/dev/API/_autosummary/pyaedt.q3d.Q3d.export_matrix_data.html)

In Hfss3DLayout using SIwave, it is only implemented this workflow:
https://aedt.docs.pyansys.com/version/stable/examples/01-HFSS3DLayout/Dcir_in_3DLayout.html#sphx-glr-examples-01-hfss3dlayout-dcir-in-3dlayout-py

And in Q3D this one, which I think is more similar to what you are trying to do:
https://aedt.docs.pyansys.com/version/stable/examples/05-Q3D/Q3D_DC_IR.html#sphx-glr-examples-05-q3d-q3d-dc-ir-py
