### ISSUE TITLE
Implement Djordjevicsarkar model in MaterialLib

### ISSUE THREAD

**Issue by gmalinve** [ansys/pyaedt#3575]
- Add choice to add or edit freq. dependent materials
- Linked to #3531

**Comment by Samuelopez-ansys** [comment]
@ring630 Is this issue solved?

**Comment by ring630** [comment]
@Samuelopez-ansys not yet. the model equations are not implemented in native code. I need to do further investigation.

**Comment by ring630** [comment]
@AbelNTesfai , Djordjevic-Sarkar model is implemented.

**Comment by qalexk-a11y** [comment]
> [@AbelNTesfai](https://github.com/AbelNTesfai) , Djordjevic-Sarkar model is implemented.

Hello, im working on adding this feature to my code and i found same limitations with exixting implementation
1. there is no property to setup high cutoff frequency 
2. for some reason DK/DF frequency limited to 15GHZ. some of our materials corelated better with higher frequency
