### ISSUE TITLE
export_model_picture function does not consider selections attribute

### ISSUE THREAD

**Issue by StiftMC** [ansys/pyaedt#3589]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Dear All,

applying export_model_picture function like this:

```
ipk.post.export_model_picture(os.path.join(filepaths['ReportDir'], '3D.jpg'),
                                show_axis   = False,
                                show_grid   = False, 
                                show_ruler  = False, 
                                show_region = False, 
                                selections = [pcb name]
                                orientation = "isometric",
                                width       = 1920,
                                height      = 1080)
```
does show additional mesh region even though it is not selected. 

### Steps To Reproduce

Apply function and see exported image:

View in GUI:
![image](https://github.com/ansys/pyaedt/assets/100361281/8e6ad7b7-a9c6-4348-b0fe-661ffee94de8)

Exported Image:
![3D_Field](https://github.com/ansys/pyaedt/assets/100361281/967a6cc4-26a2-4501-9c3a-dde2cf7fe3a7)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

aiohttp==3.8.5
aiosignal==1.3.1
ansys-api-sherlock==0.1.20
ansys-dpf-core==0.9.0
ansys-dpf-gate==0.4.1
ansys-dpf-gatebin==0.4.1
ansys-grpc-dpf==0.8.1
ansys-sherlock-core==0.3.0
async-timeout==4.0.3
attrs==23.1.0
beautifulsoup4==4.12.2
bleach==6.0.0
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.1.0
cssutils==2.7.1
cycler==0.11.0
dataframe-image==0.2.1
defusedxml==0.7.1
et-xmlfile==1.1.0
fastjsonschema==2.18.0
fonttools==4.42.1
frozenlist==1.4.0
fuzzywuzzy==0.18.0
google-api-core==2.11.1
google-api-python-client==2.98.0
google-auth==2.23.0
google-auth-httplib2==0.1.1
googleapis-common-protos==1.60.0
grpcio==1.58.0
html2image==2.0.4.3
httplib2==0.22.0
idna==3.4
importlib-metadata==4.13.0
importlib-resources==6.0.1
Jinja2==3.1.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter-client==8.3.1
jupyter-core==5.3.1
jupyterlab-pygments==0.2.2
kiwisolver==1.4.5
Levenshtein==0.21.1
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.7.3
mistune==3.0.1
multidict==6.0.4
nbclient==0.8.0
nbconvert==7.8.0
nbformat==5.9.2
numpy==1.24.4
opencv-python==4.8.0.76
openpyxl==3.1.2
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.0
Pillow==10.0.0
pkgutil-resolve-name==1.3.10
platformdirs==3.10.0
plumbum==1.8.2
pooch==1.7.0
protobuf==3.20.3
psutil==5.9.5
pyaedt==0.6.93
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.16.1
pyodbc==4.0.39
pyparsing==3.1.1
python-dateutil==2.8.2
python-Levenshtein==0.21.1
pythonnet==3.0.2
pytz==2023.3.post1
pyvista==0.42.1
pywin32==306
pyzmq==25.1.1
rapidfuzz==3.3.0
referencing==0.30.2
requests==2.31.0
rpds-py==0.10.2
rpyc==5.3.1
rsa==4.9
scooby==0.7.2
six==1.16.0
soupsieve==2.5
tinycss2==1.2.1
tornado==6.3.3
tqdm==4.66.1
traitlets==5.9.0
tzdata==2023.3
uritemplate==4.1.1
urllib3==1.26.16
vtk==9.2.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.6.3
wrapt==1.12.1
wslink==1.8.2
xlrd==2.0.1
xlwings==0.30.4
xlwt==1.3.0
yarl==1.8.1
zipp==3.4.1

**Comment by StiftMC** [comment]
Dear All, 

it seems that the selection list works if I use any other object from the model tree than the PCB 3D Component. So problem is related with user defined components.

Regards, 
Michael

**Comment by Samuelopez-ansys** [comment]
@StiftMC Please share a project to reproduce the issue.

Maybe you could debug and find the issue on PyAEDT.

Regards,
Samuel

**Comment by StiftMC** [comment]
Hi @Samuelopez-ansys, 

it all boils down to the `oeditor.ExportModelImageToFile` function where I can't see the sources. That's why I opened the issue. 

However, I played around with the **ExportModelImageToFile** function in command window and found out, that it is not sufficient to give the name of the user defined component, i.e. the PCB in this case. Unfortunately you have to name all the single copper layers, the dielectric's and the solder masks as a list to get the correct picture. Like this:

```
ipk.post.export_model_picture(os.path.join(filepaths['ReportDir'], '3D_Field.jpg'),
                                show_axis   = False,
                                show_grid   = False, 
                                show_ruler  = False, 
                                show_region = False, 
                                selections  = ["PCB1_001_signal_1_Outline","PCB1_003_signal_2_Outline","PCB1_005_signal_3_Outline","PCB1_007_signal_4_Outline","PCB1_009_signal_5_Outline","PCB1_011_signal_6_Outline","Box3","PCB1_002_Dielectric_1_Outline","PCB1_004_Dielectric_2_Outline","PCB1_006_Dielectric_3_Outline","PCB1_008_Dielectric_4_Outline","PCB1_010_Dielectric_5_Outline","PCB1_000_SolderTop_Outline","PCB1_012_SolderBottom_Outline"],
                                orientation = "isometric",
                                field_selections = 'SurfTemperature1',
                                width       = 1920,
                                height      = 1080)
```

It's pretty annoying and does not really make sense, but its coherent that you have to list the element names as given in model tree (and not the groups). 

I'm sorry to bother you guys!
