### ISSUE TITLE
Error occurs in "import_dxf" method in HFSS

### ISSUE THREAD

**Issue by ngkazu** [ansys/pyaedt#3592]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

In import_dxf / Analysis3D.py:
----Line 1234  : v0.6.93
        if self.is3d:
            sheet_bodies_2d = False
----
Application instance except Maxwell dose not have self.is3d.
So, I get an error.

Please take action

Regards

### Steps To Reproduce

from pyaedt import Hfss
app= Hfss()
file_path= r'D:/temp/foo.dxf'
layers_list= ['Air', 'Die', 'HeatSink', ....]
app.import_dxf(file_path= file_path, layers_list= layers_list)

#-----

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

cffi==1.15.1
clr-loader==0.2.6
plumbum==1.8.2
psutil==5.9.5
pyaedt==0.6.93
pycparser==2.21
pythonnet==3.0.2
pywin32==306
rpyc==5.3.1

**Comment by gmalinve** [comment]
Hi @ngkazu ,

The issue has been fixed and will be available in next release.
Thanks for feedback!

Giulia
