### ISSUE TITLE
Coordinate system of a material

### ISSUE THREAD

**Issue by jmaravin** [ansys/pyaedt#3599]
### Description of the feature

Hi, I am unable to change through code the coordinate system of a material I´ve created. By default this is set to "Cartesian" but I want to change it to "Cylindrical". I cannot do it through python code and I need to change it manually on the AEDT GUI. I´ve looked around here in the forum and there´s some people with the same problem. I would like to know if there´s a way to do it and if not, propose ane enhancement of the code. 

Thanks very much for your help. 

### Useful links and references

<img width="270" alt="github" src="https://github.com/ansys/pyaedt/assets/138773415/d46ed11a-7061-4bda-9567-c69f21680ff3">

**Comment by gmalinve** [comment]
Hi @jmaravin,

It's not possible yet.
We do have a similar request already open: #2630 .

Thanks for feedback!

Giulia
