### ISSUE TITLE
Add gauge pressure and radiation temp to Icepak.edit_design_settings()

### ISSUE THREAD

**Issue by Rungenwagen** [ansys/pyaedt#3612]
### Description of the feature

Currently, the function Icepak.edit_design_settings() can't set gauge pressure and radiation temperature. They are in the first tab of the "Icepak Design Settings" dialog in AEDT GUI.
![AEDT_design_settings](https://github.com/ansys/pyaedt/assets/39006661/2442795b-d1e2-4886-98b3-b99a84150b29)

**Comment by maxcapodi78** [comment]
Implemented
