### ISSUE TITLE
Add ability to export 3D field plots to 3D pdfs

### ISSUE THREAD

**Issue by s-benter** [ansys/pyaedt#3660]
### Description of the feature

For Icepak FieldPlots, include the ability to export to a 3D PDF, rather than just a 2D image.  This would allow for more concise and more usable reports.  Rather than generating multiple images from multiple angles, the end user would be able to spin the model in the PDF to see all sides, rather than using a variety of 2D views to attempt to show all features.

### Steps for implementing the feature

Convert plot data to U3D or PRC formats for embedding in PDF.

### Useful links and references

https://www.ecma-international.org/wp-content/uploads/ECMA-363_4th_edition_june_2007.pdf

https://web.archive.org/web/20081202034541/http://livedocs.adobe.com/acrobat_sdk/9/Acrobat9_HTMLHelp/API_References/PRCReference/PRC_Format_Specification/index.html

**Comment by Samuelopez-ansys** [comment]
@lorenzovecchietti What is the status of this issue?

**Comment by lorenzovecchietti** [comment]
@Samuelopez-ansys it is not trivial, unfortunately. One possible way is to render the plot to pyvista, export it to vtk and then use a wrapper of this class https://vtk.org/doc/nightly/html/classvtkGL2PSExporter.html.

**Comment by Samuelopez-ansys** [comment]
@lorenzovecchietti I think we can close this issue because PyAEDT is not intended to create advanced reporting, the pyvista and obj plots can be easily exported using PyAEDT, then users can implement their way to add these 3D formats into a PDF or powerpoint. If you agree, please close the issue.

**Comment by lorenzovecchietti** [comment]
@Samuelopez-ansys agreed.
@s-benter If you want to implement this yourself, you might want to check this discussion https://web.archive.org/web/20170207211224/http://vtk.1045678.n5.nabble.com/colored-surface-model-as-a-3D-PDF-td5077778.html
