### ISSUE TITLE
Add API access to the impedance synthesizer 

### ISSUE THREAD

**Issue by SamtecChrisK** [ansys/pyaedt#3679]
### Description of the feature

For automated trace geometries it would be very helpful to have access to the impedance synthesis tool in the stack-up wizard. Set target impedance, set trace width or pitch, calculate the missing dimension. 

### Steps for implementing the feature

Maybe something like object3dlayout.sythesizeZ(RoutingLayer,Freq,TraceWidth, TracePitch, Z,SignalType) 

Most of those variable are self explanatory, SignalType would be Single Ended or Differential. The idea is to only require either TraceWidth or TracePitch and which ever is missing is calculated to hit target impedance Z.

**Comment by Samuelopez-ansys** [comment]
Hi @SamtecChrisK ,

The Stack-up wizard does not have an exposed API, which means it can not be controlled with commands, please contact the Ansys technical team, and they will submit an enhancement request for future AEDT versions.
