### ISSUE TITLE
HFSS3D Layout : I need to create some "Circuit Ports"...

### ISSUE THREAD

**Issue by Ouam74** [ansys/pyaedt#3694]
### Description of the feature

In a HFSS3D Layout :
I need to be able to create some "Circuit Ports", i am now able to create differential ports using the "h3d.create_differential_port()" function, but now i need to be able to change the port "HFSS Type" from "gap" to "circuit" :

![Screenshot 2023-10-02 215810](https://github.com/ansys/pyaedt/assets/44462129/882b930a-c8c5-4590-91da-ef8d9a415eae)

Another option would be to create a "h3d.create_circuit_port()" function.

I thank you very much in advance!

**Comment by ring630** [comment]
@Ouam74, the recommended workflow is to setup layout in edb, and then import it into HFSS 3D Layout for connector assembly, analysis, post processing, etc. 

Below is an example, how to setup a gap port, and switch it ot circuit port. Please have a try once the PR is merged.

```
from pyaedt import Desktop
from pyaedt import Hfss
from pyaedt import Edb
from pyaedt import Hfss3dLayout

import pyedb


desktop = Desktop(specified_version="2023.2")

edb = Edb(edbversion="2023.2")
edb.stackup.create_symmetric_stackup(4)

trace = edb.modeler.create_trace(
    path_list=[[0, 0], [0, "5mm"]],
    layer_name="TOP",
    width="0.1mm",
    start_cap_style="Flat",
    end_cap_style="Flat",
)

port = trace.create_edge_port(name="p2", position="end", port_type="Gap")
port.is_circuit_port = True


fpath_edb = edb.edbpath
edb.save()
edb.close()

h3d = Hfss3dLayout(fpath_edb)

desktop.release_desktop(False, False)

```
