### ISSUE TITLE
Unite operation in HFSS MCAD skips an element

### ISSUE THREAD

**Issue by marcoglasses** [ansys/pyaedt#3720]
### Before submitting the issue

- [X] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

open “hfss_mcad_experiments.aedt”. performing the attached pyaedt script to unite bodies, the operation is reported as successful, but a specific body is missing (Layer_1_L66), despite it being listed as entity to be united. 
Performing the operation manually produces a unified net. Pics attached. .aedt file attached as .zip.
![pyaedt_missingpiece](https://github.com/ansys/pyaedt/assets/131883613/0b9c09d4-6977-48c6-876f-3ca43bd040a3)
![manual_working](https://github.com/ansys/pyaedt/assets/131883613/bb43353c-3a01-4adb-8098-5e024d514dcd)

Here's the pyaedt script:

from pyaedt import Hfss

from pyaedt import general_methods

hfss = pyaedt.Hfss()

purge_history = True

hfss.modeler.unite(["Bottom_Layer_L122", "Layer_1_L11", "Layer_1_L17", "Layer_1_L22", "Layer_1_L23", "Layer_1_L3", "Layer_1_L30", "Layer_1_L36", "Layer_1_L38", "Layer_1_L43", "Layer_1_L46", "Layer_1_L48", "Layer_1_L49", "Layer_1_L51", "Layer_1_L53", "Layer_1_L56", "Layer_1_L58", "Layer_1_L59", "Layer_1_L66", "Layer_1_L7", "Top_Layer", "Top_Layer_L103", "Top_Layer_L109", "Top_Layer_L111", "Top_Layer_L150", "Top_Layer_L16", "Top_Layer_L17", "Top_Layer_L18", "Top_Layer_L32", "Top_Layer_L34", "Top_Layer_L60", "Top_Layer_L63", "Top_Layer_L64", "Top_Layer_L65", "Top_Layer_L67", "Top_Layer_L70", "Top_Layer_L83", "Top_Layer_L84", "Top_Layer_L88", "Top_Layer_L97", "Via126", "Via127", "Via128", "Via129", "Via130", "Via131", "Via132", "Via133", "Via134", "Via135", "Via136", "Via137", "Via138", "Via139", "Via140", "Via141", "Via142", "Via143", "Via144", "Via145", "Via146", "Via147", "Via148", "Via149", "Via150", "Via151", "Via152", "Via153", "Via154", "Via155", "Via156", "Via157", "Via158", "Via159", "Via160", "Via161", "Via162", "Via326"], purge = purge_history)

Here's the console log:

In [1]: from pyaedt import Hfss

In [2]: from pyaedt import general_methods

In [3]: hfss = pyaedt.Hfss()
PyAEDT INFO: StdOut has been enabled
PyAEDT INFO: using existing logger.
PyAEDT INFO: pyaedt v0.6.81
PyAEDT INFO: Python version 3.10.9 (remotes/origin/4e018266dafe29ec2836492d71d245fcfd366d07-dirty:4e018266, Jan  3 2) [MSC v.1920 64 bit (AMD64)]
PyAEDT INFO: AEDT 2023.2.0 Build Date 2023-05-16 22:25:19
PyAEDT INFO: No project is defined. Project hfss_mcad_experiment exists and has been read.
PyAEDT INFO: Active Design set to HFSSDesign1
PyAEDT INFO: Aedt Objects initialized
PyAEDT INFO: Variable Manager initialized
PyAEDT INFO: Design Loaded
PyAEDT INFO: Materials Loaded
PyAEDT INFO: aedt file load time 1.1180715560913086

In [4]: purge_history = True

In [5]: hfss.modeler.unite(["Bottom_Layer_L122", "Layer_1_L11", "Layer_1_L17", "Layer_1_L22", "Lay
   ...: er_1_L23", "Layer_1_L3", "Layer_1_L30", "Layer_1_L36", "Layer_1_L38", "Layer_1_L43", "Laye
   ...: r_1_L46", "Layer_1_L48", "Layer_1_L49", "Layer_1_L51", "Layer_1_L53", "Layer_1_L56", "Laye
   ...: r_1_L58", "Layer_1_L59", "Layer_1_L66", "Layer_1_L7", "Top_Layer", "Top_Layer_L103", "Top_
   ...: Layer_L109", "Top_Layer_L111", "Top_Layer_L150", "Top_Layer_L16", "Top_Layer_L17", "Top_La
   ...: yer_L18", "Top_Layer_L32", "Top_Layer_L34", "Top_Layer_L60", "Top_Layer_L63", "Top_Layer_L
   ...: 64", "Top_Layer_L65", "Top_Layer_L67", "Top_Layer_L70", "Top_Layer_L83", "Top_Layer_L84",
   ...: "Top_Layer_L88", "Top_Layer_L97", "Via126", "Via127", "Via128", "Via129", "Via130", "Via13
   ...: 1", "Via132", "Via133", "Via134", "Via135", "Via136", "Via137", "Via138", "Via139", "Via14
   ...: 0", "Via141", "Via142", "Via143", "Via144", "Via145", "Via146", "Via147", "Via148", "Via14
   ...: 9", "Via150", "Via151", "Via152", "Via153", "Via154", "Via155", "Via156", "Via157", "Via15
   ...: 8", "Via159", "Via160", "Via161", "Via162", "Via326"], purge = purge_history)
PyAEDT INFO: Union of 78 objects has been executed.
[hfss_mcad_experiment.zip](https://github.com/ansys/pyaedt/files/12832972/hfss_mcad_experiment.zip)

Out[5]: 'Bottom_Layer_L122'

Thanks!

### Steps To Reproduce

open attached aedt project. then, open pyaedt console.

Here's the pyaedt script to execute:

from pyaedt import Hfss

from pyaedt import general_methods

hfss = pyaedt.Hfss()

purge_history = True

hfss.modeler.unite(["Bottom_Layer_L122", "Layer_1_L11", "Layer_1_L17", "Layer_1_L22", "Layer_1_L23", "Layer_1_L3", "Layer_1_L30", "Layer_1_L36", "Layer_1_L38", "Layer_1_L43", "Layer_1_L46", "Layer_1_L48", "Layer_1_L49", "Layer_1_L51", "Layer_1_L53", "Layer_1_L56", "Layer_1_L58", "Layer_1_L59", "Layer_1_L66", "Layer_1_L7", "Top_Layer", "Top_Layer_L103", "Top_Layer_L109", "Top_Layer_L111", "Top_Layer_L150", "Top_Layer_L16", "Top_Layer_L17", "Top_Layer_L18", "Top_Layer_L32", "Top_Layer_L34", "Top_Layer_L60", "Top_Layer_L63", "Top_Layer_L64", "Top_Layer_L65", "Top_Layer_L67", "Top_Layer_L70", "Top_Layer_L83", "Top_Layer_L84", "Top_Layer_L88", "Top_Layer_L97", "Via126", "Via127", "Via128", "Via129", "Via130", "Via131", "Via132", "Via133", "Via134", "Via135", "Via136", "Via137", "Via138", "Via139", "Via140", "Via141", "Via142", "Via143", "Via144", "Via145", "Via146", "Via147", "Via148", "Via149", "Via150", "Via151", "Via152", "Via153", "Via154", "Via155", "Via156", "Via157", "Via158", "Via159", "Via160", "Via161", "Via162", "Via326"], purge = purge_history)

Here's the console log:

In [1]: from pyaedt import Hfss

In [2]: from pyaedt import general_methods

In [3]: hfss = pyaedt.Hfss()
PyAEDT INFO: StdOut has been enabled
PyAEDT INFO: using existing logger.
PyAEDT INFO: pyaedt v0.6.81
PyAEDT INFO: Python version 3.10.9 (remotes/origin/4e018266dafe29ec2836492d71d245fcfd366d07-dirty:4e018266, Jan  3 2) [MSC v.1920 64 bit (AMD64)]
PyAEDT INFO: AEDT 2023.2.0 Build Date 2023-05-16 22:25:19
PyAEDT INFO: No project is defined. Project hfss_mcad_experiment exists and has been read.
PyAEDT INFO: Active Design set to HFSSDesign1
PyAEDT INFO: Aedt Objects initialized
PyAEDT INFO: Variable Manager initialized
PyAEDT INFO: Design Loaded
PyAEDT INFO: Materials Loaded
PyAEDT INFO: aedt file load time 1.1180715560913086

In [4]: purge_history = True

In [5]: hfss.modeler.unite(["Bottom_Layer_L122", "Layer_1_L11", "Layer_1_L17", "Layer_1_L22", "Lay
   ...: er_1_L23", "Layer_1_L3", "Layer_1_L30", "Layer_1_L36", "Layer_1_L38", "Layer_1_L43", "Laye
   ...: r_1_L46", "Layer_1_L48", "Layer_1_L49", "Layer_1_L51", "Layer_1_L53", "Layer_1_L56", "Laye
   ...: r_1_L58", "Layer_1_L59", "Layer_1_L66", "Layer_1_L7", "Top_Layer", "Top_Layer_L103", "Top_
   ...: Layer_L109", "Top_Layer_L111", "Top_Layer_L150", "Top_Layer_L16", "Top_Layer_L17", "Top_La
   ...: yer_L18", "Top_Layer_L32", "Top_Layer_L34", "Top_Layer_L60", "Top_Layer_L63", "Top_Layer_L
   ...: 64", "Top_Layer_L65", "Top_Layer_L67", "Top_Layer_L70", "Top_Layer_L83", "Top_Layer_L84",
   ...: "Top_Layer_L88", "Top_Layer_L97", "Via126", "Via127", "Via128", "Via129", "Via130", "Via13
   ...: 1", "Via132", "Via133", "Via134", "Via135", "Via136", "Via137", "Via138", "Via139", "Via14
   ...: 0", "Via141", "Via142", "Via143", "Via144", "Via145", "Via146", "Via147", "Via148", "Via14
   ...: 9", "Via150", "Via151", "Via152", "Via153", "Via154", "Via155", "Via156", "Via157", "Via15
   ...: 8", "Via159", "Via160", "Via161", "Via162", "Via326"], purge = purge_history)
PyAEDT INFO: Union of 78 objects has been executed.
[hfss_mcad_experiment.zip](https://github.com/ansys/pyaedt/files/12832972/hfss_mcad_experiment.zip)

Out[5]: 'Bottom_Layer_L122'

Thanks!

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

running on pyaedt console after installing from within 23R2 self-install. also, this is my first issue, so apologies if some information is missing.

**Comment by Samuelopez-ansys** [comment]
Hi @marcoglasses ,

Thank you for the example, you have found a new parameter inside the Unite command, which affects when you have multiple bodies and Parasolid kernel. I have just created a Pull request with the modification (see it above). Thank you!
