### ISSUE TITLE
Improve IcepakMesh class to allow setting 2D MLM plane

### ISSUE THREAD

**Issue by s-benter** [ansys/pyaedt#3721]
### Description of the current limitations

Add API access to set the 2D MLM plane when known, e.g. XY, XZ, YZ.   Or if there's already a method, add documentation on how to access it.

**Comment by Samuelopez-ansys** [comment]
@lorenzovecchietti Could you check if an easy fix is possible to show DMLMTypes? 

Thanks

**Comment by lorenzovecchietti** [comment]
I added a docstring for the MeshRegion class.
So when a user creates the mesh region, he can see the different attributes and their meaning with the help command. I also explicitly wrote down available options for particular arguments, like the one related to this issue.

The alternative was to create setter and getter, but this seems harder to maintain with little benefit.
