### ISSUE TITLE
EDP API : edb.components.set_solder_ball, height depends on the diameter.

### ISSUE THREAD

**Issue by Ouam74** [ansys/pyaedt#3731]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The height of the solder ball is depending on the diameter:

![image](https://github.com/ansys/pyaedt/assets/44462129/6eb0fe56-c1df-4426-ad4b-1f823f265b8b)

### Steps To Reproduce

The height of the solder ball is depending on the diameter.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

pyaedt 0.7

**Comment by ring630** [comment]
@Ouam74 , I fixed this bug. Please wait for the merge.
