### ISSUE TITLE
Enable 'Fillet' and 'Chamfer' function to work with Coordinates in 2D Modeler

### ISSUE THREAD

**Issue by DaveTwyman** [ansys/pyaedt#3734]
### Description of the feature

Enable the Chamfer and Fillet operations to work directly with coordinates, instead of first having to get the vertex id.
This isn't as slick as it should be for a user trying to chamfer a corner directly in PyAEDT.

# One approach is the below
rect=M2D.modeler.create_rectangle (position = (0,0,0), dimension_list = (2,3,0), name='Rectangle')
vertexlist = (rect.vertices[0],rect.vertices[1])

for item in vertexlist:
    item.chamfer(left_distance=0.5,right_distance=None,angle=45)

**Comment by gmalinve** [comment]
Hi @DaveTwyman,

Could you be a bit more specific on what you mean for working with coordinates in 2D Modeler?
The approach you suggested above is the way we usually apply chamfers.
We don't apply chamfers by first having to get the vertex id but rather the vertex object in itself.

Thanks,

Giulia

**Comment by gmalinve** [comment]
Closing following discussion with @DaveTwyman.
