### ISSUE TITLE
Q2D Design Settings Methods

### ISSUE THREAD

**Issue by tizianrot** [ansys/pyaedt#3737]
### Description of the feature

As of today, I could not find methods to access Q2D design settigns, i. e. Model Depth 

### Steps for implementing the feature

One idea. analogous to Maxwell2d.model_depth()

**Comment by gmalinve** [comment]
Hi @tizianrot, have you checked the design_settings() method in Design.py?

**Comment by tizianrot** [comment]
Hi @gmalinve ,

thank you for the input. I think this is the way to go, however, it fails to update in Q2D:
![image](https://github.com/ansys/pyaedt/assets/88496115/eea6b501-993a-4386-8d80-ed5b682e09fb)
![image](https://github.com/ansys/pyaedt/assets/88496115/cb9d50ea-561d-40bd-a2cf-8b2bd3bd7b5e)

**Comment by gmalinve** [comment]
Hi @tizianrot ,

please try with method change_design_settings() in Design.py class and let me know.

Thanks!

**Comment by tizianrot** [comment]
Hi @gmalinve 
it works, thanks a lot!

**Comment by tizianrot** [comment]
I close the issue, it was about using the wright sequence of methods. Thank you
