### ISSUE TITLE
EDB API : The edb.components.set_solder_ball(...) function does not allow to set the 'Reference offset" parameter value.

### ISSUE THREAD

**Issue by Ouam74** [ansys/pyaedt#3740]
### Description of the feature

EDB API : The edb.components.set_solder_ball(...) function does not allow to set the 'Reference offset" parameter value.
This function is required by customers.

![image](https://github.com/ansys/pyaedt/assets/44462129/f3d9192c-9f9c-4118-bc77-01c56bae9046)

**Comment by ring630** [comment]
@Ouam74 set_solder_ball is updated with new input parameters to set reference plane.

**Comment by askoeho** [comment]
Hi @ring630. I think the reference_height should not be put behind the auto_reference_size setting. See the original picture from @Ouam74 that only the x and y sizes should be put behind the auto_reference_size setting.

Something like this 
![image](https://github.com/ansys/pyaedt/assets/5597705/3534c26c-7023-4c42-8d05-fcc6c853deaa)

**Comment by ring630** [comment]
@askoeho I will fix it. Thanks!
