### ISSUE TITLE
Bug located in MaxwellCircuit create_inductor etc

### ISSUE THREAD

**Issue by KoRba88** [ansys/pyaedt#3757]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

create_inductor, create_resistor, create_capacitor, create_winding, create_diode function do not pass compname to component in Maxwell Circuit schematic

Solution:

in PrimitivesMaxwellCircuit.py add (before "return id" in each function handler)

id.set_property("Name", compname)

### Steps To Reproduce

i.e
aedt_app = pyaedt.MaxwellCircuit(projectname=pyaedt.generate_unique_project_name())

inductor = aedt_app.modeler.schematic.create_inductor(compname="L5", value=2e-9, location=[0, 0])

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

attrs==23.1.0
certifi==2023.5.7
cffi==1.16.0
charset-normalizer==3.2.0
click==8.1.6
click-plugins==1.1.1
cligj==0.7.2
clipboard==0.0.4
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.1.0
cycler==0.11.0
et-xmlfile==1.1.0
Fiona==1.9.4.post1
fonttools==4.41.1
geopandas==0.13.2
idna==3.4
imageio==2.31.1
kiwisolver==1.4.4
matplotlib==3.7.2
networkx==3.1
numpy==1.25.2
openpyxl==3.1.2
osmnx==1.5.1
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
platformdirs==3.9.1
plumbum==1.8.2
pooch==1.7.0
psutil==5.9.5
pyaedt==0.7.0
pycparser==2.21
PyLTSpice==4.0.6
pyparsing==3.0.9
pyperclip==1.8.2
pyproj==3.6.0
python-dateutil==2.8.2
pythonnet==3.0.2
pytz==2023.3
pyvista==0.41.1
pywin32==306
requests==2.31.0
rpyc==5.3.1
scikit-rf==0.28.0
scipy==1.11.1
scooby==0.7.2
shapely==2.0.1
six==1.16.0
SRTM.py==0.3.7
tzdata==2023.3
urllib3==2.0.4
utm==0.7.0
vtk==9.2.6

**Comment by Samuelopez-ansys** [comment]
Hi @KoRba88 ,

You are right, are you going to make the implementation? I think is quite an easy fix and you could make your first contribution.

Thanks
Samuel
