### ISSUE TITLE
Add assign radiation boudary in Maxwell

### ISSUE THREAD

**Issue by Schwalbe262** [ansys/pyaedt#3764]
### Description of the feature

in HFSS, there are assign radiation settings like bellow

https://aedt.docs.pyansys.com/version/stable/API/_autosummary/pyaedt.hfss.Hfss.assign_radiation_boundary_to_faces.html
https://aedt.docs.pyansys.com/version/stable/API/_autosummary/pyaedt.hfss.Hfss.assign_radiation_boundary_to_objects.html

but it appears that Maxwell 2D and 3D do not have radiation boudary setting

![image](https://github.com/ansys/pyaedt/assets/41924534/54811923-4d22-4bde-85c9-274212180725)

Can we implemented this function? or Is there any alternative function?

### Steps for implementing the feature

oModule = oDesign.GetModule("BoundarySetup")
oModule.AssignRadiation(
	[
		"NAME:Radiation1",
		"Objects:="		, ["Region"]
	])

**Comment by Schwalbe262** [comment]
https://github.com/ansys/pyaedt/pull/3765

**Comment by Samuelopez-ansys** [comment]
Hi @Schwalbe262,

Thank you for your pull request, please check the comments, it is missed the unit tests and the docstring for the documentation, and we will be able to merge it to the main.
