### ISSUE TITLE
Running PyAEDT without launching AEDT 

### ISSUE THREAD

**Issue by peter197321** [ansys/pyaedt#3779]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

How to use PyAEDT without a need to launch AEDT in graphical or non-graphical mode. Not launch AEDT.

### Steps To Reproduce

https://aedt.docs.pyansys.com/version/stable/examples/03-Maxwell/Maxwell2D_DCConduction.html#sphx-glr-examples-03-maxwell-maxwell2d-dcconduction-py

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

pyaedt

**Comment by Samuelopez-ansys** [comment]
Hi @peter197321 ,

Any AEDT application (HFSS, Maxwell, Icepak...) needs AEDT to be launched, it is not a PyAEDT limitation but how AEDT works. 

Then you always need an aedt process running to open any of its applications, inside pyaedt there are some classes which does not need AEDT, like ModelPlotter:

https://aedt.docs.pyansys.com/version/stable/API/_autosummary/pyaedt.modules.AdvancedPostProcessing.ModelPlotter.html#pyaedt.modules.AdvancedPostProcessing.ModelPlotter
