### ISSUE TITLE
Unexpected warning shown when running siwave sweep

### ISSUE THREAD

**Issue by skandak-ansys** [ansys/pyaedt#3790]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When adding an siwave setup using pyaedt and simulating the design, I am seeing an unexpected warning like shown below.

![image](https://github.com/ansys/pyaedt/assets/98126702/a2764192-c718-4f79-b154-1776aeae541e)

### Steps To Reproduce

1. Take any AEDT project.
2. Use the pyaedt code below
```
h = Hfss3dLayout(path_to_project, specified_version="2023.2", non_graphical=True)
setup = h.create_setup(setupname="skt", setuptype="SiwaveAC3DLayout")

props = SiwaveAC3DLayout
props["SimulationSettings"]["UseSISettings"] = False # Set slider to PI simulation and Slider position to Balanced
setup.update(props)

sweep = setup.add_sweep("my_sweep", sweeptype="Interpolating")
sweep.change_range("LogScale", "0.000001", "10.0", "30", "MHz")
sweep.add_subrange("LinearStep", "0.01", "1", "0.01", "GHz")
sweep.update()
h.close_project(save_project=True)
```

3. Open project manually and solve the setup created by pyaedt. You will see a warning like shown below. On my specific project, this warning is causing my results to be poor (results are non-passive).
![image](https://github.com/ansys/pyaedt/assets/98126702/87940e28-c512-4c24-b276-7934093a0e93)

4. Now, manually delete the sweep added by pyaedt (but keep the setup). Add your own sweep and simulate. You can still see the warning. This confirms that the warning is due to the SIwave setup parameters.
5. Now delete the setup added by pyaedt and manually add a new setup & sweep (In setup, set to PI simulation). You don't see any warnings now. This confirms that that issue is with how pyaedt is creating the setup.

Note: I have tried to use EDB API instead of AEDT API (code below) and I get the same warning.

```
edb = Edb(local_edb, edbversion=”2023.2”)
setup1 = edb.create_siwave_syz_setup("skt")
setup1.use_si_settings = False
setup1.add_frequency_sweep(frequency_sweep=[
                          ["log scale", "1Hz", "10MHz", 30],
                          ["linear scale", "0.01GHz", "1GHz", "0.01GHz"],
                         ])
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

cffi==1.16.0
clr-loader==0.2.6
plumbum==1.8.2   
psutil==5.9.6    
pyaedt==0.7.0    
pycparser==2.21  
pythonnet==3.0.2 
pywin32==306     
rpyc==5.3.1

**Comment by ring630** [comment]
@skandak-ansys fix.
