### ISSUE TITLE
EDB API: Creating PEC ports

### ISSUE THREAD

**Issue by askoeho** [ansys/pyaedt#3837]
### Description of the feature

EDB API is missing the feature how to make a PEC port. Layout 3d supports these kind of ports as in the following screenshot:

![image](https://github.com/ansys/pyaedt/assets/5597705/005b75bf-481e-49ad-98ee-ead2fbc13dda)

**Comment by svandenb-dev** [comment]
Hi  @askoeho,
we will add this feature, thanks for your feedback.

**Comment by svandenb-dev** [comment]
@askoeho this was added please grab the latest version when it is available.
you can create PEC boundaries from 2 command now

edbapp.components.create_port_on_pins(refdes="U1", pins="AU38", reference_pins="AU37", pec_boundary=True)
edbapp.components.deactivate_rlc_component(component="C5", create_circuit_port=True, pec_boundary=True)
edbapp.components.add_port_on_rlc_component(component="C65", circuit_ports=False, pec_boundary=True)

please note that the first command only accept 2 pins (one for positive and one for reference) as PEC boundary is not supported with Pingroup.

first command
![image](https://github.com/ansys/pyaedt/assets/74993647/d9a4abd7-0a39-4545-998d-65b22929f0f4)


2 last command  
![image](https://github.com/ansys/pyaedt/assets/74993647/63d30fe3-aeee-4b08-8780-4e340cdf483c)

**Comment by askoeho** [comment]
What if I need to use PEC ports in vertical orientation? I'm currently doing this with the legacy API with the following code.

```
oEditor = h3d.oeditor
oEditor.CreatePortsOnComponentsByNet(
	[
		"NAME:Components", 
		"U1"
	], 
	[
		"NAME:Nets", 
		"GND"
	], "PEC", "0", "0", "0")
```
