### ISSUE TITLE
Monitor simulation and check results

### ISSUE THREAD

**Issue by arifroni** [ansys/pyaedt#3855]
Hello

I submit my jobs in unix cluster. I can do that by pyaedt. Is there any way to monitor the status of the job and if so, is it possible to get results from the simulation, like when I run simulation in GUI and check the results?

**Comment by Samuelopez-ansys** [comment]
@arifroni Apart from the get_monitor_data method nothing else is implemented. You can use the Electronics Desktop Job Monitoring tool.
