### ISSUE TITLE
Bug found in Maxwell3d.add_winding() ...

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyaedt#3868]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

``Maxwell3d.add_winding()`` does not take ``phase`` as an argument.

### Steps To Reproduce

Try passing ``phase`` as an argument. This is an allowed argument in the native API.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

All PyAedt dependencies are installed.

**Comment by dcrawforAtAnsys** [comment]
I was using an old version of PyAedt.

**Comment by Samuelopez-ansys** [comment]
@dcrawforAtAnsys PyAEDT grows fast 😜
