### ISSUE TITLE
pyaedt.Circuit.post.export_report_to_jpg()

### ISSUE THREAD

**Issue by z7766918** [ansys/pyaedt#3951]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

hi,
I loaded a Circuit project into Circuit, and I would like to export impedance plot from the report, so I called pyaedt.Circuit.post.export_report_to_jpg() fuction, below is my code :

import pyaedt
import pyvista as pv
from matplotlib.patches import PathPatch
from matplotlib.path import Path
import matplotlib.pyplot as plt

path = r"/home/fea/Desktop/USB4_Automation/result/64e848a895956a2167525542/USB4_TDR.aedt"
save_path = r"/home/fea/Desktop/USB4_Automation/result"
plot_name = "Differential Impedence@Tr=40ps(20-80%)"

circuit = pyaedt.Circuit(specified_version="2022.2", non_graphical=True, new_desktop_session=True, close_on_exit=True)
circuit.load_project(project_file=path, close_active_proj=False, save_active_project=False)
post = circuit.post
plot = post.export_report_to_jpg(project_dir=save_path, plot_name=plot_name, width=1550, height=660)
circuit.close_desktop()

but it shows errors like below :

(pyaedt) fea@fea-DGX-Station:~/Desktop/USB4_Automation$ /home/fea/anaconda3/envs/pyaedt/bin/python /home/fea/Desktop/USB4_Automation/test.py
Initializing new desktop!
PyAEDT INFO: StdOut is enabled
PyAEDT INFO: Log on file is enabled
PyAEDT INFO: Log on Desktop Message Manager is disabled
PyAEDT INFO: Debug logger is disabled. PyAEDT methods will not be logged.
PyAEDT INFO: Launching PyAEDT outside AEDT with gRPC plugin.
PyAEDT INFO: Launching AEDT using the gRPC plugin.
PyAEDT INFO: New AEDT session is starting on gRPC port 42029
PyAEDT INFO: AEDT installation Path /opt/AnsysEM/v222/Linux64
PyAEDT INFO: Ansoft.ElectronicsDesktop.2022.2 version started with process ID 2607129.
PyAEDT INFO: pyaedt v0.7.6
PyAEDT INFO: Python version 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
PyAEDT INFO: AEDT 2022.2.0 Build Date 2022-05-26 21:47:52
PyAEDT INFO: Project Project17 has been created.
PyAEDT INFO: No design is present. Inserting a new design.
PyAEDT INFO: Added design 'Circuit Design_NDE' of type Circuit Design.
PyAEDT INFO: Aedt Objects correctly read
Returning found desktop with PID 2607129!
PyAEDT INFO: Project USB4_TDR set to active.
PyAEDT INFO: Active Design set to Circuit Design_9JU
PyAEDT INFO: Aedt Objects correctly read
PyAEDT INFO: aedt file load time 0.07906007766723633
PyAEDT INFO: ModelerCircuit class has been initialized! Elapsed time: 0m 0sec
PyAEDT INFO: ModelerNexxim class has been initialized!
PyAEDT ERROR: AEDT GRPC API CALL ERROR on export_report_to_jpg
PyAEDT ERROR: Failed to execute grpc AEDT command: ExportImageToFile
PyAEDT ERROR:   File "/home/fea/Desktop/USB4_Automation/test.py", line 14, in <module>
PyAEDT ERROR:     plot = post.export_report_to_jpg(project_dir=save_path, plot_name=plot_name, width=1550, height=660)
PyAEDT ERROR:   File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/modules/PostProcessor.py", line 1327, in export_report_to_jpg
Traceback (most recent call last):
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/grpc_plugin.py", line 120, in __Invoke__
    return _retry_ntimes(
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/general_methods.py", line 712, in _retry_ntimes
    raise AttributeError("Error in Executing Method {}.".format(function.__name__))
AttributeError: Error in Executing Method InvokeAedtObjMethod.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/general_methods.py", line 188, in wrapper
    out = user_function(*args, **kwargs)
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/modules/PostProcessor.py", line 1327, in export_report_to_jpg
    self.oreportsetup.ExportImageToFile(plot_name, file_name, width, height)
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/grpc_plugin.py", line 133, in DynamicFunc
    return self.__Invoke__(funcName, args)
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/grpc_plugin.py", line 124, in __Invoke__
    raise GrpcApiError("Failed to execute grpc AEDT command: {}".format(funcName))
pyaedt.generic.general_methods.GrpcApiError: Failed to execute grpc AEDT command: ExportImageToFile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fea/Desktop/USB4_Automation/test.py", line 14, in <module>
    plot = post.export_report_to_jpg(project_dir=save_path, plot_name=plot_name, width=1550, height=660)
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/general_methods.py", line 227, in wrapper
    _exception(sys.exc_info(), user_function, args, kwargs, "AEDT grpc API call Error")
  File "/home/fea/anaconda3/envs/pyaedt/lib/python3.10/site-packages/pyaedt/generic/general_methods.py", line 120, in _exception
    message_to_print = messages[messages.index("[error]") :]
ValueError: substring not found

Here is my computer info :
OS : Linux
AEDT Version : 2022R2
pyaedt version : 0.7.6

### Steps To Reproduce

I can provide file if you need.

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.10

### Installed packages

ansys-pythonnet==3.1.0rc3
bidict==0.22.1
blinker==1.6.2
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
clr-loader==0.2.6
contourpy @ file:///opt/conda/conda-bld/contourpy_1663827406301/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
distro==1.8.0
dnspython==2.4.2
dotnetcore2==3.1.23
et-xmlfile==1.1.0
Flask==2.3.2
Flask-Login==0.6.2
Flask-Reuploaded==1.3.0
Flask-SocketIO==5.3.5
Flask-Uploads==0.2.1
fonttools==4.25.0
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
kiwisolver @ file:///croot/kiwisolver_1672387140495/work
llvmlite==0.40.1
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib @ file:///croot/matplotlib-suite_1693812469450/work
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
mkl-service==2.4.0
mpmath==1.3.0
munkres==1.1.4
numba==0.57.1
numpy @ file:///work/mkl/numpy_and_numpy_base_1682952636358/work
openpyxl==3.0.10
packaging @ file:///croot/packaging_1693575174725/work
pandas==2.0.3
Pillow==10.0.0
platformdirs==4.0.0
plumbum==1.8.2
ply==3.11
pooch==1.8.0
psutil==5.9.5
pyaedt==0.6.89
pybind11==2.11.1
pycparser==2.21
pymongo==4.4.1
pyparsing @ file:///opt/conda/conda-bld/pyparsing_1661452539315/work
PyQt5-sip==12.11.0
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-engineio==4.5.1
python-pptx==0.6.21
python-socketio==5.8.0
pythonnet==3.0.1
pytz==2023.3
pyvista==0.42.3
requests==2.31.0
rpyc==5.3.1
scikit-rf==0.28.0
scipy==1.11.1
scooby==0.9.2
sip @ file:///tmp/abs_44cd77b_pu/croots/recipe/sip_1659012365470/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
sympy==1.12
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tornado @ file:///croot/tornado_1690848263220/work
tzdata==2023.3
urllib3==2.0.4
vtk==9.3.0
Werkzeug==2.3.7
XlsxWriter==3.1.2

**Comment by Samuelopez-ansys** [comment]
@z7766918 This method is tested on Linux and it is working, please check this example where the method is used:

https://aedt.docs.pyansys.com/version/stable/examples/07-Circuit/Reports.html#sphx-glr-examples-07-circuit-reports-py

In addition, the possibility of exporting a picture in Non graphical mode was introduced in 2023 R1, so it was not possible in previous versions, I guess this is the problem you are facing. If you can not change the AEDT version, the only solution is to use Matplotlib and plot the data.

Like other examples:
https://aedt.docs.pyansys.com/version/stable/examples/02-HFSS/HFSS_Dipole.html#sphx-glr-examples-02-hfss-hfss-dipole-py
