### ISSUE TITLE
IPC export layout profile not included

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyaedt#3952]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

IPC exported remove all primitive which doesn't have net assigned. 

### Steps To Reproduce

import ipc im aedt -> save -> load aedb -> export ipc from pyaedt -> import xml file

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

NA

**Comment by louseph** [comment]
@svandenb-dev , IPC export is not proper for customer designs. I will share the designs directly.
