### ISSUE TITLE
Help page search is not working

### ISSUE THREAD

**Issue by FabianSchwartau** [ansys/pyaedt#3969]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The search on the help page
https://aedt.docs.pyansys.com/version/stable/search.html
never returns any results.
I tried multiple browsers/OS.

### Steps To Reproduce

Go to https://aedt.docs.pyansys.com/version/stable/search.html and search for something, hit enter, you get an empty page.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

What do python packages that I have installed to do with the web page?

**Comment by Samuelopez-ansys** [comment]
@FabianSchwartau Sometimes it is a bit slow, could you type a word (like box) and wait? 
<img width="1088" alt="image" src="https://github.com/ansys/pyaedt/assets/85613111/a85b0161-c1e7-4c20-88d8-134abc9b8862">

**Comment by FabianSchwartau** [comment]
Ok, that works.
I never waited for anything, I just hit enter. This just brings me to a blank page with the search box and nothing in it.
It is also quite annoying that Ctrl+Backspace does not work in the search edit box.

**Comment by Samuelopez-ansys** [comment]
@FabianSchwartau Sorry for the confusion, but it follows PyAnsys search bar, we can not change it only for PyAEDT.

What do you mean with Ctrl+Backspace? Not sure what this combination should do.

**Comment by FabianSchwartau** [comment]
I don't understand what you mean by "it follows PyAnsys search bar" - so it is out of "your" control?
I can live with the workaround now, but its a bit confusing and not clear. I have been working around this now for days before posting here and I am sure there are other people who are as confused as I was. Together with the fact that the help is not indexed by google, made it quite hard as a beginner to find anything.

How can you live without Ctrl+backspace? :P
It deletes the complete word left of the cursor.

**Comment by Samuelopez-ansys** [comment]
@FabianSchwartau PyAEDT is part of the PyAnsys initiative, so the documentation  style is part of the PyAnsys organization.

I will add two members to check if this performance could be improved :)

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey @SMoraisAnsys

**Comment by SMoraisAnsys** [comment]
@FabianSchwartau Hi, thanks for the feed back ! I understand your remarks about the documentation. I'll do my best to free up some time to have a look at it but I can't give a date. Btw, I wasn't adapted to CTR + Backspace but I love it :D
