### ISSUE TITLE
Improve Maxwell create_setup docstring, currently referring to HFSS

### ISSUE THREAD

**Issue by IreneWoyna** [ansys/pyaedt#3970]
### Description of the feature

*** this is a demo issue for pyAEDT for Maxwell training **

Replace HFSS by Maxwell in docstring in maxwell.py function create_setup()

**Comment by IreneWoyna** [comment]
![image](https://github.com/ansys/pyaedt/assets/98172186/bbe33e7b-67d2-455f-afc6-de93fb0b8f76)

**Comment by gmalinve** [comment]
fix code snippet example in :doc:`../SetupTemplatesMaxwell`
