### ISSUE TITLE
Add enable_parallel_projection to pyvista plot

### ISSUE THREAD

**Issue by ring630** [ansys/pyaedt#3981]
### Description of the feature

parallel projection shows better view when plotting Q2D design.

reference
https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.Camera.enable_parallel_projection.html

**Comment by Samuelopez-ansys** [comment]
@ring630 Could you provide a PyAEDT snipped code? I think you can get the PyVista object and then apply this enable_parallel_projection()
