### ISSUE TITLE
Import GDS with PyAEDT 

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyaedt#3992]
### Description of the feature

Currently GDS import is supported with PyEDB but we got request to have it also in PyAEDT

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev Is this issue related to #3744 ?

**Comment by amichel0205** [comment]
Simon is this related to HFSS 3D Layout or HFSS 3D?

**Comment by amichel0205** [comment]
Implementation in progress
