### ISSUE TITLE
Redirect messages from the desktop to the logger when in non-graphical mode.

### ISSUE THREAD

**Issue by Devin-Crawford** [ansys/pyaedt#4012]
### Description of the feature

Failures are caught by the ``_function_handler_wrapper()`` in the file ``.\generic\general_methods.py``. Debugging would be much easier if the messages from the native API that are posted to the desktop when the AEDT UI is visible could also be available from this wrapper method.

### Steps for implementing the feature

This may require an enhancement to the native API.

### Useful links and references

``oDesktop.GetMessages()``

**Comment by dcrawforAtAnsys** [comment]
This should be handled in ``_log_method()`` in the file ``general_methods.py``.

**Comment by maxcapodi78** [comment]
I'm currently refactoring the logger to support the history of messages from pyaedt and from Desktop.
