### ISSUE TITLE
Remove redundant keyword arguments when creating primitives.

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyaedt#4018]
### Description of the feature

Resolution of issue #4010 makes some keyword arguments for primitives obsolete. For example, ``app.modeler.create_rectangle(matname="Copper")`` can be replaced by ``app.modeler.create_rectangle(material_name)``.

### Steps for implementing the feature

The method ``GeometryModeler._create_object()`` will map variable keyword arguments to their corresponding properties.

**Comment by dcrawforAtAnsys** [comment]
Addressed in PR #4019.

**Comment by gmalinve** [comment]
Closed by #4019.
