### ISSUE TITLE
get_all_dielectrics_names

### ISSUE THREAD

**Issue by soliton37** [ansys/pyaedt#4104]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

aedt API, should return a list of dielectrics

### Steps To Reproduce

dielectrics = hfss.get_all_dielectrics_names

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.10

### Installed packages

_

**Comment by amichel0205** [comment]
Hi,

Looking at the code you shared I think you've forget to use () after commands dielectrics = hfss.get_all_dielectrics_names() and  sources = hfss.get_all_sources().
After correctin it the simple code below is returning the correct values:

```python
import pyaedt

aedtfilepath = r"C:\Data\Support\HFSS\viawizard.aedt"
version= 2023.2

hfss = pyaedt.Hfss(projectname=aedtfilepath, specified_version=version, non_graphical=False)

dielectrics = hfss.get_all_dielectrics_names()
print("diel", dielectrics)
conductor = hfss.get_all_conductors_names()
print("cond", conductor)
sources = hfss.get_all_sources()
print("sources", sources)


# hfss.save_project()
hfss.release_desktop(close_projects=False, close_desktop=False)
```
![image](https://github.com/ansys/pyaedt/assets/119294121/3c5e9abf-928f-49e2-8dbd-523e50edd588)

![image](https://github.com/ansys/pyaedt/assets/119294121/9e5b96b8-f905-4b7c-8261-315505c06870)
