### ISSUE TITLE
Index error in modules/Material.py -> Material.__init__() (color assignment)

### ISSUE THREAD

**Issue by clguenthe** [ansys/pyaedt#4170]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When more materials are created than the number of CSS4_COLORS defined, material creation fails with a list index error:
![image](https://github.com/ansys/pyaedt/assets/102694609/98271014-f7e5-4aad-9524-e90f86db3cd4)

Reason is within modules/Material.py -> Material.__init__():
https://github.com/ansys/pyaedt/blob/8d0c6c53a219e6a5281d45ea2d9c2917d281b642/pyaedt/modules/Material.py#L1292

This should be changed to 
`if (materiallib._color_id) >= len(vals):`
to guarantee that the following line will not raise a list index out of range error:
https://github.com/ansys/pyaedt/blob/8d0c6c53a219e6a5281d45ea2d9c2917d281b642/pyaedt/modules/Material.py#L1294

### Steps To Reproduce

See above - try to create more Materials (with different material names) using the Materials.add_materia() command than the number of colors defined in CSS4_COLORS.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

attrs==23.1.0
bottle==0.12.25
build==0.10.0
certifi==2023.7.22       
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
clr-loader==0.2.6        
colorama==0.4.6
contourpy==1.1.1
coverage==7.3.2
cycler==0.12.1
distlib==0.3.7
exceptiongroup==1.1.3    
filelock==3.13.1
fonttools==4.44.3
identify==2.5.31
idna==3.4
importlib-resources==6.1.1
iniconfig==2.0.0
kiwisolver==1.4.5
matplotlib==3.7.3
nodeenv==1.8.0
numpy==1.24.4
packaging==23.2
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
plumbum==1.8.2
pooch==1.8.0
pre-commit==3.5.0
psutil==5.9.6
py==1.11.0
pyaedt==0.6.92
pycparser==2.21
pyparsing==3.1.1
pyproject_hooks==1.0.0
pytest==7.2.2
pytest-cov==4.0.0
pytest-timeout==2.1.0
pytest-xprocess==0.22.2
python-dateutil==2.8.2
pythonnet==3.0.2
pyvista==0.42.3
pywin32==306
PyYAML==6.0.1
requests==2.31.0
rpyc==5.3.1
scooby==0.9.2
six==1.16.0
tomli==2.0.1
urllib3==2.1.0
virtualenv==20.24.6
vtk==9.3.0
waitress==2.1.2
zipp==3.17.0

**Comment by gmalinve** [comment]
Hi @nnetake and @clguenthe,
I'd suggest first to update pyaedt to latest version 0.7.20. 
I see that you are still using 0.6.92 and if the issue persists and you already found the fix please do it :)
Thanks!
Giulia

**Comment by clguenthe** [comment]
@gmalinve It's still there in the current code, see the links to the wrong line in the code, so needs to be fixed anyways (and yes, afterwards we'll need to go through an update our pyaedt version :) ) @nnetake is already working on the fix.

**Comment by nnetake** [comment]
@gmalinve I don't see any changes in 0.7.20 related to this issue so I do not expect it to be corrected, so I have raised the PR and added you as a reviewer.
