### ISSUE TITLE
Can't close/exit ANSYS AEDT Desktop - freeze with release_desktop(save_project=False, close_desktop=True)

### ISSUE THREAD

**Issue by onyx22574** [ansys/pyaedt#4198]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

![image](https://github.com/ansys/pyaedt/assets/84866154/cfa263da-d51c-4a52-bb6d-4051a4a09191)

### Steps To Reproduce

```
import sys
import atexit
from pyaedt import *
import pyaedt
pyaedt.settings.use_grpc_api=False

desktop = Desktop(
        specified_version= version,
        aedt_process_id = aedt_process_id,
        new_desktop_session=False,
        non_graphical=False,
        close_on_exit=False,
        student_version=False,
    )
q = pyaedt.Q3d(projectname=pyaedt.generate_unique_project_name(),specified_version="2023.2",non_graphical=False,new_desktop_session=True)
q.release_desktop(save_project=False, close_desktop=True)

```
![image](https://github.com/ansys/pyaedt/assets/84866154/cd4ca17e-e7b1-4eec-96b2-288ec2bd0164)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

Jupyter Notebook from ANSYS AEDT

**Comment by Samuelopez-ansys** [comment]
Hi @onyx22574 ,

THis code has one small issue, when you try to create the Q3D app, you specified that you want to create a new_desktop_session, so it tries to open a new AEDT. But PyAEDT for now can not control more than one AEDT session at the same time, so if you had already the "desktop" object created, you will have the error you are facing. This is the correct script:

![image](https://github.com/ansys/pyaedt/assets/85613111/8415467a-7ead-47f7-be65-f2ec8ac90925)

To avoid this kind of confusion, I would use load_project method if you want to open an specific project with a "desktop" object create:
https://aedt.docs.pyansys.com/version/0.7/API/_autosummary/pyaedt.hfss3dlayout.Hfss3dLayout.load_project.html#load-project

Or if you want to create an empty Q3D design, you can just not create the "desktop" object, and call directly:
q = pyaedt.Q3d(projectname=pyaedt.generate_unique_project_name(),specified_version="2023.2",non_graphical=False,new_desktop_session=False)

It is up to you. Please close the issue if you do not have more questions.

Thanks
