### ISSUE TITLE
(AO) Import Layer Stackup XML

### ISSUE THREAD

**Issue by aohta2021** [ansys/pyaedt#4240]
### Description of the feature

HFSS3D Layout GUI can import Layer Stackup XML.
It has material definition and layer construction.
Pintopinsetup command can support limited import Layer Stackup XML.
It could not support Thermal material and Frequency depended Dielectric material definition.
User want to import Layer Stackup XML without GUI.

**Comment by aohta2021** [comment]
It is related TFS#1006882:(AO) Seting Layer Stackup is not correct by pintopinsetup.exe

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev @ring630 Is this possible with PyEBD right?

**Comment by ring630** [comment]
@Samuelopez-ansys it is supported by PyEDB. @aohta2021, could you provide an example xml file I can test?

**Comment by aohta2021** [comment]
I have confirmed PyEDB can support it.
This issue is closed.
