### ISSUE TITLE
'pyaedt.modeler.modeler2d.Modeler2D.create_region' function requires improvement for Maxwell2D

### ISSUE THREAD

**Issue by yliu44197** [ansys/pyaedt#4251]
### Description of the current limitations

When creating a region in Maxwell2D using this function, it seems that users cannot correctly create a region when the solver type is "Cylindrical about Z". (Pad percent on "+Z" & "-Z" will always be 0.)
```python
from pyaedt import Maxwell2d

M2D = Maxwell2d("Project1", "Design1", "TransientZ")
M2D.modeler.create_circle([10, 0, 0], 5)
M2D.modeler.create_region(100)

M2D.release_desktop(False, False)
```
```python
from pyaedt import Maxwell2d

M2D = Maxwell2d("Project1", "Design1", "TransientZ")
M2D.modeler.create_circle([10, 0, 0], 5)
M2D.modeler.create_region([100, 200, 300, 400])

M2D.release_desktop(False, False)
```
These two codes both create an air region as below.
![image](https://github.com/ansys/pyaedt/assets/159108007/056648a1-50a5-4f3b-913f-769e1a1cf06e)

### Code sample expected

I would recommend the code as below can be implemented in **Primitive2D.py** in the upcoming versions so that this function applies for all existing solver types in Maxwell2D and 2D Extractor.
```python
@pyaedt_function_handler()
def create_region(self, pad_percent=300, is_percentage=True):
    if not isinstance(pad_percent, list):
        if self._app.design_type == "2D Extractor" or (self._app.design_type == "Maxwell 2D" and self._app.xy_plane):
            pad_percent = [pad_percent, pad_percent, 0, pad_percent, pad_percent, 0]
        else:
            pad_percent = [pad_percent, 0, pad_percent, pad_percent, 0, pad_percent]
    else:
        if self._app.design_type == "2D Extractor" or (self._app.design_type == "Maxwell 2D" and self._app.xy_plane):
            pad_percent = [pad_percent[0], pad_percent[1], 0, pad_percent[2], pad_percent[3], 0]
        else:
            pad_percent = [pad_percent[0], 0, pad_percent[1], pad_percent[2], 0, pad_percent[3]]
    return self._create_region(pad_percent, is_percentage)
```

**Comment by gmalinve** [comment]
Hi @yliu44197,

Thanks for your feedback!
I'd suggest for you to try and implement it if you already have something in mind or a solution :)
It's an open source repository so everyone can contribute!

Thanks!

Giulia
