### ISSUE TITLE
Editing all Icepak global mesh settings

### ISSUE THREAD

**Issue by attefocho** [ansys/pyaedt#4256]
### Description of the feature

Icepak.globalMeshSettings() seems to be tailored only to PCBs. Something like a 'globalmesh' object with attributes like UserSpecifiedSettings to switch to manual settings, MaxElementSizeX, BufferLayers, e.t.c.

IcepakMesh.automatic_mesh_3D doesn't provide this flexibility.

**Comment by lorenzovecchietti** [comment]
Enhancement included in #4313
