### ISSUE TITLE
LSF submission, Bug located in desktop.py (pyaedt-0.7.12)

### ISSUE THREAD

**Issue by kruglovIFX** [ansys/pyaedt#4286]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

desktop.py line 1912 missing an "=" sign:
`elif "NumCores" in line:`
should be
`elif "NumCores=" in line:`
otherwise submission to LSF doesn't work

### Steps To Reproduce

Execute submit_job() method for any design

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.10

### Installed packages

Does not depend on other packages. Same issue with other 0.6.XX and 0.7.XX versions

**Comment by kruglovIFX** [comment]
Error message in EDT if "=" sign not added:
![image](https://github.com/ansys/pyaedt/assets/136462756/4f9e3353-7821-4e54-82a9-7660394fd0c5)

**Comment by Samuelopez-ansys** [comment]
Hi @kruglovIFX , PyAEDT is an open-source library so that next time you can create a pull request and it will be merged into PyAEDT if it passes all the tests and PyAnsys checks. I have created a pull request with your suggestions. 

https://github.com/ansys/pyaedt/pull/4290/files

**Comment by kruglovIFX** [comment]
Hi @Samuelopez-ansys,
Alright, will do next time. Thanks!
