### ISSUE TITLE
Bug in ipk.boundaries

### ISSUE THREAD

**Issue by nnetake** [ansys/pyaedt#4311]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

In network boundaries, If I try to update the link resistance it does not get updated even after boundaries.update(). After some investigation, we found that if use `aedtapp.boundaries[3].links['Link1'].value` does not sync `aedtapp.boundaries[3].props["Links"]["Link1"][4] `. Need to correct that sync mechanism. Thanks!

### Steps To Reproduce

As discussed in the description.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

ansys-pythonnet==3.1.0rc3
attrs==23.2.0
cffi==1.16.0
clr-loader==0.2.6
defusedxml==0.7.1
fonttools==4.49.0
fpdf2==2.7.8
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
pillow==10.2.0
plumbum==1.8.2
psutil==5.9.8
pyaedt==0.8.1
pycparser==2.21
pyedb==0.4.0
pywin32==306
referencing==0.33.0
rpds-py==0.18.0
rpyc==5.3.1

**Comment by lorenzovecchietti** [comment]
Fixed in #4313
