### ISSUE TITLE
Unable to run pyAEDT with python 3.9. Fail at installing .[tests]

### ISSUE THREAD

**Issue by anspraksaph** [ansys/pyaedt#4357]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Unable to run pyAEDT with python 3.9. Fail at installing .[tests] with this error
![Screenshot 2024-03-12 094455](https://github.com/ansys/pyaedt/assets/101877396/30a1679b-a551-421d-af20-5dedd6203572)

### Steps To Reproduce

- Clone latest pyAEDT at C:\
- With Python 3.9 install, run these in cmd:
   1. py -3.9 -m venv C:\Users\test_admin\venv_3.9
   2. C:\Users\test_admin\venv_3.9\Scripts\activate
   3. python -m pip install pip -U
   4. python -m pip install wheel setuptools -U
   5. python -m pip install C:\pyaedt\\.[tests]  -----> error

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

plumbum==1.8.2
pywin32==306
rpyc==6.0.0

**Comment by SMoraisAnsys** [comment]
Thanks for the feedback.
@Samuelopez-ansys I've got to fix the dependencies version while working on the CICD refactoring.
Assigning this issue to not forget to handle that case.

**Comment by Samuelopez-ansys** [comment]
@SMoraisAnsys I think this issue is fixed right?
