### ISSUE TITLE
rename problem in hfss

### ISSUE THREAD

**Issue by arifroni** [ansys/pyaedt#4409]
I am renaming a geometry like this

```
hfssapp = Hfss(projectname=project_file, 
            specified_version=desktopVersion, 
            non_graphical=NonGraphical)
obj = hfssapp.modeler['AMB_V53_LS_AMB_Keramikquer_1']
obj.name = "AMB_Keramikquer_1"
```

If another geometry is present with this name, the code doesn't do anything/shows any error. 
So after a mass rename, I don't know how many of those renames are successful. 

how can I solve this?

**Comment by gmalinve** [comment]
Hi @arifroni,

yes you are right, we don't throw any message/exception if an object name is already in design.
I fixed this in this PR: #4431 where we'll throw a warning message if object's name is already present and rename won't be successful.
In the meanwhile I'll suggest to check before assignment:
`if my_name in hfss.modeler.object_names`

Hope this helps,

Giulia
