### ISSUE TITLE
Arguments deprecation

### ISSUE THREAD

**Issue by gmalinve** [ansys/pyaedt#4420]
- [x] Circuit
- [x] Hfss
- [x] Hfss 3d Layout
- [ ] Icepak
- [x] Maxwell
- [x] MaxwellCircuit
- [x] Mechanical
- [x] Q3D
- [x] SIwave
- [ ] Rmxprt
- [x] Twinbuilder
- [x] Post-processor
- [x] Primitives 2D/3D
- [x] Modeler 2D/3D
- [x] Schematic
- [x] Material
- [x] Boundary
- [x] Mesh
- [x] Report templates
- [x] Setups
- [x] Generic
- [x] Update doc @gmalinve @dcrawforAtAnsys 
- [x] Optimetrics
- [x] Variables
- [x] cables
- [ ] monitors
- [ ] Sweeps
- [x] solutions
- [x] Analysis (general) 
- [x] Application __init__ @maxcapodi78 @gmalinve 
- [ ] Non graphical @maxcapodi78 @gmalinve @dcrawforAtAnsys 
- [x] Design

**Comment by dcrawforAtAnsys** [comment]
@gmalinve I added SIwave to our list.

**Comment by MaxJPRey** [comment]
Very impressive work @gmalinve ! What a refactoring.
