### ISSUE TITLE
set lumped_port

### ISSUE THREAD

**Issue by asuperwang** [ansys/pyaedt#4438]
I want to set a circle as a lumped port. The steps are to set the X, Y, Z of the integration line as the starting coordinates (7.6, 0, 0), and then enter the relative coordinates in the dx, dy, dy of the status bar ( 0.9, 0, 0)
  But in the official documentation, two models must be created to achieve "signal and reference"
  I tried many methods but failed to create a lumped port incentive.

**Comment by gkorompi** [comment]
Hello @asuperwang, please try create_port_sheet=True, as the defined cicle is indeed a sheet.

**Comment by gkorompi** [comment]
Hello @asuperwang, did you have time to review my suggestion??

**Comment by asuperwang** [comment]
> Hello @asuperwang, did you have time to review my suggestion??

Yes, I tried it. But the lumped_port is still not created. Is my integration line not set properly?Or are some parameters set incorrectly?
![circle](https://github.com/ansys/pyaedt/assets/91042197/c6dd9acb-39e3-4dd2-83c1-a3da023f1582)
![lumped](https://github.com/ansys/pyaedt/assets/91042197/5da79e79-beca-4463-be0a-f7b74cc8ee94)
![sheet](https://github.com/ansys/pyaedt/assets/91042197/5e4cbdf3-c3e9-41b7-a077-4171044405f3)

**Comment by gkorompi** [comment]
Hello @asuperwang the correct expression is: 
hfss.lumped_port(signal="Port",create_port_sheet=False,integration_line=[[7.6,0,0],[0.9,0,0]],impedance = 50, name="1")

The integration_line should be a list of two points as expressed above. Also, when using two point integration line, you should use create_port_sheet = False, because create_port_sheet = True (wrongly recommended before) works only for int type integration_line (i.e. = AxisDir.ZPos etc).
Lastly, make sure that both endpoints lie on the port. If this still gives you an error please share the code and design if possible.

**Comment by asuperwang** [comment]
> Hello @asuperwang the correct expression is: hfss.lumped_port(signal="Port",create_port_sheet=False,integration_line=[[7.6,0,0],[0.9,0,0]],impedance = 50, name="1")
> 
> The integration_line should be a list of two points as expressed above. Also, when using two point integration line, you should use create_port_sheet = False, because create_port_sheet = True (wrongly recommended before) works only for int type integration_line (i.e. = AxisDir.ZPos etc). Lastly, make sure that both endpoints lie on the port. If this still gives you an error please share the code and design if possible.

After modification, lumped_port is still not created correctly.

My process of setting lumped_port is: the starting coordinates of the integration line (7.6, 0, 0), and then enter the relative coordinates (0.9, 0, 0) in the DX, DY, DZ of the status bar, but I can't get it right in the python script place setting.
I uploaded all my code in myrepository.The code is not completely finished yet. The problem lies in setting lumped_port.

https://github.com/asuperwang/pyaedt_antenna/blob/1af109287b260b42a0b9487213ae91f9468baab0/antenna.py

**Comment by gkorompi** [comment]
Hello @asuperwang the port you are trying to define is outside of the object selected:
![image](https://github.com/ansys/pyaedt/assets/156683163/a9482932-d99b-438d-b488-0d34934c44d5)

When coordinates are set correctly (inside the circle), the port is created: 
hfss.lumped_port("Port",  create_port_sheet=False, port_on_plane=True, integration_line=[[7.2, -1.4, 0], [6.8, 1.4, 0]], impedance=50, name="1")

![image](https://github.com/ansys/pyaedt/assets/156683163/724fbce6-52a3-44cc-8a8c-d8fd8c56be3a)

**Comment by asuperwang** [comment]
> Hello @asuperwang the port you are trying to define is outside of the object selected: ![image](https://private-user-images.githubusercontent.com/156683163/321529199-2face8f8-c45d-4219-b27c-e73e795341e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDY3MDUsIm5iZiI6MTcxMjg0NjQwNSwicGF0aCI6Ii8xNTY2ODMxNjMvMzIxNTI5MTk5LTJmYWNlOGY4LWM0NWQtNDIxOS1iMjdjLWU3M2U3OTUzNDFlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODczYzRjZDBkNDE1NjhjNjkwMGZiMGEwOGRkMGJmNTY0NThlOTgzZDgwZjdlN2FiNmUxYzY3OTQ4YWYyMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bz43527ucLVBHacDWTXtBqSzNuF2GMt_VzFh68EDRyg)
> 
> When coordinates are set correctly (inside the circle), the port is created: hfss.lumped_port("Port", create_port_sheet=False, port_on_plane=True, integration_line=[[7.2, -1.4, 0], [6.8, 1.4, 0]], impedance=50, name="1")
> 
> ![image](https://private-user-images.githubusercontent.com/156683163/321528831-724fbce6-52a3-44cc-8a8c-d8fd8c56be3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDY3MDUsIm5iZiI6MTcxMjg0NjQwNSwicGF0aCI6Ii8xNTY2ODMxNjMvMzIxNTI4ODMxLTcyNGZiY2U2LTUyYTMtNDRjYy04YThjLWQ4ZmQ4YzU2YmUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWVhNWMwMzBkYTM0MjYzOTNlYWI3YmY3NjNmMDQ3YzQwNmIyNzgzNGM5MzAzYzYwNWRlZTM2YzIzOWNhODA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.43_ZtSeHgmZChDc1ylfH1U3JBnXOsH_akhfJUzb-bL4)

I have solved this problem, thank you very much for helping me。
