### ISSUE TITLE
Export picture from only one selected 3Dcomponent in Icepak

### ISSUE THREAD

**Issue by BenjaminFriess** [ansys/pyaedt#4489]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hello,
I have a project in which I have several 3D components. I want to write a python script, that automatically exports a picture from each 3Dcomponent alone. So basically, I wanted to use the function export_model_picture(), and specify which 3Dcomponent I want to export. Unfortunately, it always exports the full view. Does someone have any idea how to solve this issue?
Thanks

### Steps To Reproduce

icepak.post.export_model_picture(r"C:\tmp\image.jpg", 'False', 'False', 'False', 'False', 'None', field_selections = modeler.get_3d_component_object_list(components_list[1]), orientation='dimetric', width=1500,height=1500)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

pyaedt

**Comment by lorenzovecchietti** [comment]
Given `ipk` (the `pyaedt.Icepak` object), the string with the `component_name`, and a string with `export_image_filepath`, you have two options:

```
comp=ipk.modeler.user_defined_components[component_name].edit_definition()
comp.post.export_model_picture(export_image_filepath)
```

Or, if you want to use the script in non-graphical mode, you can use the integration with pyvista:
```
ipk.post.plot_model_obj([obj.name for obj in ipk.modeler.user_defined_components[component_name].parts.values()], export_path=export_image_filepath)
```
