### ISSUE TITLE
Q3D get selections

### ISSUE THREAD

**Issue by arifroni** [ansys/pyaedt#4519]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I want to get the face ids of the faces that I have selected manually. How do I do that?

### Steps To Reproduce

<>

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

<>

**Comment by Samuelopez-ansys** [comment]
@arifroni You can get the selections using:

app.modeler.selections

This will return the selected object IDs. Then using app.modeler you can find which object is selected.
