### ISSUE TITLE
AEDT doc landing page - Remove PyEDB card?

### ISSUE THREAD

**Issue by PipKat** [ansys/pyaedt#4524]
Given that the PyEDB API Reference section is no longer part of the PyAEDT documentation should the doc landing page be edited to:

- Rename the card with the title "AEDT API reference" to "API reference" as in the doc for all other PyAnsys libraries.
- Remove the card with the title "EDB API reference" given separate PyEDB documentation now exists. (Add a note to the AEDT doc landing page with a link to the EDB documentation.)

THE TASK IN THIS NEXT BULLET HAS BEEN MOVED TO A SEPARATE ISSUE (https://github.com/ansys/pyaedt/issues/4574).

- Relabel the cheat sheets for each of these libraries according and then display them in the left navigation pane of their respective doc landing pages. This would also include removing the text content and links in the README and in the doc because cheat sheets would be so much more visible. (Or, would we want to wait until cheat sheets are redone using Markdown source files and the [PyAnsys Quarto Cheat Sheet](https://github.com/ansys-internal/pyansys-quarto-cheatsheet) extension?)

@MaxJPRey and @maxcapodi78 If you agree with any or all of these recommended changes, let me know which to pursue and assign me this issue.

**Comment by MaxJPRey** [comment]
@PipKat I fully agree with your 3 suggestions.

Maybe at some point, we could add a link in the PyAEDT doc toward the PyEDB doc because they are related.

Adding @SMoraisAnsys  for visibility.

**Comment by SMoraisAnsys** [comment]
Great suggestions ! If you want to do it, I would gladly let you handle items 1 and 2.
For the last one, we might try to work with pyansys quarto but it could be done in a second group of changes / PR.
