### ISSUE TITLE
add_frequency_sweep(self, name=None, frequency_sweep=None) can't work in HFSS3dlayout

### ISSUE THREAD

**Issue by Acaptian** [ansys/pyaedt#4529]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The frequency sweep by "edb.create_hfss_setup()" cannot be used in hfss3Dlayout. 
![20240418134925](https://github.com/ansys/pyaedt/assets/152392017/bbd1ad37-70f9-43be-8b9d-bd2f1d75ed3e)

### Steps To Reproduce

import pyaedt
from pyaedt import Edb
from pyaedt import Hfss3dLayout
from datetime import datetime

edb = Edb(edbpath=aedb_path)
    setup = edb.create_hfss_setup("setup1")
    setup.add_frequency_sweep(
        frequency_sweep=[
            ["linear count", "0", "1kHz", 1],
            ["log scale", "1kHz", "0.1GHz", 10],
            ["linear scale", "0.1GHz", "10GHz", "0.1GHz"],
        ]
    )
edb.save_edb()
edb.close_edb()
h3d = Hfss3dLayout(projectname=aedb_path, non_graphical=False, new_desktop_session=True)
h3d.save_project()
h3d.release_desktop()
### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

altgraph                  0.17.4   
ansys-pythonnet           3.1.0rc3 
attrs                     23.2.0   
certifi                   2024.2.2 
cffi                      1.16.0   
charset-normalizer        3.3.2    
click                     8.1.7    
click-plugins             1.1.1    
cligj                     0.7.2    
clr-loader                0.2.6    
colorama                  0.4.6    
contourpy                 1.2.0    
control                   0.9.4    
cycler                    0.12.1   
defusedxml                0.7.1    
et-xmlfile                1.1.0    
fiona                     1.9.6
fonttools                 4.45.0
fpdf2                     2.7.7
geopandas                 0.14.3
idna                      3.6
imageio                   2.34.0
Jinja2                    3.1.3
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
MarkupSafe                2.1.5
matplotlib                3.8.2
networkx                  3.2.1
numpy                     1.26.2
openpyxl                  3.1.2
osmnx                     1.9.1
packaging                 23.2
pandas                    2.1.3
pefile                    2023.2.7
Pillow                    10.1.0
pip                       24.0
platformdirs              4.2.0
plumbum                   1.8.2
pooch                     1.8.1
psutil                    5.9.6
pyaedt                    0.8.3
pycparser                 2.21
pyedb                     0.6.0
pyinstaller               6.5.0
pyinstaller-hooks-contrib 2024.3
pyparsing                 3.1.1
pyproj                    3.6.1
PyQt5                     5.15.10
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.13.0
PyQt5-stubs               5.15.6.0
python-dateutil           2.8.2
pythonnet                 3.0.3
pytomlpp                  1.0.13
pytz                      2023.3
pyvista                   0.43.4
pywin32                   306
pywin32-ctypes            0.2.2
qt-material               2.14
referencing               0.33.0
requests                  2.31.0
rpds-py                   0.17.1
rpyc                      6.0.0
scikit-rf                 0.32.0
scipy                     1.11.3
scooby                    0.9.2
setuptools                68.2.2
shapely                   2.0.3
six                       1.16.0
SRTM.py                   0.3.7
tzdata                    2023.3
urllib3                   2.2.1
utm                       0.7.0
vtk                       9.2.6
wheel                     0.36.2

**Comment by Samuelopez-ansys** [comment]
Hi @Acaptian ,

First, this is a PyEDB issue, I will transfer it. 

Second, I see a solver error, which is not a PyEDB/ PyAEDT problem, your computer is OUT OF RAM. Please if you have questions regarding the setup, reach the Ansys technical support.
