### ISSUE TITLE
Update Contrbuting.rst to reflect keyword conventions.

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyaedt#4547]
### Description of the current limitations

Recent refactoring efforts have focused on creating consistent keyword name conventions throughout the repo. The documentation should be updated to reflect these conventions to ensure that future updates are consistent.

### Code sample expected

Update the code style section in `./doc/source/Getting_started/Conributing.rst`

**Comment by dcrawforAtAnsys** [comment]
@gmalinve FYI.

**Comment by MaxJPRey** [comment]
Agreed. Nice catch @dcrawforAtAnsys .

**Comment by gmalinve** [comment]
Linked #4420 and [v1.0](https://github.com/ansys/pyaedt/milestone/3)
