### ISSUE TITLE
Error in plotting vector fields

### ISSUE THREAD

**Issue by vaishnavibhope** [ansys/pyaedt#4563]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I am trying to plot and export fields using plot_field. The function works fine when exporting Magnitude plots but throws a fatal error for Vector plots.

### Steps To Reproduce

- Run any HFSS project and save fields.
- Run the python code first for quantity="Mag_E"
- Change quantity="Vector_E" and run the code
Change the project and design name in the code.
[field_plot.txt](https://github.com/ansys/pyaedt/files/15059730/field_plot.txt)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

ansys-pythonnet==3.1.0rc3
asttokens==2.4.1
attrs==23.1.0
av==12.0.0
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==3.0.0
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.0
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
et-xmlfile==1.1.0
executing==2.0.1
fiona==1.9.5
fonttools==4.45.1
fpdf2==2.7.8
geopandas==0.14.1
idna==3.6
imageio==2.33.0
imageio-ffmpeg==0.4.9
ipykernel==6.27.1
ipython==8.18.1
jedi==0.19.1
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
matplotlib==3.8.0
matplotlib-inline==0.1.6
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.26.0
opencv-python-headless==4.9.0.80
openpyxl==3.1.2
osmnx==1.7.1
packaging==23.2
pandas==2.1.1
parso==0.8.3
Pillow==10.1.0
platformdirs==4.0.0
plumbum==1.8.2
pooch==1.8.0
prompt-toolkit==3.0.41
psutil==5.9.6
pure-eval==0.2.2
pyaedt==0.8.0
pyargus==1.1.post1
pycparser==2.21
pyedb==0.2.0
Pygments==2.17.2
pyparsing==3.1.1
pyproj==3.6.1
pyqtgraph==0.13.3
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
python-dateutil==2.8.2
pytz==2023.3.post1
pyvista==0.42.2
pywin32==306
pyzmq==25.1.1
QDarkStyle==3.2.3
QtPy==2.4.1
referencing==0.34.0
requests==2.31.0
rpds-py==0.18.0
rpyc==5.3.1
scikit-rf==0.29.1
scipy==1.11.4
scooby==0.9.2
setuptools==69.0.2
shapely==2.0.2
shiboken6==6.6.1
six==1.16.0
spyder-kernels==2.5.0
SRTM.py==0.3.7
stack-data==0.6.3
tornado==6.4
traitlets==5.14.0
tzdata==2023.3
urllib3==2.1.0
utm==0.7.0
vtk==9.3.0
wcwidth==0.2.12

**Comment by maxcapodi78** [comment]
@vaishnavibhope I've looked into your issue. I don't have any error in latest pyaedt version but I see missing fields from the plot so I've fixed it and it runs for me on the same example
