### ISSUE TITLE
pyaedt modeler modeler2d Modeler2D create_point syntax error in example

### ISSUE THREAD

**Issue by Herve-L1** [ansys/pyaedt#4565]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

>>> from pyaedt import hfss
>>> hfss = Hfss()
>>> point_object = hfss.modeler.primivites.create_point([0,0,0], name="mypoint")

The right syntax is:
from pyaedt import hfss
>>> hfss = Hfss()
>>> point_object = hfss.modeler.primivites.create_point([0,0,0], "mypoint", "(255 0 0)")

### Steps To Reproduce

>>> from pyaedt import hfss
>>> hfss = Hfss()
>>> point_object = hfss.modeler.primivites.create_point([0,0,0], name="mypoint")

The right syntax is:
from pyaedt import hfss
>>> hfss = Hfss()
>>> point_object = hfss.modeler.primivites.create_point([0,0,0], "mypoint", "(255 0 0)")
[support Case00068454_01.docx](https://github.com/ansys/pyaedt/files/15060659/support.Case00068454_01.docx)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

C:\Users\212508492\AppData\Roaming\Python\Python311>python -m pip freeze
ansys-pythonnet==3.1.0rc3
attrs==23.2.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
defusedxml==0.7.1
et-xmlfile==1.1.0
fiona==1.9.6
fonttools==4.51.0
fpdf2==2.7.8
geopandas==0.14.3
idna==3.6
imageio==2.34.0
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
matplotlib==3.8.4
networkx==3.3
numpy==1.26.4
openpyxl==3.1.2
osmnx==1.9.2
packaging==24.0
pandas==2.2.1
pillow==10.3.0
platformdirs==4.2.0
plumbum==1.8.2
pooch==1.8.1
psutil==5.9.8
pyaedt==0.8.7
pycparser==2.22
pyedb==0.7.0
pyparsing==3.1.2
pyproj==3.6.1
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.1
pyvista==0.43.5
pywin32==306
referencing==0.34.0
requests==2.31.0
rpds-py==0.18.0
rpyc==6.0.0
scikit-rf==0.32.0
scipy==1.13.0
scooby==0.9.2
shapely==2.0.3
six==1.16.0
SRTM.py==0.3.7
tzdata==2024.1
urllib3==2.2.1
utm==0.7.0
vtk==9.2.6

C:\Users\212508492\AppData\Roaming\Python\Python311>

**Comment by gmalinve** [comment]
Hi @Herve-L1,

Thanks for opening this issue.
What is causing the issue for you?
`point_object = hfss.modeler.primitives.create_point([0,0,0], name="mypoint")`
correctly creates a point object.
We should only fix the typo in _primivites_ to _primitives_ but the method works as expected.

Thanks,

Giulia

**Comment by gmalinve** [comment]
Hi @Herve-L1,

I think you are a bit confused.
In your code snippet you are mixing the native API and PyAEDT.
Here you inizialize Maxwell correctly with PyAEDT:

`from pyaedt import Maxwell2d
#m2d = Maxwell2d(specified_version="2024.1")`

but then you are not leveraging PyAEDT. You don't need that to access the modeler in this way:

`oDesktop = m2d.odesktop
oProject = oDesktop.GetActiveProject()
oDesign = oProject.GetActiveDesign()
MyProject = oProject.GetName()
Mydesign = oDesign.GetName()
oEditor = m2d.modeler`

you can access the modeler by simply calling:

`mod = m2d.modeler`

to access all modeler methods, such as the create_point()

`point = m2d.modeler.create_point(position=[0,0,0], name="mypoint")`

All of the create_point methods you listed above are correct.
As stated in the documentation the only required argument is _position_ (first argument) then all the others are optional _name_ and _color_ .
As long as you define them in order you can avoid specifying the argument names but for clarity is always good to specify them

Hope this helps!
Kind regards

Giulia

**Comment by Herve-L1** [comment]
Hi Giulia
Thanks a lot.

This clarify things.
For all those object
oDesktop = m2d.odesktop oProject = oDesktop.GetActiveProject() oDesign = oProject.GetActiveDesign() MyProject = oProject.GetName() Mydesign = oDesign.GetName()

of courses they are not needed for create point, but they are use in sub.

Where must I ask questions about syntax,  method ?

I want to move ”wk_pt” to another coordinate after to have read Mag in field calculator.

Best regards

Hervé


De : gmalinve ***@***.***>
Envoyé : mardi 23 avril 2024 12:02
À : ansys/pyaedt ***@***.***>
Cc : Lavalee, Herve (GE Vernova) ***@***.***>; Mention ***@***.***>
Objet : EXT: Re: [ansys/pyaedt] pyaedt modeler modeler2d Modeler2D create_point syntax error in example (Issue #4565)

AVERTISSEMENT: cet email provient de l'extérieur de GE. Veuillez valider l'adresse e-mail de l'expéditeur avant de cliquer sur les liens ou les pièces jointes, car ils risquent de ne pas être sûrs.

Hi @Herve-L1<https://github.com/Herve-L1>,

I think you are a bit confused.
In your code snippet you are mixing the native API and PyAEDT.
Here you inizialize Maxwell correctly with PyAEDT:

from pyaedt import Maxwell2d #m2d = Maxwell2d(specified_version="2024.1")

but then you are not leveraging PyAEDT. You don't need that to access the modeler in this way:

oDesktop = m2d.odesktop oProject = oDesktop.GetActiveProject() oDesign = oProject.GetActiveDesign() MyProject = oProject.GetName() Mydesign = oDesign.GetName() oEditor = m2d.modeler

you can access the modeler by simply calling:

mod = m2d.modeler

to access all modeler methods, such as the create_point()

point = m2d.modeler.create_point(position=[0,0,0], name="mypoint")

All of the create_point methods you listed above are correct.
As stated in the documentation the only required argument is position (first argument) then all the others are optional name and color .
As long as you define them in order you can avoid specifying the argument names but for clarity is always good to specify them

Hope this helps!
Kind regards

Giulia

**Comment by gmalinve** [comment]
Hi @Herve-L1,

First I'd suggest you to reply directly in GitHub, otherwise if you reply via email people can see your details (if this can cause you problems).
If you'd like to post questions, open discussions and in general for any other doubt please post it here in the discussion section: https://github.com/ansys/pyaedt/discussions.

If you have any doubts or would like to understand how PyAEDT works a good starting point is our examples page where you can download and run them locally: https://aedt.docs.pyansys.com/version/stable/examples/index.html. You can download them either as python files or Jupyter notebook.

Regarding your question:
Move points to a different coordinate system is not possible in AEDT. You can create them in a different coordinate system then the Global one though.
Suppose you have a dummy cs called _dummy_cs_ if you want to create a point relative to it you have to set the coordinate system first and then create the point: 
`m2d.modeler.set_working_coordinate_system("dummy_cs")
point = m2d.modeler.create_point([0, 0, 0], name="Point1")`

Hope this helps!
Kind regards,

Giulia

**Comment by gmalinve** [comment]
Hi @Herve-L1,

I was thinking that you actually could move your point to a different cs in two different ways:
- You could remove the old point, set the new coordinate system as the working cs (as I showed you in my previous reply) and then create a new point.
or
- Keep your point and moving its position calculating the quaternion between the old cs and the new one
