### ISSUE TITLE
Bug located in multi desktop

### ISSUE THREAD

**Issue by ring630** [ansys/pyaedt#4571]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

First desktop is 222
Second desktop is 222 although specified_version=232

### Steps To Reproduce

settings.use_multi_desktop = True
d222 = Desktop(new_desktop_session=True, specified_version=222)
d232 = Desktop(new_desktop_session=True, specified_version=232)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by Samuelopez-ansys** [comment]
@ring630 This is fixed in the last pyaedt release
