### ISSUE TITLE
Add support for Discovery Link

### ISSUE THREAD

**Issue by IreneWoyna** [ansys/pyaedt#4682]
### Description of the feature

Add support for Discovery Link, see IronPython code below

### Steps for implementing the feature

oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.CreateUserDefinedModel(
	[
		"NAME:UserDefinedModelParameters",
		[
			"NAME:Definition",
			[
				"NAME:UDMParam",
				"Name:="		, "GeometryFilePath",
				"Value:="		, "\"C:\\disco_demo.dsco\"",
				"DataType:="		, "String",
				"PropType2:="		, 0,
				"PropFlag2:="		, 1
			]
		],
		[
			"NAME:Options",
			[
				"NAME:UDMParam",
				"Name:="		, "IsDiscoveryLink",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Solid Bodies",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 0
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Surface Bodies",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 0
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Parameters",
				"Value:="		, "\"eCADImportParameterType_Independent,eCADImportParameterType_None,eCADImportParameterType_Independent,eCADImportParameterType_All\"",
				"DataType:="		, "String",
				"PropType2:="		, 1,
				"PropFlag2:="		, 0
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Parameter Key",
				"Value:="		, "\"\"",
				"DataType:="		, "String",
				"PropType2:="		, 0,
				"PropFlag2:="		, 0
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Named Selections",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Material Properties",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 0
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Import As Lightweight",
				"Value:="		, "0",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 1
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Facet Level",
				"Value:="		, "\"3,1,2,3,4,5\"",
				"DataType:="		, "String",
				"PropType2:="		, 1,
				"PropFlag2:="		, 1
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Use Parasolid For Transfer",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Tolerant Stitching",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Stitch Tolerance",
				"Value:="		, "0.1",
				"PropType2:="		, 3,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Tighten Gaps",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Tighten Gaps Tolerance",
				"Value:="		, "1e-06",
				"PropType2:="		, 3,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Cleaning",
				"Value:="		, "0",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Use Associativity",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Attributes",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Import Coordinate Systems",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Decompose Disjoint Faces",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Import Using Instances",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Line Bodies",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Mixed Import Resolution",
				"Value:="		, "\"eMixedImport_None\"",
				"DataType:="		, "String",
				"PropType2:="		, 0,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Enclosure and Symmetry Processing",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Reader Mode Saves Updated File",
				"Value:="		, "0",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Smart CAD Update",
				"Value:="		, "0",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			],
			[
				"NAME:UDMParam",
				"Name:="		, "Import Work Points",
				"Value:="		, "1",
				"DataType:="		, "Int",
				"PropType2:="		, 5,
				"PropFlag2:="		, 8
			]
		],
		[
			"NAME:GeometryParams"
		],
		"DllName:="		, "SACADIntegUDM",
		"Library:="		, "installLib",
		"Version:="		, "1.0",
		"ConnectionID:="	, ""
	])

**Comment by Samuelopez-ansys** [comment]
@IreneWoyna please could you share an example?
