### ISSUE TITLE
Update 3D components

### ISSUE THREAD

**Issue by BenjaminFriess** [ansys/pyaedt#4693]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hello,

I'm trying to modify the attribute from a boundary power source in Icepak, but I don't manage to modify this attribute. When I execute the code below, the value is temporary modified, but is not stored in the project :

icepak.boundaries[136].props['Total Power Variation Data']['Variation Values'][1] = 'pwl(50,Temp)'

Does someone have any idea on how to modify this attribute?
The boundary I'm trying to access belongs to a 3dcomponent from the project

Thanks
Benjamin

### Steps To Reproduce

icepak.boundaries[136].props['Total Power Variation Data']['Variation Values'][1] = 'pwl(50,Temp)'

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

pyaedt

**Comment by lorenzovecchietti** [comment]
Hi @BenjaminFriess, I'm very sorry for the late reply.
I assume you want to locally update the 3d component (so the original file is unchanged):
```
import os
import pyaedt
import tempfile

component_name = "IcepakDesign1_1"
ipk = pyaedt.Icepak(r"C:\Users\lvecchie\OneDrive - ANSYS, Inc\Desktop\Project4.aedt", specified_version="2024.1")

#Get component handler, edit it and define an update BC
cmp = ipk.modeler.user_defined_components[component_name ]
ipk_cmp = cmp.edit_definition()
ipk_cmp.boundaries[0].delete()
ipk_cmp.assign_solid_block("Box1", "1W")

# Use a temporary file to update (locally) the component definition
with tempfile.TemporaryDirectory() as temp_dir:
    fullpath=os.path.join(temp_dir,'comp.a3dcomp')
    ipk_cmp.modeler.create_3dcomponent(fullpath)
    cmp.update_definition(output_file=fullpath, local_update=True)

# Close the component project
ipk_cmp.close_project()
```

The argument `local_update=False` has been added to the PR linked to this issue. If you want to overwrite the original component or write a new component, you can just ignore that argument and run:
`cmp.update_definition(output_file=non_temporary_path)`
