### ISSUE TITLE
Bug located in "create_page_port(name="name", location=[], angle=90)"

### ISSUE THREAD

**Issue by giuseppe1692** [ansys/pyaedt#4718]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Hi everyone,
using this function I noticed that changing the angle from 90 to 180 degrees does not change anything. You can't do the flip unless you go through IronPython. Could you correct it as soon as possible? Thank you

### Steps To Reproduce

Use the method to create page port

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

altgraph==0.17.4
ansys-pythonnet==3.1.0rc3
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
auto-py-to-exe==2.43.3
Babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
bottle==0.12.25
bottle-websocket==0.2.9
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.2
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
Eel==0.16.0
et-xmlfile==1.1.0
exceptiongroup==1.2.0
executing==2.0.1
fastjsonschema==2.19.1
fiona==1.9.6
fonttools==4.49.0
fpdf2==2.7.8
fqdn==1.5.1
future==1.0.0
geopandas==0.14.3
gevent==24.2.1
gevent-websocket==0.10.1
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.4
httpx==0.27.0
idna==3.6
imageio @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/imageio-2.34.0-py3-none-any.whl#sha256=08082bf47ccb54843d9c73fe9fc8f3a88c72452ab676b58aca74f36167e8ccba
ipykernel==6.29.3
ipython==8.22.2
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.3
json5==0.9.22
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter-events==0.9.1
jupyter-lsp @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/jupyter_lsp-2.2.4-py3-none-any.whl#sha256=da61cb63a16b6dff5eac55c2699cc36eac975645adee02c41bdfc03bf4802e77
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.13.0
jupyter_server_terminals==0.5.3
jupyterlab @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/jupyterlab-4.1.4-py3-none-any.whl#sha256=f92c3f2b12b88efcf767205f49be9b2f86b85544f9c4f342bb5e9904a16cf931
jupyterlab_pygments==0.3.0
jupyterlab_server @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/jupyterlab_server-2.25.3-py3-none-any.whl#sha256=c48862519fded9b418c71645d85a49b2f0ec50d032ba8316738e9276046088c1
kiwisolver==1.4.5
lxml==5.2.1
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/matplotlib_inline-0.1.6-py3-none-any.whl#sha256=f1f41aab5328aa5aaea9b16d083b128102f8712542f819fe7e6a420ff581b311
mistune==3.0.2
nbclient==0.10.0
nbconvert==7.16.2
nbformat==5.10.3
nest-asyncio @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/nest_asyncio-1.6.0-py3-none-any.whl#sha256=87af6efd6b5e897c81050477ef65c62e2b2f35d51703cae01aff2905b1852e1c
networkx==3.2.1
notebook_shim @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/notebook_shim-0.2.4-py3-none-any.whl#sha256=411a5be4e9dc882a074ccbcae671eda64cceb068767e9a3419096986560e1cef
numpy==1.26.4
openpyxl @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/openpyxl-3.1.2-py2.py3-none-any.whl#sha256=f91456ead12ab3c6c2e9491cf33ba6d08357d802192379bb482f1033ade496f5
osmnx @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/osmnx-1.9.1-py3-none-any.whl#sha256=804790b4963f915ca172f56ef27a9bd62347c44616902a1c8a12dc3d94737f4b
overrides @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/overrides-7.7.0-py3-none-any.whl#sha256=c7ed9d062f78b8e4c1a7b70bd8796b35ead4d9f510227ef9c5dc7626c60d7e49
packaging==24.0
pandas==2.2.1
pandocfilters @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/pandocfilters-1.5.1-py2.py3-none-any.whl#sha256=93be382804a9cdb0a7267585f157e5d1731bbe5545a85b268d6f5fe6232de2bc
parso @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/parso-0.8.3-py2.py3-none-any.whl#sha256=c001d4636cd3aecdaf33cbb40aebb59b094be2a74c556778ef5576c175e19e75
pefile==2023.2.7
pillow==10.2.0
platformdirs==4.2.0
plum-dispatch==1.7.4
plumbum==1.8.2
pooch==1.8.1
prometheus_client @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/prometheus_client-0.20.0-py3-none-any.whl#sha256=cde524a85bce83ca359cc837f28b8c0db5cac7aa653a588fd7e84ba061c329e7
prompt-toolkit @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/prompt_toolkit-3.0.43-py3-none-any.whl#sha256=a11a29cb3bf0a28a387fe5122cdb649816a957cd9261dcedf8c9f1fef33eacf6
psutil==5.9.8
pure-eval==0.2.2
pyaedt==0.8.6
pycparser==2.21
pyedb==0.7.0
Pygments @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/pygments-2.17.2-py3-none-any.whl#sha256=b27c2826c47d0f3219f29554824c30c5e8945175d888647acd804ddd04af846c
pyinstaller==6.5.0
pyinstaller-hooks-contrib==2024.3
pyparsing==3.1.2
pyproj @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/pyproj-3.6.1-cp310-cp310-win_amd64.whl#sha256=db3aedd458e7f7f21d8176f0a1d924f1ae06d725228302b872885a1c34f3119e
python-dateutil==2.9.0.post0
python-json-logger @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/python_json_logger-2.0.7-py3-none-any.whl#sha256=f380b826a991ebbe3de4d897aeec42760035ac760345e57b812938dc8b35e2bd
python-pptx==0.6.23
pythonnet==3.0.3
pytomlpp @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/pytomlpp-1.0.13-cp310-cp310-win_amd64.whl#sha256=fab6e69a754d3be5d8580753feac56fa70d2f4f9388f1d7a30c719ceca2d3ff2
pytz==2024.1
pyvista @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/pyvista-0.43.3-py3-none-any.whl#sha256=5eb589bbea294761cd44aed0330481019e8eca2ddb950a1f332a5a132000e93d
pywin32==306
pywin32-ctypes==0.2.2
pywinpty==2.0.13
PyYAML @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/PyYAML-6.0.1-cp310-cp310-win_amd64.whl#sha256=fd1592b3fdf65fff2ad0004b5e363300ef59ced41c2e6b3a99d4089fa8c5435d
pyzmq @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/pyzmq-25.1.2-cp310-cp310-win_amd64.whl#sha256=fa99973d2ed20417744fca0073390ad65ce225b546febb0580358e36aa90dba6
referencing @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/referencing-0.33.0-py3-none-any.whl#sha256=39240f2ecc770258f28b642dd47fd74bc8b02484de54e1882b74b35ebd779bd5
requests==2.31.0
rfc3339-validator @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/rfc3339_validator-0.1.4-py2.py3-none-any.whl#sha256=24f6ec1eda14ef823da9e36ec7113124b39c04d50a4d3d3a3c2859577e7791fa
rfc3986-validator @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/rfc3986_validator-0.1.1-py2.py3-none-any.whl#sha256=2f235c432ef459970b4306369336b9d5dbdda31b510ca1e327636e01f528bfa9
rpds-py @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/rpds_py-0.18.0-cp310-none-win_amd64.whl#sha256=7223a2a5fe0d217e60a60cdae28d6949140dde9c3bcc714063c5b463065e3d66
rpyc @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/rpyc-6.0.0-py3-none-any.whl#sha256=e86b5831378f794c623db46e8ade6fff766c56cf9dbe96886e614025b4647339
scikit-rf @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/scikit_rf-0.31.0-py3-none-any.whl#sha256=9b60c29c0c69632fba1331db3a8bb0bbb64b92287ee154eb359b8f54208f5e28
scipy @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/scipy-1.12.0-cp310-cp310-win_amd64.whl#sha256=75ea2a144096b5e39402e2ff53a36fecfd3b960d786b7efd3c180e29c39e53f2
scooby @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/scooby-0.9.2-py3-none-any.whl#sha256=3cbc59de9febf8c8ba1e01bc7d08b4eca18ece3212d38b08a6f45188f88c8ea9
Send2Trash @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/Send2Trash-1.8.2-py3-none-any.whl#sha256=a384719d99c07ce1eefd6905d2decb6f8b7ed054025bb0e618919f945de4f679
shapely @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/shapely-2.0.3-cp310-cp310-win_amd64.whl#sha256=64c5013dacd2d81b3bb12672098a0b2795c1bf8190cfc2980e380f5ef9d9e4d9
six==1.16.0
sniffio @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/sniffio-1.3.1-py3-none-any.whl#sha256=2f6da418d1f1e0fddd844478f41680e794e6051915791a034ff65e5f100525a2
soupsieve @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/soupsieve-2.5-py3-none-any.whl#sha256=eaa337ff55a1579b6549dc679565eac1e3d000563bcb1c8ab0d0fefbc0c2cdc7
Spire.Presentation==9.3.0
SRTM.py @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/SRTM.py-0.3.7-py3-none-any.whl#sha256=8c08cc5f0833415b807003a7dea93bcf83bb68f798656f12be1df40a87b5b0b2
stack-data @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/stack_data-0.6.3-py3-none-any.whl#sha256=d5558e0c25a4cb0853cddad3d77da9891a08cb85dd9f9f91b9f8cd66e511e695
terminado @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/terminado-0.18.0-py3-none-any.whl#sha256=87b0d96642d0fe5f5abd7783857b9cab167f221a39ff98e3b9619a788a3c0f2e
tinycss2 @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/tinycss2-1.2.1-py3-none-any.whl#sha256=2b80a96d41e7c3914b8cda8bc7f705a4d9c49275616e886103dd839dfc847847
tomli @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/tomli-2.0.1-py3-none-any.whl#sha256=939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc
tornado @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/tornado-6.4-cp38-abi3-win_amd64.whl#sha256=10aeaa8006333433da48dec9fe417877f8bcc21f48dda8d661ae79da357b2a63
traitlets @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/traitlets-5.14.1-py3-none-any.whl#sha256=2e5a030e6eff91737c643231bfcf04a65b0132078dad75e4936700b213652e74
types-python-dateutil @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/types_python_dateutil-2.8.19.20240106-py3-none-any.whl#sha256=efbbdc54590d0f16152fa103c9879c7d4a00e82078f6e2cf01769042165acaa2
typing_extensions @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/typing_extensions-4.10.0-py3-none-any.whl#sha256=69b1a937c3a517342112fb4c6df7e72fc39a38e7891a5730ed4985b5214b5475
tzdata @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/tzdata-2024.1-py2.py3-none-any.whl#sha256=9068bc196136463f5245e51efda838afa15aaeca9903f49050dfa2679db4d252
uri-template @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/uri_template-1.3.0-py3-none-any.whl#sha256=a44a133ea12d44a0c0f06d7d42a52d71282e77e2f937d8abd5655b8d56fc1363
urllib3 @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/urllib3-2.2.1-py3-none-any.whl#sha256=450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d
utm @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/utm-0.7.0-py3-none-any.whl#sha256=19457f175c8d79a32d594b3c2571c8204e65cd0b8eebf7be76811c9ee1f8525b
virtualenv-clone==0.5.7
vtk @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/vtk-9.3.0-cp310-cp310-win_amd64.whl#sha256=2aae778297817335ddd6698b4c124c109d8ac476512691fe19446614ae43ba56
wcwidth @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/wcwidth-0.2.13-py2.py3-none-any.whl#sha256=3da69048e4540d84af32131829ff948f1e022c1c6bdb8d6102117aac784f6859
webcolors @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/webcolors-1.13-py3-none-any.whl#sha256=29bc7e8752c0a1bd4a1f03c14d6e6a72e93d82193738fa860cbff59d0fcc11bf
webencodings @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/webencodings-0.5.1-py2.py3-none-any.whl#sha256=a0af1213f3c2226497a97e2b3aa01a7e4bee4f403f95be16fc9acd2947514a78
websocket-client @ file:///C:/Users/giuseppe.giordano/Desktop/venv_giuseppe/venv_giuseppe/libreria_esterna/websocket_client-1.7.0-py3-none-any.whl#sha256=f4c3d22fec12a2461427a29957ff07d35098ee2d976d3ba244e688b8b4057588
whichcraft==0.6.1
xlrd==2.0.1
XlsxWriter==3.2.0
xlutils==2.0.0
xlwt==1.3.0
zope.event==5.0
zope.interface==6.2

**Comment by gmalinve** [comment]
Hi @giuseppe1692,

you can always access the angle property in pyaedt after you created it: 
`my_port = self.aedtapp.modeler.schematic.create_page_port("my_port", [0,0,0], 0)`
`my_port.angle = 90`

Hope this helps,

Giulia

**Comment by giuseppe1692** [comment]
Hi @gmalinve,
thank you for your answer. 
Unfortunately it doesn't work and I get this warning: 
PyAEDT WARNING: Grpc doesn't support angle settings because special characters are not supported.

**Comment by gmalinve** [comment]
@giuseppe1692, ok let me investigate.
In the meantime I see you are still using an older version of pyaedt. Could you please upgrade to the latest and re-try?

**Comment by giuseppe1692** [comment]
Hi @gmalinve 
I've updgraded to 0.9.1 but there is the same issue.

Below the code: 

```python
resistor = aedt_app.modeler.schematic.create_resistor(value=0, location=[offset_x + 1000, offset_y])
page_port = aedt_app.modeler.schematic.create_page_port(name="DUT_" + str(site) + "_" + lista_net_needle[i], location=[offset_x+1500,offset_y], angle=90)
page_port.angle = 180 
```

**Comment by gmalinve** [comment]
@giuseppe1692 which version of AEDT are you using?

**Comment by gmalinve** [comment]
@giuseppe1692 I suppose you are using version < 2023.1.

**Comment by giuseppe1692** [comment]
Hi @gmalinve,
On my local PC I'm using 2023.2
I'll try 2024.1 and let you know.

**Comment by gmalinve** [comment]
@giuseppe1692 I'm pretty sure with 2024.1 you won't have any issue.
The fact is that all versions previous to 2024.1 (2023.2 included), if launched in grpc mode, don't allow this parameter to be changed.
