### ISSUE TITLE
Make sorting optional for `DataSet.update()` 

### ISSUE THREAD

**Issue by nathmay** [ansys/pyaedt#4801]
### Description of the feature

The `update()` method in `application.Variables.DataSet` class sorts the dataset by it's X coordinate values - both for 1D and 3D datasets. While this makes sense for 1D, could be problematic for 3D datasets. I was only updateing the `v` column of a 3D dataset, and seeing weird results because of this :)

### Steps for implementing the feature

- At the very least, [improving documentation ](https://aedt.docs.pyansys.com/version/0.9/API/_autosummary/pyaedt.application.Variables.DataSet.update.html) to reflect this sorting behavior would be helpful.
- Make the sorting optional, if possible through a passed argument.

**Comment by Samuelopez-ansys** [comment]
Hi @nathmay, please could you provide a 3D Dataset just to check the new code is working as expected?

Thanks!

**Comment by Samuelopez-ansys** [comment]
@nathmay  Please try: https://github.com/ansys/pyaedt/pull/4803
