### ISSUE TITLE
Example Maxwell3D_Team3_bath_plate.py is failing

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/pyaedt#4840]
Since the release of version `0.9.4`, some changes have broken example Maxwell3D_Team3_bath_plate.py.

For example, this test was failing in the release of `0.9.6`. Bellow is a screenshot extracted from the CICD of the release's documentation with example job.
![image](https://github.com/ansys/pyaedt/assets/146729917/8a0b028c-f76e-4b38-babf-b675a32f512c)

**Comment by Samuelopez-ansys** [comment]
@SMoraisAnsys This PR should fix it https://github.com/ansys/pyaedt/pull/4839
