### ISSUE TITLE
Add documentation and examples for installed Examples

### ISSUE THREAD

**Issue by Devin-Crawford** [ansys/pyaedt#4871]
### Description of the feature

The current AEDT installation has 3 script examples that are purely scripts. 
- ``Examples/Circuit/Automation/FWS_Scripting_SPICE.aedt``
- ``Examples/Circuit/Automation/FWS_Scripting_SSS.aedt``
- ``Examples/Circuit/Automation/FWS_Scripting_TS.aedt``
These should be documented with examples in this repository.

### Steps for implementing the feature

See the scripts that are embedded in these examples.

**Comment by Samuelopez-ansys** [comment]
@dcrawforAtAnsys Should this issue be assined to PyAEDT... or to a different repo? :)
