### ISSUE TITLE
Bug located in GeometryModeler.create_region()

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyaedt#4972]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

See the [HFSS unit cell example](https://aedt.docs.pyansys.com/version/stable/examples/02-HFSS/HFSS_FSS_unitcell.html#sphx-glr-examples-02-hfss-hfss-fss-unitcell-py). In HFSS 24R1 the z and y dimensions are swapped.

### Steps To Reproduce

Run this [example](https://aedt.docs.pyansys.com/version/stable/examples/02-HFSS/HFSS_FSS_unitcell.html#sphx-glr-examples-02-hfss-hfss-fss-unitcell-py). Look at the airbox. The y-dimension is too big, while z is not correct. 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

accessible-pygments==0.0.4
aiofiles==23.2.1
aiohttp==3.9.3  
aiosignal==1.3.1
aiosqlite==0.20.0
alabaster==0.7.16
annotated-types==0.6.0
ansys-aedt-toolkits-antennas @ file:///C:/Users/dcrawfor/repo/pyaedt-antenna-toolkit
ansys-aedt-toolkits-motor @ file:///C:/Users/dcrawfor/repo/pymotorcad-pyaedt-toolkit
ansys-aedt-toolkits-template @ file:///C:/Users/dcrawfor/repo/toolkits/FMCW_Radar_Plots
ansys-motorcad-core @ git+https://github.com/pyansys/pymotorcad.git@a116ea034b0a6938e1b6f6b53971b6f3d2b5dec3
ansys-pythonnet==3.1.0rc3
ansys-sphinx-theme==0.15.2
anyio==3.7.1
apeye==1.4.1
apeye-core==1.1.5
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
autodocsumm==0.2.12
Babel==2.14.0
backcall==0.2.0
backports.tarfile==1.0.0
beautifulsoup4==4.13.0b2
black==24.4.0
bleach==6.1.0
blinker==1.7.0
build==1.0.3
CacheControl==0.14.0
certifi==2024.2.2
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.2
commonmark==0.9.1
contourpy==1.2.0
coverage==7.4.4
cssutils==2.9.0
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.8.0rc2
dict2css==0.3.0.post1
distlib==0.3.8
docutils==0.20
docutils-stubs==0.0.22
domdf-python-tools==3.8.0.post2
entrypoints==0.4
et-xmlfile==1.1.0
exceptiongroup==1.2.0
execnet==2.0.2
executing==2.0.1
fastjsonschema==2.19.1
filelock==3.13.3
fiona==1.9.6
Flask==3.0.2
fonttools==4.50.0
fpdf==1.7.2
fpdf2==2.7.9
fqdn==1.5.1
frozenlist==1.4.1
geopandas==0.14.3
h11==0.12.0
html5lib==1.1
httpcore==0.13.7
httpx==1.0.0b0
identify==2.5.35
idna==3.7
imageio==2.34.0
imageio-ffmpeg==0.4.9
imagesize==1.4.1
importlib_metadata==7.1.0
iniconfig==2.0.0
ipykernel==6.29.3
ipython==8.23.0
ipython-genutils==0.2.0
ipywidgets==8.1.2
isoduration==20.11.0
itsdangerous==2.1.2
jaraco.classes==3.3.1
jaraco.context==5.3.0
jaraco.functools==4.0.0
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
json5==0.9.24
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.4
jupyter-sphinx==0.5.3
jupyter-ydoc==2.0.1
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.13.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.4
jupyterlab_widgets==3.0.10
jupytext==1.16.1
keyring==25.0.0
kiwisolver==1.4.5
lab==8.1
livereload==2.6.3
lockfile==0.12.2
m2r2==0.3.3.post2
markdown-it-py==2.2.0
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
mdit-py-plugins==0.4.0
mdurl==0.1.2
mistune==2.0.5
mock==5.1.0
more-itertools==10.2.0
mpld3==0.5.10
mpmath==1.3.0
msgpack==1.0.8
multidict==6.0.5
munch==4.0.0
mypy-extensions==1.0.0
myst-parser==2.0.0
natsort==8.4.0
nbclassic==1.0.0
nbclient==0.10.0
nbconvert==7.16.3
nbformat==5.10.3
nbsphinx==0.9.3
nest-asyncio==1.6.0
networkx==3.2.1
nh3==0.2.17
nodeenv==1.8.0
notebook==7.1.2
notebook_shim==0.2.4
numpy==1.26.4
numpydoc==1.6.0
openpyxl==3.2.0b1
osmnx==1.9.1
overrides==7.7.0
packaging==24.0
pandas==2.2.1
pandocfilters==1.5.1
parso==0.8.3
pathspec==0.12.1
pep517==0.13.1
pickleshare==0.7.5
pillow==10.2.0
pkginfo==1.10.0
platformdirs==4.2.0
plotly==5.20.0
pluggy==1.4.0
plumbum==1.8.2
pooch==1.8.1
pre-commit==3.7.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
psutil==5.9.8
pure-eval==0.2.2
pyaedt==0.9.10
pyaedt-examples @ file:///C:/Users/dcrawfor/repo/pyaedt-examples
pyargus==1.1.post1
pycparser==2.21
pycrdt==0.8.16
pydantic==2.6.4
pydantic_core==2.16.3
pydata-sphinx-theme==0.14.4
pyedb==0.22.0
Pygments==2.17.2
pypandoc==1.13
pyparsing==3.1.2
pyproj==3.6.1
pyproject_hooks==1.0.0
pyqtgraph==0.13.4
pyrsistent==0.20.0
PySide6==6.7.0
PySide6_Addons==6.7.0
PySide6_Essentials==6.7.0
pysmithplot @ git+https://github.com/schlatterbeck/pySmithPlot.git@b6dbf4bc443e2b0dc949aadba0fbd6da9ee6ca50
pytest==8.1.1
pytest-cov==4.1.0
pytest-xdist==3.5.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pythonnet==3.0.3
pytomlpp==1.0.13
pytz==2024.1
pyvista==0.43.4
pywin32==306
pywin32-ctypes==0.2.2
pywinpty==2.0.13
PyYAML==6.0.1
pyzmq==25.1.2
QDarkStyle==3.2.3
qtconsole==5.5.1
QtPy==2.4.1
readme_renderer==43.0
recommonmark==0.7.1
referencing==0.34.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3339-validator==0.1.4
rfc3986==1.5.0
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.0
rpyc==6.0.0
Rtree==1.3.0
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
scikit-learn==1.4.1.post1
scikit-rf==0.32.0
scipy==1.12.0
scooby==0.9.2
Send2Trash==1.8.3
shapely==2.0.3
shiboken6==6.7.0
simplejson==3.19.2
six==1.16.0
sniffio==1.3.1
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.6
sphinx-autodoc-typehints==2.0.0
sphinx-copybutton==0.5.2
sphinx-gallery==0.15.0
sphinx-jinja==2.0.2
sphinx-jinja2-compat==0.2.0.post1
sphinx-prompt==1.8.0
sphinx-tabs==3.4.5
sphinx-toolbox==3.5.0
sphinx_design==0.5.0
sphinx_subfigure==0.2.4
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-quizdown @ git+https://github.com/bonartm/sphinxcontrib-quizdown@d9f24a7a2305ad5b196e06597b1779c9414d1d85
sphinxcontrib-serializinghtml==1.1.10
sphinxcontrib-video==0.2.0
sphinxcontrib-websupport==1.2.7
SRTM.py==0.3.7
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
terminado==0.18.1
threadpoolctl==3.4.0
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tornado==6.4
traitlets==5.14.2
trame==3.5.4
trame-client==2.16.5
trame-components==2.2.1
trame-deckgl==2.0.3
trame-markdown==3.0.1
trame-matplotlib==2.0.3
trame-plotly==3.0.2
trame-rca==0.4.1
trame-router==2.2.0
trame-server==2.17.2
trame-simput==2.4.1
trame-vega==2.1.1
trame-vtk==2.8.5
trame-vuetify==2.4.3
twine==5.0.0
txt2tags==3.9
types-python-dateutil==2.9.0.20240316
typing_extensions==4.10.0
tzdata==2024.1
uri-template==1.3.0
urllib3==2.2.1
utm==0.7.0
virtualenv==20.25.1
vtk==9.2.6
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
Werkzeug==3.0.1
widgetsnbextension==4.0.10
wslink==1.12.4
y-py==0.6.2
yarl==1.9.4
ypy-websocket==0.12.4
zipp==3.18.1

**Comment by fwlfHS** [comment]
So basically the order of the directions has changed over time in the API. It used to be ["+X", "+Y", "+Z", "-X", "-Y", "-Z"] and now it is: ["+X", "-X", "+Y", "-Y", "+Z", "-Z"]. The example uses the old order. Please update the example.

**Comment by SMoraisAnsys** [comment]
@dcrawforAtAnsys If https://github.com/ansys/pyaedt/pull/4978 fixes this issue, can you close it ?

**Comment by dcrawforAtAnsys** [comment]
Fixed in #4978
