### ISSUE TITLE
No PyAedt function to assign Floating excitation in Electrostatic solver

### ISSUE THREAD

**Issue by AlfVII** [ansys/pyaedt#5009]
### Description of the feature

This option from the GUI is missing in a Pythonic way in PyAedt
![image](https://github.com/user-attachments/assets/9e6d11ba-152a-4a6c-a857-56bd8c230fad)

```

### Steps for implementing the feature

I worked around it by:
```
project.odesign.GetModule("BoundarySetup").AssignFloating(
[
    "NAME:FloatingCore",
    "Objects:="     , [x.name for x in part_that_I_want_floating],
    "Value:="       , "0"
])

**Comment by gmalinve** [comment]
Hi @AlfVII,

If you'd like I can cover this :)
Please do let me know.

Regards,

Giulia
