### ISSUE TITLE
User Guide mentions `analyze_nominal()` which does not exist

### ISSUE THREAD

**Issue by A-Phamfam** [ansys/pyaedt#5029]
### Description of the current limitations

The User Guide section on Postprocessing has the following snippet, but the method .analyze_nominal() does not exist.

```
from pyaedt import Hfss
hfss = Hfss()
hfss.analyze_nominal()

traces_to_plot = hfss.get_traces_for_plot(second_element_filter="P1*")
report = hfss.post.create_report(traces_to_plot)  # Creates a report in HFSS
solution = report.get_solution_data()
plt = solution.plot(solution.expressions)  # Matplotlib axes object.
```

### Useful links and references

https://aedt.docs.pyansys.com/version/dev/User_guide/postprocessing.html

**Comment by Samuelopez-ansys** [comment]
@A-Phamfam Thank you. It is fixed here: https://github.com/ansys/pyaedt/pull/5032
