### ISSUE TITLE
Speed up execution of export from 3D Layout to HFSS/Q3D while keeping net name

### ISSUE THREAD

**Issue by skandak-ansys** [ansys/pyaedt#5052]
### Description of the feature

When exporting 3d layout design to MCAD/Q3D with `keep_net_name=True`, the current API command execution is extremely slow which I believe is due to the unite operation after exporting to MCAD. Uniting geometries in MCAD has few issues:

1. If the physically touching geometries belong to different materials then merging them would be incorrect.
   a. This is a fairly common occurance where-in one signal layer in 3d layout is of material M1 and the other signal layer is of material M2. If there's a signal net that runs thru both layers, after export to MCAD, only one material will be present and assigned to geometries on both layers. This is undesirable.

2. After exporting to MCAD, the user may want to create a port on one of the inner geometries. If the geometries get united, then this inner geometry will be swallowed by the outer geometry and it would make it much harder to create port.

3. Even for relatively small designs, the export operation is super slow.
  a. A moderately sized design took me 2 days to export using the API.

Suggestion:
Instead of uniting geometries in MCAD, it would be useful if the geometries are left as is but their names renamed, ex: all geometries belonging to GND net can be named GND_1, GND_2,..etc instead of uniting everything and calling it GND. This way we can preserve all material properties and the export will also be faster as no union operation is needed.

### Steps for implementing the feature

```
from pyaedt import Hfss3dLayout

# change “projectPath” and “designName” as required
h3dl = Hfss3dLayout(projectPath, designName, non_graphical=True) 

# create a dummy setup
setup = h3dl.create_setup()

# change path as required and export to HFSS/Q3D
setup.export_to_hfss(path/to/save/hfssMCAD.aedt, True)
setup.export_to_q3d(path/to/save/Q3D.aedt, True)

# close 3DL project
h3dl.close_project()
```

**Comment by Samuelopez-ansys** [comment]
Hi @skandak-ansys ,


Please try this PR:

https://github.com/ansys/pyaedt/pull/5054

Next time you could try to implement the solution if you think a method can be improved :)

Thanks
