### ISSUE TITLE
No function for HFSS toolkit finite array beam angle calculator option in pyAEDT

### ISSUE THREAD

**Issue by libt-pyint** [ansys/pyaedt#5053]
### Description of the current limitations

![Screenshot 2024-08-15 160331](https://github.com/user-attachments/assets/5edf7f4d-4ca9-4965-b2de-5fb2aeceed4f)
There isn't a way to use this GUI ability with pyAEDT

**Comment by Samuelopez-ansys** [comment]
@libt-pyint  This is a python toolkit. It is not part of the AEDT API. 

BUT, recently PyAEDT added a new set of farfield classes, which includes some of these capabilities.

https://aedt.docs.pyansys.com/version/stable/API/Visualization.html#farfield

For instance, if you have 3DComponent array, you can use this method and once you have the ffdata change the taper algorithm, the phase and magnitude of each element... everything computed in python:

https://aedt.docs.pyansys.com/version/stable/examples/02-HFSS/Array.html#sphx-glr-examples-02-hfss-array-py
