### ISSUE TITLE
Defining the folder where the batch.log file is created

### ISSUE THREAD

**Issue by Samuelopez-ansys** [ansys/pyaedt#5083]
### Discussed in https://github.com/ansys/pyaedt/discussions/5060

<div type='discussions-op-text'>

<sup>Originally posted by **shizzlemaster** August 19, 2024</sup>
Hello community,

I am using pyaedt to write a simulation script that is called by another application and I have the following issue:

The batch.log is created in the folder of my external application e.g. .../my_application/

This is not wanted in my case and I want to specify the directory where the batch.log is created but I do not know how.

Can anyone help me with this issue?

Thanks in advance

Marcus</div>

**Comment by SMoraisAnsys** [comment]
@Samuelopez-ansys Since I plan to update the settings as discussed before, I think that this could be also associated in this refactoring. Any idea of how this change can be performed ?

**Comment by Samuelopez-ansys** [comment]
@SMoraisAnsys THis is in my todo list, I think it is an argument in the AEDT initialization, like the non graphical mode. So when we call the ansysedt.exe, we should be able to redirect this file, which is not created by PyAEDT. It is AEDT that creates it when it is launched from batch.
