### ISSUE TITLE
Bug located in Maxwell Examples

### ISSUE THREAD

**Issue by DaveTwyman** [ansys/pyaedt#5085]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

https://aedt.docs.pyansys.com/version/stable/examples/03-Maxwell/Maxwell3D_Team3_bath_plate.html#set-up-sweep-value-and-plot-solution

![image](https://github.com/user-attachments/assets/40105bd1-7fab-4c3b-9b4e-32bda2483442)

### Steps To Reproduce

Click on example here
https://aedt.docs.pyansys.com/version/stable/examples/03-Maxwell/Maxwell3D_Team3_bath_plate.html#set-up-sweep-value-and-plot-solution

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

Issue is on example website so this isn't needed

**Comment by SMoraisAnsys** [comment]
Thanks @DaveTwyman, we have discovered this error (see https://github.com/ansys/pyaedt/issues/5082) and are working on it.

**Comment by DaveTwyman** [comment]
@SMoraisAnsys , Thanks that's great
