### ISSUE TITLE
Set temperature dependence

### ISSUE THREAD

**Issue by soliton37** [ansys/pyaedt#5111]
### Description of the feature

            Set temperature dependence in HFSS, no pyaedt equivalent command available to my knowledge.
            hfss.odesign.SetObjectTemperature(
                [
                    "NAME:TemperatureSettings",
                    "IncludeTemperatureDependence:=", True,
                    "EnableFeedback:=", True,
                    "Temperatures:=",
                    []
                ])

**Comment by Samuelopez-ansys** [comment]
Yes, it exists:

set_objects_temperature

https://aedt.docs.pyansys.com/version/0.10/API/_autosummary/ansys.aedt.core.modeler.modeler_3d.Modeler3D.set_objects_temperature.html#set-objects-temperature

I encourage you to clone the repository, and then easily you can search for AEDT API commands.
