### ISSUE TITLE
Bug located in ...PyAEDT Examples

### ISSUE THREAD

**Issue by DaveTwyman** [ansys/pyaedt#5123]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Two of the PyAEDT examples have the red 'Broken' stamp on them

https://aedt.docs.pyansys.com/version/stable/examples/04-Icepak/Icepak_CSV_Import.html#download-and-open-project

and 

https://aedt.docs.pyansys.com/version/stable/examples/01-HFSS3DLayout/EDB_in_3DLayout.html#initialize-aedt-and-launch-hfss-3d-layout

### Steps To Reproduce

Follow the links above

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

NA

**Comment by gmalinve** [comment]
@Samuelopez-ansys @SMoraisAnsys can we close this issue? it doesn't make sense now that we are about to publish the new examples.

**Comment by lorenzovecchietti** [comment]
Hi @DaveTwyman, I cannot see any error right now in those two examples. A recent PR might've solved those.

**Comment by lorenzovecchietti** [comment]
Sorry @gmalinve, I was replying at the same time as you :)

**Comment by gmalinve** [comment]
@lorenzovecchietti no worries :)
