### ISSUE TITLE
Add `edit_source` / `edit_sources` functionality for Eigenmode solutions

### ISSUE THREAD

**Issue by nzani** [ansys/pyaedt#5322]
### Description of the feature

Include the ability to edit the source distribution for Eigenmode-type solutions, as is possible in the GUI via Field Overlays -> Edit Sources... option for a simulation with this solution type

### Steps for implementing the feature

Under `hfss.py`, modify `edit_sources` to have particular functionality given the `hfss.solution_type` parameter is "Eigenmode". Specifically, format the `setting` object for the desired eigenmode setup (I would do this myself but I am struggling with finding/guessing the proper format for this).

**Comment by nzani** [comment]
Additionally - `edit_sources_from_file` does not work with Eigenmode solution type

**Comment by Samuelopez-ansys** [comment]
Hi @nzani ,

Thank you for your feedback, I have fixed the issue: https://github.com/ansys/pyaedt/pull/5330
