### ISSUE TITLE
Axial flux motor in RMxprt

### ISSUE THREAD

**Issue by lijinlong0308** [ansys/pyaedt#5366]
HI all,
        is it possible for us to build an axial flux motor with RMxprt using pyaedt? I can not find an example to achieve this.

**Comment by gmalinve** [comment]
Hi @lijinlong0308, 

There isn't any example specific to an axial flux motor with PyAEDT but there is an example of an Adjust-Speed Synchronous Machine: [https://examples.aedt.docs.pyansys.com/version/dev/examples/low_frequency/motor/aedt_motor/rmxpert.html](url).
This serves you as an example on how to interact with a Rmxprt session but you can adapt your script based on the machine type you are interested in. You can access the general, stator, rotor properties in the same way.

Hope this is clear.

Kind regards,

Giulia

**Comment by lijinlong0308** [comment]
Hi @gmalinve,
     Thanks for you tips.
     I checked the source code, maybe there is no similar modules like ASSM.
      Best,
              Jinlong

**Comment by lijinlong0308** [comment]
Hi, @gmalinve ,
      Thanks for your help.
      This issue is solved.
      Best,
                    Jinlong
