### ISSUE TITLE
Bug located in ...Circuit.load_project

### ISSUE THREAD

**Issue by Ronaldo-SIPI** [ansys/pyaedt#5407]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

may this is only a documentation thing
in the documentation the load_project attribut stated design_name= but in the usage only design= is allowed

![Image](https://github.com/user-attachments/assets/496e932f-d03f-4a68-b4ce-b5668ba1b3bb)

please correct that
regards Ronaldo

### Steps To Reproduce

import ansys.aedt.core
project_name = "circuit_reports.aedt"
aedtapp = ansys.aedt.core.Circuit.load_project(project_name, design="cir1", )

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3           
attrs==24.2.0                       
cffi==1.17.1                        
clr-loader==0.2.6                   
defusedxml==0.7.1                   
fonttools==4.53.1                   
fpdf2==2.7.9                        
jsonschema==4.23.0                  
jsonschema-specifications==2023.12.1
numpy==1.26.4
pandas==2.2.2
pillow==10.4.0
plumbum==1.8.3
psutil==6.0.0
pyaedt==0.10.2
pycparser==2.22
pydantic==2.9.1
pydantic_core==2.23.3
pyedb==0.28.0
python-dateutil==2.9.0.post0
pytz==2024.2
pywin32==306
PyYAML==6.0.2
referencing==0.35.1
rpds-py==0.20.0
rpyc==6.0.0
Rtree==1.3.0
scikit-rf==1.3.0
scipy==1.14.1
six==1.16.0
toml==0.10.2
typing_extensions==4.12.2
tzdata==2024.1

**Comment by Samuelopez-ansys** [comment]
Hi @Ronaldo-SIPI ,

I think your browser is not correctly loading the latest version, probably you need to clean the cache and cookies, because I see it correctly.

https://aedt.docs.pyansys.com/version/stable/API/_autosummary/ansys.aedt.core.circuit.Circuit.load_project.html

![Image](https://github.com/user-attachments/assets/85d5b25b-d9de-4831-b457-e4c483970724)
