### ISSUE TITLE
PyAEDT Installer / Installation

### ISSUE THREAD

**Issue by FgPy93** [ansys/pyaedt#5412]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

Open Issue under https://github.com/ansys/pyaedt/issues/5413

### Steps To Reproduce

https://github.com/ansys/pyaedt/issues/5413

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

Standard configuration of the installer.

**Comment by Samuelopez-ansys** [comment]
@FgPy93 Thank you for submitting this issue.

We realized this yesterday. A new PyAEDT has just been released (PyAEDT 0.11.4), and the console issue should be fixed.

Regarding the extension manager, I was not aware, and I have just fix it. Tomorrow I will create a new release.

https://github.com/ansys/pyaedt/pull/5414
