### ISSUE TITLE
Add Resistive Sheet boundary condition in Maxwell

### ISSUE THREAD

**Issue by IreneWoyna-HE** [ansys/pyaedt#5428]
### Description of the feature

Dear pyAEDT team! 

To me it seems that Resistive Sheet feature is missing in pyAEDT, could you please add it? It's quite similar to insulating boundary condition, the only inputs are the surface which it should be assigned to, and the resistance value.

Cheers
Irene

**Comment by IreneWoyna-HE** [comment]
this is the IronPython code:

oModule = oDesign.GetModule("BoundarySetup")
oModule.AssignResistiveSheet(
	[
		"NAME:ResistiveSheet1",
		"Objects:="		, ["contact_inner"],
		"Resistance:="		, "1ohm"
	])

**Comment by gmalinve** [comment]
@IreneWoyna-HE FYI I just open a PR for this!
