### ISSUE TITLE
Bug located in 'duplicate' function in modeler_pcb.py

### ISSUE THREAD

**Issue by abhandare21** [ansys/pyaedt#5438]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

User gets an error message when trying to duplicate a list of objects.

Current line 761 in https://github.com/ansys/pyaedt/blob/v0.11.3/src/ansys/aedt/core/modeler/modeler_pcb.py

`self.oeditor.Duplicate(["NAME:options", "count:=", count], ["NAME:elements", ",".join(assignment)], vector)`

Suggested change to fix bug

`self.oeditor.Duplicate(["NAME:options", "count:=", count], ["NAME:elements"]+assignment, vector)`

### Steps To Reproduce

```
# Imports
from pyaedt import Hfss3dLayout

# Variables
project_name = 'Duplicate function'
design_name= 'test'
aedt_version = '2024.2'
layer_name = 's'
pitch = 2e-3

# Create Hfss3dLayout instance
h3dl = Hfss3dLayout(projectname=project_name, designname=design_name, specified_version=aedt_version, close_on_exit=False)

# Create a new layer in the modeler
h3dl.modeler.layers.add_layer(layer_name, 'signal', '0mm', '0mm', 'copper')

# Create a rectangle
rect = [h3dl.modeler.create_rectangle(layer_name, origin=['0mm', '0mm'], sizes=['1mm', '1mm'])]

# Duplicate the rectangle 5 times in the x direction
rect.extend(h3dl.modeler.duplicate(rect, 4, [pitch, 0])[0])

# Duplicate the rectangle 5 times in the y direction
h3dl.modeler.duplicate(rect, 4, [0, pitch])

# Exit AEDT
h3dl.release_desktop(close_desktop=False, close_projects=False)
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.11

### Installed packages

python 3.11.0 installed using conda

pip install list
annotated-types==0.7.0
ansys-pythonnet==3.1.0rc4
attrs==24.2.0
cffi==1.17.1
clr-loader==0.2.6
defusedxml==0.7.1
fonttools==4.54.1
fpdf2==2.8.1
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
numpy==1.26.4
pandas==2.2.3
pillow==11.0.0
plumbum==1.9.0
psutil==6.1.0
pyaedt==0.11.3
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyedb==0.31.0
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.2
pywin32==308
PyYAML==6.0.2
referencing==0.35.1
rpds-py==0.21.0
rpyc==6.0.1
Rtree==1.3.0
scikit-rf==1.4.1
scipy==1.14.1
six==1.16.0
toml==0.10.2
typing_extensions==4.12.2
tzdata==2024.2

**Comment by gmalinve** [comment]
Close as #5491.
