### ISSUE TITLE
Add "Single Point" to add_eddy_current_sweep

### ISSUE THREAD

**Issue by IreneWoyna-HE** [ansys/pyaedt#5479]
### Description of the feature

Dear pyaedt team!

It seems that I can't add a single point, only single points (corresponding to Single Point Sweep):

![Image](https://github.com/user-attachments/assets/64a01ba7-eda2-4c84-a3d5-3990c901f4c5)

I tried this, but it doesn't add frequency sweep:

sim_setup = m2d.create_setup()
sim_setup.add_eddy_current_sweep(range_type="SinglePoints", start = 0.001)

Thanks in advance for looking into this.

Thanks
Irene

### Steps for implementing the feature

sim_setup = m2d.create_setup()
sim_setup.add_eddy_current_sweep(range_type="SinglePoints", start = 0.001)

**Comment by gmalinve** [comment]
@IreneWoyna-HE I'll close this one since I fix the issue in #5492.
It will be available in today's new release. 
Please do let me know!

Giulia

**Comment by IreneWoyna-HE** [comment]
Many thanks Giulia! I'll test asap.
