### ISSUE TITLE
Add hfss.mesh.assign_initial_mesh_manually() function for detailed mesh settings for the initial mesh.

### ISSUE THREAD

**Issue by FgPy93** [ansys/pyaedt#5551]
### Description of the feature

Create counterpart to the assign_initial_mesh_from_slider() method.

Easy implementation via the initial_mesh_settings.props dictionary. Similar to the assign_surface_mesh_manually but only for the initial mesh settings.

It would just complement the function overview for the hfss mesh.

### Steps for implementing the feature

something like:

def assign_initial_mesh_manually(args):

> mesh_props = hfss.initial_mesh_settings.props

    mesh_props[...] = ...

### Useful links and references

@Samuelopez-ansys

**Comment by Samuelopez-ansys** [comment]
@FgPy93 Please check this pull request:

https://github.com/ansys/pyaedt/pull/5556

You will be able to assign initial mesh with the manual settings. But, for now, there is no a pythonic way to edit these properties, you can get the initial mesh:

app.mesh.initial_mesh_settings

Remind to save the project to load the updated properties.
