### ISSUE TITLE
Maxwell3D: Eddy Current with DC Biased design type is missing

### ISSUE THREAD

**Issue by ansvdelafos** [ansys/pyaedt#5580]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug
I am using aedt 25.1
In src pyaedt/ansys/aedt/core/generic, constant.py, there is no solution type for the solver type that got introduced in 242 in Maxwell: Eddy Current , Include DC Fields
![Image](https://github.com/user-attachments/assets/55e636f6-638c-49a7-b3fb-e0643d822df5)

In .aedt project, we can see that this solver is named dcbiasededdycurrent

![Image](https://github.com/user-attachments/assets/a02bf0a3-90c5-4ca0-ad08-65bbfd7f6d81)

### Steps To Reproduce

You cannot create a project with this design type.
You can open an existing project created outside of pyaedt wit this design type, but the unknown design type will prevent you of running any command

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

annotated-types==0.7.0
ansys-pythonnet==3.1.0rc4
ansys-templates==4.0.0
arrow==1.3.0
attrs==24.2.0
binaryornot==0.4.4
certifi==2024.8.30
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.0
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.3.1
cookiecutter==2.2.3
cycler==0.12.1
defusedxml==0.7.1
fonttools==4.55.1
fpdf2==2.8.1
idna==3.10
importlib_metadata==8.5.0
isort==5.13.2
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
MarkupSafe==3.0.2
matplotlib==3.9.3
numpy==2.1.3
packaging==24.2
pandas==2.2.3
pillow==11.0.0
platformdirs==4.3.6
plumbum==1.9.0
pooch==1.8.2
psutil==6.1.0
pyaedt==0.11.7
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyedb==0.34.2
pyparsing==3.2.0
python-dateutil==2.9.0.post0
python-slugify==8.0.4
pytomlpp==1.0.13
pytz==2024.2
pyvista==0.44.2
pywin32==308
PyYAML==6.0.2
referencing==0.35.1
requests==2.32.3
rpds-py==0.22.3
rpyc==6.0.1
Rtree==1.3.0
scikit-rf==1.5.0
scipy==1.14.1
scooby==0.10.0
six==1.16.0
text-unidecode==1.3
toml==0.10.2
types-python-dateutil==2.9.0.20241003
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
vtk==9.3.1
zipp==3.21.0

**Comment by maxcapodi78** [comment]
@ansvdelafos Added in #5602
