### ISSUE TITLE
Install from wheelhouse is not working

### ISSUE THREAD

**Issue by hui-zhou-a** [ansys/pyaedt#5591]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

It is still trying to download pyaedt from internet.

![Image](https://github.com/user-attachments/assets/702aaa39-5642-474e-aada-3173fdf23d7e)

### Steps To Reproduce

follow the guideline to install pyaedt from wheelhouse.
https://aedt.docs.pyansys.com/version/stable/Getting_started/Installation.html#install-from-pyaedt-installer

![Image](https://github.com/user-attachments/assets/bd386683-b08f-459e-b2e7-4f9bbf175cc7)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

all

**Comment by Samuelopez-ansys** [comment]
@hui-zhou-a Did you install the "installer" wheelhouse? I think you were using the "all" one, which is only valid when you are installing it manually from your venv.

**Comment by hui-zhou-a** [comment]
@Samuelopez-ansys it is not working
![Image](https://github.com/user-attachments/assets/94a8038d-4762-4f95-aac7-693f261cd9af)
